# Gomme Vol I entries
gomme1_entries = [
    {
        "id": "accroshay",
        "slug": "accroshay",
        "title": "Accroshay",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "jumping-game",
        "tags": ["jumping", "outdoor", "children", "team", "victorian", "folk"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "A cap or small article is placed on the back of a stooping boy by other boys as each in turn jumps over him. The first as he jumps says 'Accroshay,' the second 'Ashotay,' the third 'Assheflay,' and the last 'Lament, lament, Leleeman's war.' The boy who in jumping knocks off either of the things has to take the place of the stooper.",
        "modern_description": "One player bends over as the 'stooper' while others balance a cap on his back. Each player takes a running jump over the stooper in turn, calling out the ritual words as they leap. If a jumper knocks the cap off, they become the new stooper. The game continues until everyone has had a turn or someone dislodges the cap.",
        "fun_fact": "This game's name and its rhythmic calling words ('Accroshay, Ashotay, Assheflay') are thought to derive from corrupted French phrases, reflecting the long history of cross-Channel cultural exchange in British folk games.",
        "image_prompt": "Victorian boys in school clothes playing a leaping game outdoors, one boy bent over while another jumps over him with a cap balanced on his back, country village setting, 1890s style illustration"
    },
    {
        "id": "all-a-row",
        "slug": "all-a-row",
        "title": "All a Row",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "singing-game",
        "tags": ["singing", "marching", "children", "rhyme", "folk", "procession"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "A marching game for very little children, who follow each other in a row singing: 'All a row, a bendy bow, / Shoot at a pigeon and kill a crow; / Shoot at another and kill his brother; / Shoot again and kill a wren, / And that'll do for gentlemen.'",
        "modern_description": "Small children line up one behind another in a long row. They march together while singing the rhyme about shooting birds. The game is simple and joyful, primarily serving as an introduction to group movement and song for the youngest players. No winners or losers — just a shared walking song.",
        "fun_fact": "This simple marching rhyme is one of thousands of children's singing games recorded by Alice Gomme in her landmark 1894 study, which remains the most comprehensive collection of traditional British children's folk games ever assembled.",
        "image_prompt": "A line of small Victorian children marching in a row through a village lane, mouths open singing, holding hands, countryside backdrop with a church steeple visible, soft watercolor style, 1890s"
    },
    {
        "id": "all-in-the-well",
        "slug": "all-in-the-well",
        "title": "All in the Well",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "throwing-game",
        "tags": ["throwing", "outdoor", "marbles", "stakes", "skill", "folk"],
        "difficulty": "beginner",
        "players": "2+",
        "equipment": ["wooden peg", "button", "marbles or buttons for stakes"],
        "family_friendly": True,
        "original_description": "A circle about eight inches in diameter is drawn on the ground, termed the 'well,' with a wooden peg (four inches tall) and a button balanced on top. Players give items — buttons or marbles — for a short stick to throw at the peg from a distance. If the button flies out of the circle, the player wins double value; otherwise they alternate until someone wins.",
        "modern_description": "Draw a small circle on the ground (the 'well') and stand a wooden peg upright in the center with a button balanced on top. Players take turns throwing a short stick at the peg from an agreed distance. If your throw knocks the button outside the circle, you win double the staked items. Otherwise, play alternates until someone succeeds.",
        "fun_fact": "A variant of this game was played at Newcastle Races with three pegs arranged in a triangle, each topped with a knife or copper coin — showing how folk games often adapted to local materials and festive occasions.",
        "image_prompt": "Victorian children gathered around a small circle drawn in dirt, one child throwing a short stick at a wooden peg with a button on top, excitement on their faces, rural English village, pen-and-ink illustration style"
    },
    {
        "id": "all-the-boys-in-our-town",
        "slug": "all-the-boys-in-our-town",
        "title": "All the Boys in Our Town",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "singing-game",
        "tags": ["singing", "ring-game", "partner-choosing", "courtship", "children", "folk"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Children form a ring with one child in the center. After the first verse, a child from the ring goes to join the center child. The rest sing verses while the central pair perform actions suiting the words, pairing off like sweethearts. The song runs: 'All the boys in our town / Shall lead a happy life, / Except 'tis ——, and he wants a wife.'",
        "modern_description": "Players form a large circle with one child in the middle. The ring sings about the center child wanting a sweetheart, whereupon a second child is invited to join the center. The two act out the courtship verses — turning, joining hands, and mimicking marriage — as the ring sings different verses. Each new round adds another couple until all are paired.",
        "fun_fact": "This singing game is one of a large family of Victorian partner-choosing games that mimicked adult courtship rituals, giving children a playful way to rehearse social customs surrounding marriage and romance.",
        "image_prompt": "Victorian children in a large ring outdoors, two children in the middle acting out courtship, girls in pinafores and boys in knee breeches, an English village green, sunny day, watercolor illustration"
    },
    {
        "id": "alligoshee",
        "slug": "alligoshee",
        "title": "Alligoshee",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "singing-game",
        "tags": ["singing", "paired", "dancing", "folk", "skipping", "children"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Children form pairs with arms linked behind. They skip forward then back while singing the first four lines, then turn about without loosing hands at the last line. One version runs: 'Betsy Blue came all in black... / Alligoshi, alligoshee, / Turn the bridle over my knee.'",
        "modern_description": "Players pair up and link arms behind each other's backs. Each pair skips forward together for four lines of the song, then skips backward, and finally turns around completely without letting go of each other's arms on the last line. The tricky turnaround is the fun challenge — keeping linked arms while spinning creates cheerful tangles.",
        "fun_fact": "The unusual word 'Alligoshee' is a fine example of how folk game rhymes often preserve corrupted or nonsense syllables from older languages, kept alive for centuries simply because children loved their sound.",
        "image_prompt": "Pairs of Victorian children with arms linked behind their backs, skipping together in a garden, girls in long dresses with pinafores, laughing as they try to turn without letting go, soft pastel illustration"
    },
    {
        "id": "angel-and-devil",
        "slug": "angel-and-devil",
        "title": "Angel and Devil",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "chasing-game",
        "tags": ["dramatic", "guessing", "chasing", "colour", "folk", "children", "role-play"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "One child acts as 'Angel,' one as 'Devil,' and one as 'Minder.' The Minder secretly assigns colours to the other children. Angel knocks and a guessing dialogue follows — if the Angel guesses a child's colour correctly, that child is led away to heaven. The Devil repeats the same, winning souls to the other side.",
        "modern_description": "The Minder secretly tells each remaining child their assigned colour. The Angel approaches, knocks, and asks the Minder to guess colours — each correct guess wins a child to the Angel's side. Then the Devil repeats the process. Whichever side collects more children at the end wins. The dramatic theme of heavenly and diabolical competition made this game irresistible to Victorian children.",
        "fun_fact": "This game survives in dozens of variants across Europe and reflects ancient folk beliefs about angels and devils competing for human souls — transformed into a safe, joyful children's game.",
        "image_prompt": "Victorian children playing Angel and Devil, one child dressed with paper wings as the Angel, another as the Devil, a Minder stands between groups of children in an autumn garden, theatrical and dramatic scene, 1890s illustration"
    },
    {
        "id": "auntieloomie",
        "slug": "auntieloomie",
        "title": "Auntieloomie",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "dancing-game",
        "tags": ["dancing", "ring-game", "singing", "kissing", "folk", "children", "maypole"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Children join hands and dance in a circle around an invisible May-pole with front step, back step, and side step. They sing: 'Can you dance the Auntieloomie? / Yes, I can; yes, I can.' The game ends with a kissing round, adding a romantic element familiar in many Victorian singing games.",
        "modern_description": "Players join hands and circle together using a three-step pattern — one step forward, one back, one to the side — while singing the question-and-answer song. The circle continues until the kissing verse, at which point players release hands and find a partner for a quick kiss before the round begins again.",
        "fun_fact": "The Auntieloomie dance was closely associated with May Day celebrations, and Gomme noted it as a rare survival of maypole-dancing customs in communities that no longer had an actual maypole.",
        "image_prompt": "Children dancing in a ring around an invisible maypole on a village green, holding hands and stepping in a folk dance pattern, spring blossoms in background, Victorian countryside, joyful expressions, watercolor"
    },
    {
        "id": "babbity-bowster",
        "slug": "babbity-bowster",
        "title": "Babbity Bowster",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "dancing-game",
        "tags": ["dancing", "kissing", "scottish", "folk", "handkerchief", "courtship", "singing"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": ["handkerchief"],
        "family_friendly": True,
        "original_description": "At the end of a country ball, a boy dances before the girls singing the first verse, throws a handkerchief on the selected girl for a kiss. The girl takes the handkerchief, sings the second verse, throws it to a boy, and is pursued back. Pairs form a line and dance like Sir Roger de Coverley. The song: 'Wha learned you to dance... / Babbity Bowster brawly?'",
        "modern_description": "This Scottish kissing dance closes a country ball. A boy dances solo before the assembled girls and drops a handkerchief at his chosen partner's feet. She picks it up, gives him a kiss, then dances before the boys and drops the handkerchief at her choice. The selected boy chases her around the room. When caught, they join the growing line that dances together in a reel-like conclusion.",
        "fun_fact": "Babbity Bowster (from 'bab at the bolster') was traditionally played using an actual bolster or pillow rather than a handkerchief — a survival of much older courtship customs at harvest festivals and rural dances.",
        "image_prompt": "A Scottish country dance at the end of a ball, one boy dancing before assembled girls throwing a handkerchief to a blushing girl, candlelit Scottish hall with tartan decorations, Georgian/early Victorian style, warm festive atmosphere"
    },
    {
        "id": "badger-the-bear",
        "slug": "badger-the-bear",
        "title": "Badger the Bear",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "chasing-game",
        "tags": ["rough", "outdoor", "bear", "keeper", "folk", "boys", "physical"],
        "difficulty": "intermediate",
        "players": "6+",
        "equipment": ["string or cord", "caps or handkerchiefs for pelting"],
        "family_friendly": True,
        "original_description": "One boy plays the 'Bear' on hands and knees, held by a string. A 'Keeper' defends him from attacks by other players who pelt him with caps and neckties on string. Players may only strike when the Keeper cries 'My Bear is free!' Any player who strikes too early becomes the new Bear.",
        "modern_description": "One player is the Bear (kneeling), held by a string held by the Keeper. The other players circle and taunt, waiting for the Keeper to shout 'My Bear is free!' — only then may they rush in and tag the Bear. The Keeper defends the Bear by blocking or pulling the string. Anyone who strikes before the signal takes the Bear's place.",
        "fun_fact": "This game dramatizes the once-popular sport of bear-baiting, transforming a brutal spectacle into a childhood game. It survived long after real bear-baiting was outlawed in Britain in 1835.",
        "image_prompt": "Victorian boys playing Badger the Bear outdoors, one boy on all fours as the bear on a string held by another boy acting as keeper, others circling with caps swinging on strings, energetic and boisterous, countryside 1890s illustration"
    },
    {
        "id": "ball-and-bonnets",
        "slug": "ball-and-bonnets",
        "title": "Ball and Bonnets",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "chasing-game",
        "tags": ["ball", "chasing", "caps", "outdoor", "folk", "boys", "penalty"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": ["ball", "caps or bonnets"],
        "family_friendly": True,
        "original_description": "Players' caps or bonnets are laid in a row. A ball is thrown into one cap from a distance. The owner of that cap must run while all others give chase until he is caught. The caught player then throws the ball. If a player accumulates six penalty stones in their cap, they must suffer 'buns' — bumps with the ball against the wall.",
        "modern_description": "Lay all players' caps in a row along a wall. One player throws the ball into any cap. The owner of that cap immediately runs, while all others chase them. When caught, the caught player must now throw the ball. Penalty stones accumulate in a cap if its owner is caught repeatedly — six stones earns a forfeit of bumps with the ball.",
        "fun_fact": "Variants of this cap-and-ball chasing game appear across Britain, Scotland, and Ireland under many names, suggesting it is one of the oldest continuously played folk games in the British Isles.",
        "image_prompt": "Victorian boys with caps laid in a row by a stone wall, one boy throwing a ball toward the caps while others crouch ready to run, autumn outdoor setting, energetic action scene, pen-and-ink illustration"
    },
    {
        "id": "banger",
        "slug": "banger",
        "title": "Banger",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "throwing-game",
        "tags": ["buttons", "throwing", "skill", "scoring", "folk", "boys", "outdoor"],
        "difficulty": "beginner",
        "players": "2+",
        "equipment": ["buttons"],
        "family_friendly": True,
        "original_description": "A button is laid near a wall. Other players snap their buttons against the wall in turn. Scoring is by span distance or direct hits, awarding one to four points each. The first player to reach the agreed number of points wins all the buttons staked.",
        "modern_description": "Each player stakes buttons as the prize pool. One button is placed near a wall as the target. Players take turns flicking their buttons against the wall. A button landing within a hand's span of the target scores one point; a direct hit scores more. First to the agreed winning total claims all the staked buttons. A simple game of finger skill that could keep Victorian children occupied for hours.",
        "fun_fact": "Buttons served as the small change of the Victorian schoolyard economy — wagered in games like Banger, Biscuit, and Span Farthing, they were as eagerly won and jealously guarded as real coins.",
        "image_prompt": "Victorian schoolboys crouched near a brick wall flicking buttons, concentration on their faces, buttons scattered on the ground, cobblestone street setting, 1890s style illustration"
    },
    {
        "id": "barley-break",
        "slug": "barley-break",
        "title": "Barley-Break",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "chasing-game",
        "tags": ["chasing", "teams", "outdoor", "mixed", "folk", "historical", "harvest"],
        "difficulty": "intermediate",
        "players": "6",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Six players (three of each sex) are coupled in pairs. The ground is divided into three compartments, with the middle called 'Hell.' The Hell couple must catch others from the end zones without separating. Caught players swap to Hell. The last couple remaining in Hell are said to be 'in Hell' and lose the game.",
        "modern_description": "Three couples play across a field divided into three zones. The middle zone is called Hell and always contains one unlucky couple. The Hell couple must chase and tag players from the end zones without uncoupling — they must stay linked. Any tagged pair swaps to become the new Hell couple. The game continues until all pairs have had a turn in Hell.",
        "fun_fact": "Barley-Break is one of the oldest named games in British history, mentioned by Philip Sidney in 1580 and referenced by John Fletcher in 1614. The 'barley' in the name likely refers to the stacks around which it was originally played at harvest time.",
        "image_prompt": "Elizabethan/Stuart-era young men and women playing Barley-Break in a field, two players linked in the middle zone trying to catch another couple running between zones, haystacks in the background, lively pastoral scene"
    },
    {
        "id": "bedlams-relievo",
        "slug": "bedlams-relievo",
        "title": "Bedlams (Relievo)",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "chasing-game",
        "tags": ["chasing", "teams", "prisoner", "outdoor", "rescue", "folk", "boys"],
        "difficulty": "intermediate",
        "players": "8+",
        "equipment": ["chalk for marking den"],
        "family_friendly": True,
        "original_description": "Sides are picked and a 'Den' (chalk square) is marked. A 'Tenter' guards the Den with one foot inside. Fielders run far out, shout 'Relievo,' and are pursued back to the Den. Caught players stay as prisoners unless the Tenter trips on 'Relievo' breaking through. When all are caught, sides reverse.",
        "modern_description": "Two teams play: one team guards a marked square (the Den) while the other team tries to run up, shout 'Relievo,' and race back without being tagged. Tagged players become prisoners in the Den. A free player can rescue all prisoners by successfully reaching the Den and shouting 'Relievo!' The guarding team wins when all opponents are captured.",
        "fun_fact": "Relievo is a direct ancestor of the modern schoolyard game of Prisoner's Base and British Bulldog. Its rules appear nearly unchanged in Victorian schoolyard accounts going back to the 1600s.",
        "image_prompt": "Victorian schoolboys playing Relievo in a schoolyard, one boy guarding a chalk-marked square while others dash toward it, captured boys standing as prisoners, brick school building in background, energetic action, 1890s illustration"
    },
    {
        "id": "bell-horses",
        "slug": "bell-horses",
        "title": "Bell-Horses",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "singing-game",
        "tags": ["singing", "marching", "procession", "children", "folk", "time-telling", "horses"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Children form trains, one behind the other. They march and sing the first four lines, then on the fifth line stand still and repeat. The song goes: 'Bell-horses... what time of day? / One o'clock, two o'clock, three, and away!'",
        "modern_description": "Children line up in a long chain, each with hands on the shoulders of the child ahead. They march together singing the Bell-Horses song, counting up the hours. When they sing 'away!' the train breaks apart and everyone gallops around before reforming the chain for the next verse. The game teaches counting while providing joyful movement.",
        "fun_fact": "Bell-horses refers to the lead horse in a team that wore bells on its harness so carters could hear the wagon coming. Children's games frequently referenced familiar everyday sights and sounds of Victorian rural life.",
        "image_prompt": "A line of small Victorian children marching in a train formation, hands on each other's shoulders, mouths open singing, a country road with a real horse and cart visible in the background, morning light, cheerful watercolor"
    },
    {
        "id": "bingo-folk-game",
        "slug": "bingo-folk-game",
        "title": "Bingo (Folk Game)",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "singing-game",
        "tags": ["singing", "spelling", "ring-game", "children", "folk", "farmer", "dog"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "A ring forms with one child in the center; they dance and sing while the center child points, spelling out B-I-N-G-O. A wrong letter or mis-step means the center child must swap with the pointed-to player. The song: 'The farmer's dog lay on the floor, / And Bingo was his name-O! / B-i-n-g-o, B-i-n-g-o, / And Bingo was his name-O!'",
        "modern_description": "Players stand in a ring with one in the middle. The ring walks and sings the Bingo song while the center player points at different people, calling out one letter at a time — B, I, N, G, O. If a player fails to step forward when pointed to, or the center child makes a spelling error, they swap places. An older, richer version of the song that would eventually evolve into the modern party classic.",
        "fun_fact": "This Victorian folk game version of Bingo predates the modern lottery-style Bingo game by decades and shows that the song and name were already beloved in British rural communities before 1894.",
        "image_prompt": "Victorian children in a circle outdoors, one child in the middle pointing at others while all sing, countryside setting with a farmhouse and dog in the background, bright sunny day, folk art style illustration"
    },
    {
        "id": "bird-apprentice",
        "slug": "bird-apprentice",
        "title": "Bird-Apprentice",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "guessing-game",
        "tags": ["guessing", "chasing", "birds", "teams", "outdoor", "folk"],
        "difficulty": "beginner",
        "players": "8+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Two parallel rows of children face each other. The first row secretly chooses bird names for each member. The second row calls out bird names; if a called name matches a first-row child's secret bird, that child must run to swap places before being caught. The caught children must 'ride' on the catchers' backs.",
        "modern_description": "Team A secretly assigns each member a bird name. Team B stands opposite and starts calling out bird names. When a name matches, that player from Team A must make a dash to switch places with any Team B player. If caught before reaching safety, the caught player rides piggyback. Teams then swap roles. The team that catches the most riders wins.",
        "fun_fact": "Bird-Apprentice is part of a large family of 'guessing-and-running' games found across Europe, all built on the same exciting mechanism of matching hidden names to trigger a chase.",
        "image_prompt": "Two rows of Victorian children facing each other in a garden, one child running frantically between the rows as others reach to catch them, laughter and excitement, a country house garden setting, 1890s watercolor"
    },
    {
        "id": "black-mans-tig",
        "slug": "black-mans-tig",
        "title": "Black Man's Tig",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "chasing-game",
        "tags": ["chasing", "rope", "linking", "outdoor", "folk", "children", "team"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": ["rope"],
        "family_friendly": True,
        "original_description": "A rope is tied to a gate or pole. One player holds the end and tries to catch another. Once captured, the caught player joins the chain by holding hands, helping to catch the rest. The chain grows longer and longer until all are caught.",
        "modern_description": "Tie a rope to a fixed point. One player holds the free end and tries to tag others. Each tagged player joins the chain, holding hands and extending its reach. As the chain grows it becomes an unstoppable sweeping line that traps players in corners. The game ends when all players are part of the chain — a joyful crescendo of a finale.",
        "fun_fact": "This rope-and-chain variant of Tig (British slang for Tag) is notable for its use of growing team cooperation as a central mechanic, making the game more exciting with every capture.",
        "image_prompt": "Victorian children outdoors, a long chain of linked children sweeping across a yard after one remaining free player, a rope tied to a gate post at one end, excited and laughing faces, 1890s ink illustration"
    },
    {
        "id": "black-thorn",
        "slug": "black-thorn",
        "title": "Black Thorn",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "singing-game",
        "tags": ["singing", "teams", "catching", "dialogue", "folk", "outdoor", "verse"],
        "difficulty": "beginner",
        "players": "8+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Two sides stand opposite each other, one against a wall. They sing a dialogue: 'Blackthorn! / Butter-milk and barley-corn; / How many geese have you today?' One side then rushes to catch the other; the last to be caught joins the winners' side. This continues until one side has all the players.",
        "modern_description": "Two teams face each other across an open space, one team with their backs to a wall. They exchange sung challenges and answers. On the final line, the team away from the wall rushes to catch as many of the wall team as possible before they escape. Each caught player switches sides. The game continues until one team has absorbed the other entirely.",
        "fun_fact": "The 'Black Thorn' game is one of many British children's games built on a sung dialogue that triggers a chase — a format so ancient it may predate recorded history.",
        "image_prompt": "Two lines of Victorian children facing each other on an open field, one line against a stone wall, both groups singing with arms reaching out, about to break into a chase, autumn leaves on the ground, 1890s illustration"
    },
    {
        "id": "blind-bell",
        "slug": "blind-bell",
        "title": "Blind Bell",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "chasing-game",
        "tags": ["blindfold", "bell", "chasing", "outdoor", "folk", "children", "sensory"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": ["blindfolds", "small bell"],
        "family_friendly": True,
        "original_description": "All players are blindfolded except the 'Bell,' who rings a bell and tries to evade the others. Any blindfolded player who catches the Bell wins, removes their blindfold, and becomes the new Bell. The tension comes from hearing the bell but not seeing it.",
        "modern_description": "One player holds a small bell and must keep ringing it while evading all the other players, who are blindfolded. The blindfolded players must navigate toward the sound of the bell and try to catch the ringer. The first to touch the Bell player wins and takes the bell as the next ringer. An exciting sensory game that rewards listening over looking.",
        "fun_fact": "Blind Bell is a rare inversion of the usual blindfold game — here it is the sighted player who is hunted, creating an unusual dynamic where sound guides the entire play.",
        "image_prompt": "Children with blindfolds stumbling toward one child ringing a small bell, outdoors on a lawn, reaching arms groping forward, the bell-holder tiptoeing away, Victorian garden setting, amusing pen-and-ink illustration"
    },
    {
        "id": "booman",
        "slug": "booman",
        "title": "Booman",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "dramatic-game",
        "tags": ["dramatic", "funeral", "singing", "ring-game", "death", "folk", "ritual"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": ["flowers optional"],
        "family_friendly": True,
        "original_description": "One child lies as the 'Booman' in the center of a ring. The ring of boys raises and lowers their hands like bells while the girls weep. They carry out a dramatic funeral: digging the grave and strewing flowers. The song: 'Dill doule for Booman... / Where shall we bury him? / Dig his grave...' A new Booman is then chosen.",
        "modern_description": "One child plays the 'Booman' — a recently deceased character — lying still in the center of the ring. The ring acts out a mock Victorian funeral with great solemnity: some children mime ringing bells, others weep, and all process around the body singing the dirge. They mime digging the grave, laying flowers, and bidding farewell before choosing the next Booman.",
        "fun_fact": "Booman is a striking example of how Victorian children used play to process the reality of death, which was far more visible in 19th-century life than today, with high child mortality and public funerals a common sight.",
        "image_prompt": "Victorian children performing a mock funeral game outdoors, one child lying dramatically in the center of a ring, others weeping or miming bell-ringing with solemn expressions, scattered flowers, a churchyard wall visible behind, theatrical and touching"
    },
    {
        "id": "boss-out",
        "slug": "boss-out",
        "title": "Boss-Out",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "marble-game",
        "tags": ["marbles", "skill", "boys", "outdoor", "folk", "shooting", "target"],
        "difficulty": "beginner",
        "players": "2",
        "equipment": ["marbles"],
        "family_friendly": True,
        "original_description": "One player bowls a marble as the mark. The antagonist bowls to try to hit it or land within a span's touch. A hit wins the mark marble outright. If neither hits on the first roll, players alternate until someone wins. A clean, simple two-player marble game of skill.",
        "modern_description": "Player one rolls their marble to stop wherever it lands. Player two rolls their marble trying to hit the first or land within a hand-span. A direct hit wins the target marble immediately. If both players miss, they alternate rolling until one succeeds. No complicated rules — pure aiming skill determines the winner.",
        "fun_fact": "Boss-Out is one of the simplest forms of the vast family of marble games played by British children for centuries, forming the basis for more elaborate games like Ring Taw and Plum Pudding.",
        "image_prompt": "Two Victorian boys crouching on a cobbled schoolyard, one aiming a marble at another marble on the ground, concentration on their faces, crowd of watching boys behind them, 1890s illustration"
    },
    {
        "id": "bridgeboard",
        "slug": "bridgeboard",
        "title": "Bridgeboard",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "marble-game",
        "tags": ["marbles", "board", "scoring", "bowling", "folk", "boys", "skill"],
        "difficulty": "beginner",
        "players": "2+",
        "equipment": ["wooden board with arched holes", "marbles"],
        "family_friendly": True,
        "original_description": "A board about a foot wide and four inches tall has numbered squares or holes along its ground edge, with numbers placed irregularly. Players bowl marbles through the holes to win the number written above. A miss means the marble is lost to the board's owner.",
        "modern_description": "A wooden board with arched holes cut along its base is set up against a wall. Each arch has a number above it — but the valuable numbers are placed in the harder-to-reach smaller arches. Players take turns rolling marbles from an agreed line, trying to thread a marble through an arch. Success wins you that arch's value in marbles; a miss adds your marble to the house.",
        "fun_fact": "Bridgeboard was a commercially popular carnival game as well as a children's folk game, with various board vendors setting up at fairs and markets where children could try their luck.",
        "image_prompt": "Victorian boys rolling marbles toward a wooden board with numbered arched holes propped against a wall, one marble curving perfectly through an arch, cheering onlookers, a market fair setting, 1890s illustration"
    },
    {
        "id": "brother-ebenezer",
        "slug": "brother-ebenezer",
        "title": "Brother Ebenezer",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "guessing-game",
        "tags": ["guessing", "mind-reading", "parlor", "folk", "trick", "medium", "names"],
        "difficulty": "intermediate",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Ebenezer goes out of the room. The remaining players choose a secret name, and a 'medium' uses subtle influence to guide Ebenezer's thinking toward the chosen name when he returns. Ebenezer must guess name after name until he hits the right one. The art lies in the medium's subtle assistance.",
        "modern_description": "One player (Ebenezer) leaves the room. The group chooses a secret name. When Ebenezer returns, one player acts as a 'medium' who secretly helps steer Ebenezer toward the right answer through subtle cues — emphasizing certain sounds, touching items, or using coded signals. The trick is effective enough that Ebenezer seems to read the group's mind.",
        "fun_fact": "Brother Ebenezer belongs to the rich Victorian tradition of apparently supernatural parlor games, where the real method — a confederate using agreed signals — was kept strictly secret from uninitiated guests.",
        "image_prompt": "A Victorian parlor scene, one man re-entering a drawing room to find a group of ladies and gentlemen, a woman acting as 'medium' whispering to him, candlelit atmosphere, mysterious and playful mood, 1880s"
    },
    {
        "id": "buck-buck",
        "slug": "buck-buck",
        "title": "Buck, Buck",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "guessing-game",
        "tags": ["guessing", "riding", "outdoor", "boys", "folk", "physical", "fingers"],
        "difficulty": "beginner",
        "players": "3+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "One boy stoops (the Buck) on a table with a rider on his back holding up fingers. 'Buck, buck, how many horns do I hold up?' The stooper must guess the number; a wrong guess means the position continues until correct. A variant has a whole row of stoopers that the rider leaps along while asking.",
        "modern_description": "The Buck bends over while a rider sits on their back, holding up some fingers. 'Buck, buck, how many horns do I hold up?' The Buck must guess the number without being able to see. A wrong guess means the rider stays on for another turn. Correct guess means the rider becomes the new Buck. With multiple stoopers, the rider leaps from back to back asking at each stop.",
        "fun_fact": "Buck, Buck is one of the oldest recorded British children's games — the Roman author Petronius mentions a nearly identical game called 'Bucca, bucca' played in ancient Rome, making it at least 2,000 years old.",
        "image_prompt": "Victorian boys playing Buck Buck, one boy bending over as the stooper with a rider on his back holding up fingers, other boys watching and laughing, a stone schoolyard, boisterous afternoon, 1890s pen-and-ink"
    },
    {
        "id": "buff-folk-game",
        "slug": "buff-folk-game",
        "title": "Buff (Folk Game)",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "forfeit-game",
        "tags": ["forfeit", "laughter", "folk", "dialogue", "stick", "singing", "ring"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": ["stick"],
        "family_friendly": True,
        "original_description": "Players sit in a row; one thumps a stick and delivers the dialogue. The goal is to make 'Buff' smile for a forfeit. 'Knock, knock! / Who's there? / Buff. / Buff says Buff to all his men, / And I say Buff to you again, / Buff neither laughs nor smiles.' Anyone who laughs pays a forfeit.",
        "modern_description": "Players sit in a line and one player goes before them as 'Buff,' performing an elaborate routine with a stick and delivering the ritual dialogue. The challenge is for Buff to maintain a perfectly straight face and for the row of players to resist laughing. Anyone who cracks a smile — player or audience — owes a forfeit to be paid later. A wonderful game of collective deadpan performance.",
        "fun_fact": "'Buff' — meaning a strong-faced, straight-faced person — gives us the phrase 'blind man's buff' and 'calling one's bluff.' This game may be the origin of both expressions.",
        "image_prompt": "A Victorian parlor game scene, one person standing solemnly with a stick before a row of seated people struggling desperately not to laugh, one person obviously failing to suppress a grin, gaslit drawing room, 1880s illustration"
    },
    {
        "id": "bull-in-the-park",
        "slug": "bull-in-the-park",
        "title": "Bull in the Park",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "chasing-game",
        "tags": ["chasing", "breaking-circle", "outdoor", "folk", "dialogue", "children"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "One child in the center circle (the Bull) asks: 'Where's the key of the park?' All but the last child answer 'Ask the next-door neighbour.' The last child answers: 'Get out the way you came in.' The Bull then dashes at the linked hands trying to break through; whoever the Bull catches becomes the new Bull.",
        "modern_description": "Players form a circle holding hands with one player (the Bull) in the center. The Bull asks 'Where's the key of the park?' and gets deflected with 'Ask the next-door neighbour' until the last player says 'Get out the way you came in!' The Bull then charges at the circle trying to break through the linked hands. Whoever's link is broken becomes the new Bull.",
        "fun_fact": "The Bull in the Park game is a survival of a much older tradition of circle-breaking games that may have originated in fertility rituals where breaking through a circle symbolized new life or new seasons.",
        "image_prompt": "Victorian children forming a tight hand-linked circle outdoors, one child in the center charging at the circle trying to break through linked hands, excited faces, a park with iron railings visible, 1890s illustration"
    },
    {
        "id": "barbarie-king",
        "slug": "barbarie-king",
        "title": "King of the Barbarie",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "singing-game",
        "tags": ["singing", "dramatic", "teams", "siege", "folk", "dialogue", "breaking-through"],
        "difficulty": "intermediate",
        "players": "8+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Two children join hands as a 'fortress.' A 'King' stands at a distance with soldiers behind. Soldiers surround the fortress, singing alternately with the fortress defenders: 'O will you surrender... / To the King of the Barbarie?' Eventually soldiers try to break the clasped hands; the King succeeds in breaking through, and the troop bursts through the gap.",
        "modern_description": "Two players stand as the Fortress by linking hands. A King leads a band of soldiers who surround the Fortress while both sides exchange sung challenges and defiant replies. The soldiers try to break the fortress by pulling apart the two linked children. When the King finally breaks through, all the soldiers flood through the gap to victory.",
        "fun_fact": "The 'King of the Barbarie' game survives from medieval siege-play traditions and was likely influenced by actual accounts of wars with Barbary pirates, which were major news events in the 16th and 17th centuries.",
        "image_prompt": "Victorian children re-enacting a siege game outdoors, two children as a castle with linked hands while a crowd of children as soldiers surrounds them singing, dramatic and playful, autumn garden, 1890s illustration"
    },
    {
        "id": "bag-o-malt",
        "slug": "bag-o-malt",
        "title": "Bag o' Malt",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "action-game",
        "tags": ["paired", "weighing", "rhyme", "folk", "children", "back-to-back"],
        "difficulty": "beginner",
        "players": "2",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Two children stand back to back, linked together near their armpits. They weigh each other up and down while repeating the rhyme: 'A bag o' malt, a bag o' salt, / Ten tens a hundred.'",
        "modern_description": "Two children stand back-to-back and hook their arms together at the elbows. Each alternately bends forward to lift the other off the ground and back again, like a living seesaw. Throughout, they chant the rhyme together. The game builds strength and coordination while the simple arithmetic rhyme (ten tens is a hundred) makes it educational too.",
        "fun_fact": "Back-to-back weighting games like Bag o' Malt appear in children's play records going back to at least the 17th century and were used informally to determine which of two children was heavier — a matter of some importance before bathroom scales existed.",
        "image_prompt": "Two Victorian children standing back-to-back with arms linked at the elbows, one leaning forward to lift the other off the ground, both grinning, a farmyard setting with grain sacks in the background, rustic illustration"
    },
    {
        "id": "betsy-bungay",
        "slug": "betsy-bungay",
        "title": "Betsy Bungay",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. I",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1894,
        "source_url": "https://www.gutenberg.org/ebooks/41727",
        "category": "folk-game",
        "subcategory": "singing-game",
        "tags": ["singing", "carrying", "sedan-chair", "folk", "action", "children", "rhyme"],
        "difficulty": "beginner",
        "players": "3",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Two children cross hands to make a 'sedan chair.' A third child sits on their linked hands. They sing: 'Hi, Betsy Bungay, all day on Sunday; / You're the lock and I'm the key, / All day on Monday.' On the last line, they unclasp their hands and drop their passenger.",
        "modern_description": "Two players face each other and cross their right hands to grasp each other's left wrists, forming a sturdy seat. A third player sits on this 'sedan chair.' The carriers walk while all three sing the Betsy Bungay song. On the final word, the carriers unclasp — sending the passenger tumbling onto the grass with a shriek of laughter.",
        "fun_fact": "The sedan chair — a covered litter carried by two footmen — was a luxury form of transport in 18th-century Britain, and this game mischievously mimics the grand experience before deliberately depositing the 'passenger' on the ground.",
        "image_prompt": "Three Victorian children playing sedan chair, two facing each other with crossed arms as the seat while a third sits on their hands being carried, all singing cheerfully, a garden path, moments before the passenger is dropped, watercolor illustration"
    },
]

print(f"Gomme Vol I entries: {len(gomme1_entries)}")
