# Gomme Vol II entries and Carroll entry
gomme2_entries = [
    {
        "id": "oats-and-beans-and-barley",
        "slug": "oats-and-beans-and-barley",
        "title": "Oats and Beans and Barley",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "singing-game",
        "tags": ["singing", "ring-game", "farming", "partner-choosing", "folk", "marriage", "action"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Players form a ring with one child in the center. The ring walks round singing while the center child mimics farming actions — sowing seed, standing, stamping foot, clapping hands, turning round. At 'open the ring and take one in,' the center child chooses a partner. The ring then sings a marriage formula while the couple stands together.",
        "modern_description": "One child stands in the center of a circle while the ring sings and walks around. At each action line — sowing seed, stamping, clapping, turning — everyone acts out the motion. When the song reaches 'open the ring and take one in,' the center child picks a partner who joins them. The ring sings a joyful marriage blessing to the pair, and the game continues with a new center child.",
        "fun_fact": "Oats and Beans and Barley is one of the most widely distributed folk games in Britain, with Gomme recording over 18 distinct regional variants from Shropshire to the Isle of Man — each with slightly different crops, actions, and marriage verses.",
        "image_prompt": "Victorian children in a circle on a farm field, one child in the middle mimicking sowing seeds with arms outstretched, others walking around singing, farm buildings visible in the background, golden afternoon light, watercolor"
    },
    {
        "id": "obadiah",
        "slug": "obadiah",
        "title": "Obadiah",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "action-game",
        "tags": ["cumulative", "chain", "action", "east-anglian", "folk", "collapse", "silly"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Players stand in a row. The head child says in a sing-song manner: 'My son Obadiah is going to be married, twiddle your thumbs!' All twiddle. The next adds 'Fall on one knee!' — all comply while still twiddling. Head adds 'Do as you see me.' As the last child repeats, the head falls onto the next, and all collapse like ninepins.",
        "modern_description": "Players stand in a row and the leader begins a cumulative chain of actions — first twiddling thumbs, then adding dropping to one knee, then adding more postures — all while continuing every previous action simultaneously. The chain grows absurdly complex. When the leader finally leans onto the next person, the whole row collapses in a delightful heap.",
        "fun_fact": "Obadiah is an East Anglian game named for the distinctly non-heroic Old Testament figure, and its cumulative collapse mechanic is closely related to the cumulative songs like 'Twelve Days of Christmas' in which each verse repeats all that came before.",
        "image_prompt": "A row of Victorian children in various awkward positions — twiddling thumbs, on one knee, leaning — about to collapse like dominoes, all grinning, a garden or schoolroom setting, comic illustration"
    },
    {
        "id": "old-dame",
        "slug": "old-dame",
        "title": "Old Dame",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "singing-game",
        "tags": ["singing", "procession", "chasing", "folk", "clock", "children", "drama"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": ["stool"],
        "family_friendly": True,
        "original_description": "One child (the 'old dame') sits on a stool while others march round in a file holding onto each other. They sing, asking the dame what time it is. The dame answers progressively up to 'eleven; you'll be hanged at twelve!' Then all run and the dame chases; whoever she catches becomes the new dame.",
        "modern_description": "One player sits on a stool as the Old Dame while the rest form a procession marching around her, holding each other's clothes. They sing to ask what time it is; the Dame answers with each hour from one to eleven, then declares 'you'll be hanged at twelve!' and springs up to chase the fleeing procession. The caught player becomes the new Old Dame.",
        "fun_fact": "The Old Dame's counting from one to twelve and the dramatic gallows threat at midnight echoes the widespread European custom of using clock-counting games to teach children to tell time through fear-tinged amusement.",
        "image_prompt": "Victorian children marching in a file around an old woman seated on a stool, mouths open counting hours in song, about to scatter in fright, a Yorkshire village schoolroom, 1890s illustration"
    },
    {
        "id": "old-roger-is-dead",
        "slug": "old-roger-is-dead",
        "title": "Old Roger Is Dead",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "dramatic-game",
        "tags": ["dramatic", "singing", "death", "funeral", "apple-tree", "ring-game", "folk"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "A ring forms around 'Roger' who lies covered on the ground. The ring sings about Roger dying with an apple tree over his head. One player enters as the tree, another as an old woman who picks apples. Roger suddenly jumps up and gives the woman a knock — she hobbles away, hipperty-hop, and the game begins again with a new Roger.",
        "modern_description": "One child plays Old Roger, lying still on the ground with a covered head. The circle sings about his death and the apple tree over his grave. One player enters as the apple tree, arms raised like branches; another plays the old woman stealing apples. When the song reaches the climax, Roger leaps up and chases the old woman. Whoever is caught becomes the next Roger.",
        "fun_fact": "Old Roger Is Dead is thought to be connected to ancient harvest-time rituals about the spirit of the grain dying and rising — 'Roger' being a common folk name for the corn-spirit in British agricultural mythology.",
        "image_prompt": "Victorian children around a boy lying on the ground covered with a cloth, one child standing with arms raised as an apple tree, another child stooping to mime picking apples, a ring of singers around them, autumn setting, dramatic folk illustration"
    },
    {
        "id": "old-soldier-folk",
        "slug": "old-soldier-folk",
        "title": "Old Soldier",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "forfeit-game",
        "tags": ["forfeit", "avoidance", "taboo-words", "role-play", "folk", "begging", "soldier"],
        "difficulty": "intermediate",
        "players": "4+",
        "equipment": ["walking stick"],
        "family_friendly": True,
        "original_description": "One player acts as an old soldier limping with a stick, begging garments and items from other players. When asked questions, players must answer without saying 'Yes,' 'No,' 'Nay,' 'Black,' 'White,' or 'Grey.' Those who slip and say a forbidden word owe a forfeit to the old soldier.",
        "modern_description": "The Old Soldier limps around (stick required) asking every player for donations and asking tricky questions designed to elicit the forbidden words. Players must answer naturally while avoiding 'Yes,' 'No,' 'Nay,' 'Black,' 'White,' and 'Grey' — which is far harder than it sounds. Every slip earns the soldier a forfeit. A superb Victorian vocabulary game.",
        "fun_fact": "Word-avoidance games like Old Soldier are among the oldest parlor entertainments in existence — similar games appear in medieval European manuscripts, and the specific taboo words varied by region and era.",
        "image_prompt": "A Victorian parlor, one man dressed as a limping old soldier with a stick approaching seated ladies and gentlemen, one lady with hand over mouth realizing she just said 'yes,' amused onlookers, firelit drawing room, 1880s"
    },
    {
        "id": "oranges-and-lemons",
        "slug": "oranges-and-lemons",
        "title": "Oranges and Lemons",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "singing-game",
        "tags": ["singing", "arch-game", "london-bells", "tug-of-war", "folk", "children", "choosing"],
        "difficulty": "beginner",
        "players": "8+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Two leaders (Orange and Lemon) face each other and raise their clasped hands as an arch. The other children pass underneath in a chain, singing about London's church bells. At the final line — 'here comes a chopper to chop off your head!' — the arch drops on a child, who is secretly asked to choose orange or lemon. When all are sorted, the two teams have a tug-of-war.",
        "modern_description": "Two players form an arch with clasped hands. The other players hold a chain and pass through the arch repeatedly while singing about the bells of London. At 'chop off your head!' the arch drops, catching one player, who whispers their choice of orange or lemon to join that team. When all players are assigned, the two fruit teams line up behind their leaders and pull in the great tug-of-war.",
        "fun_fact": "Oranges and Lemons is one of the most famous British children's folk songs, with Gomme recording 16 variants. The church bells mentioned (St. Clement's, Shoreditch, Stepney, Bow) formed a real geography of London's bell-ringing churches.",
        "image_prompt": "Victorian children passing in a long chain under an arch made by two children's raised arms, mouths open singing about London bells, a cheerful street scene, Georgian townhouses visible, bright afternoon, classic illustration"
    },
    {
        "id": "paddy-from-home",
        "slug": "paddy-from-home",
        "title": "Paddy from Home",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "guessing-game",
        "tags": ["guessing", "ring-passing", "string", "ring", "folk", "detective", "hiding"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": ["string", "small ring"],
        "family_friendly": True,
        "original_description": "Players in a ring hold a long loop of string with a small ring threaded on it. They pass the ring from hand to hand, concealing it, while singing 'Paddy from home has never been... travels along the railway.' The center child must guess which hand currently holds the ring.",
        "modern_description": "Thread a small ring on a loop of string that all players hold with both hands in a circle. Players sing the song while passing the ring secretly from hand to hand under their fingers. The child in the center watches carefully and must guess whose hands currently contain the ring. Success means the holder becomes the new guesser.",
        "fun_fact": "Ring-passing guessing games were played across medieval Europe under names like 'Hunt the Ring' and 'Find the Ring' — Gomme's version adds the distinctly Victorian detail of a railway journey in the accompanying song.",
        "image_prompt": "Victorian children in a circle each holding a shared loop of string, all trying to secretly pass a ring along while one child in the center watches hawk-like for movement, a parlor setting, focused expressions, 1890s illustration"
    },
    {
        "id": "peg-in-the-ring",
        "slug": "peg-in-the-ring",
        "title": "Peg-in-the-Ring",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "top-game",
        "tags": ["top", "spinning", "outdoor", "boys", "folk", "skill", "circle"],
        "difficulty": "intermediate",
        "players": "2+",
        "equipment": ["spinning tops", "chalk circle"],
        "family_friendly": True,
        "original_description": "A circle is drawn and players spin their tops inside it; the top must spin without overstepping. If a top fails to spin properly, it remains inside for others to peg (strike with their top). The player can cry 'One a penny!' to save their top from the first hit, 'Two a penny!' for the second, 'Three a penny!' to escape altogether.",
        "modern_description": "Draw a large ring in chalk. All players spin their tops inside the ring simultaneously. A top that stops or falls before the others or crosses the ring boundary is 'in' and becomes a target — other players may strike it with their spinning tops. The owner calls out their penalty tier ('One a penny!' through 'Three a penny!') to limit how many hits they must endure.",
        "fun_fact": "Top spinning was one of the most popular pastimes for Victorian boys, and specialized pegging-tops with metal tips were sold specifically for aggressive striking games like Peg-in-the-Ring.",
        "image_prompt": "Victorian schoolboys crouching around a chalk circle drawn on pavement, several spinning tops inside the ring, one boy launching his top to strike another boy's stopped top, concentration and competition, 1890s illustration"
    },
    {
        "id": "peg-top-folk",
        "slug": "peg-top-folk",
        "title": "Peg-Top",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "top-game",
        "tags": ["top", "spinning", "pegging", "outdoor", "boys", "folk", "skill", "striking"],
        "difficulty": "intermediate",
        "players": "2+",
        "equipment": ["spinning tops with metal pegs"],
        "family_friendly": True,
        "original_description": "A top is spun and others peg-strike it with their own tops while it spins. If a player fails to make their top spin properly, they must lay their top down to be struck by others. The ultimate prize: splitting the loser's top to release the metal peg as a trophy.",
        "modern_description": "Each player winds their top and spins it as powerfully as possible. Players then throw their spinning tops at each other's tops — the goal being to strike and split an opponent's top. A cracked-open top releases its metal peg, which the victor keeps as a trophy. Skill in throwing while maintaining spin is the essential challenge.",
        "fun_fact": "Victorian peg-tops were deliberately made with wooden bodies and iron pegs so that a strong strike could crack the wood — splitting an opponent's top was the ultimate victory and a point of great schoolyard pride.",
        "image_prompt": "Victorian boys in a schoolyard hurling spinning tops at each other's tops on the cobblestones, one top splitting apart with a crack, boys cheering, stone school building in background, vigorous action illustration"
    },
    {
        "id": "pillie-winkie",
        "slug": "pillie-winkie",
        "title": "Pillie-Winkie",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "action-game",
        "tags": ["blindfold", "striking", "eggs", "folk", "bird", "nest", "outdoor"],
        "difficulty": "intermediate",
        "players": "3+",
        "equipment": ["blindfold", "stick", "egg or similar small object"],
        "family_friendly": True,
        "original_description": "An egg, bird, or nest is placed in front of a blindfolded 'Winkie' who must strike it perpendicularly with a stick, breaking it without touching or destroying the surrounding area. Other players mislead Winkie with false descriptions. Breaking the target wins all staked items.",
        "modern_description": "Place a small target object on the ground. One player (Winkie) is blindfolded and handed a stick. The object is placed in front of them — but other players give confusing verbal directions about where it actually is. Winkie must bring the stick down straight to break or hit the target. Success wins the pool of staked objects; a miss gives others another chance to mislead.",
        "fun_fact": "Pillie-Winkie is a Scottish folk game, and its name likely comes from old Scots 'winkie' meaning a blinking or winking eye — perfectly fitting a game where the central action depends on being blindfolded.",
        "image_prompt": "A Scottish Victorian child blindfolded with a stick raised over a small object on the ground, other children pointing misleadingly in different directions, heather-covered moor background, excited and mischievous atmosphere"
    },
    {
        "id": "pinny-show",
        "slug": "pinny-show",
        "title": "Pinny Show",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "performance-game",
        "tags": ["peep-show", "flowers", "performance", "street", "folk", "children", "pins"],
        "difficulty": "beginner",
        "players": "2+",
        "equipment": ["flowers or pictures", "glass or cellophane", "framed paper with slit"],
        "family_friendly": True,
        "original_description": "A peep-show made with flowers or colored objects under glass, framed with a paper cover with a slit to peep through. Children charge one pin to peep. The song: 'A pin to see the poppet-show, / All manner of colours oh! / See the ladies all below.'",
        "modern_description": "A child constructs a miniature peep-show by arranging colorful flowers, cut pictures, or small figures under a piece of glass and framing it with decorated paper. A small slit allows viewers to look inside. The showman charges one pin per look and sings their advertisement. Other children pay the pin toll to glimpse the colorful display within.",
        "fun_fact": "Pinny Show is the children's domestic version of the adult peep-show booths common at Victorian fairs. Pins served as the smallest unit of currency in children's informal economies throughout the 19th century.",
        "image_prompt": "Victorian children gathered around a homemade peep-show box made from flowers under glass, one child peeking through a slit in the paper cover while another holds out their hand for payment, a cottage garden, charming folk illustration"
    },
    {
        "id": "pirley-pease-weep",
        "slug": "pirley-pease-weep",
        "title": "Pirley Pease-Weep",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "action-game",
        "tags": ["scottish", "sending", "direction", "folk", "boys", "assignment", "rhyme"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "A Scottish boys' game using the rhyme: 'Scotsman, Scotsman, lo! / Where shall this poor Scotsman go? / Send him east, or send him west, / Send him to the craw's nest.' The chosen direction sends players on various tasks or forfeits, similar to Hot Cockles.",
        "modern_description": "One player recites the rhyme and points in a direction — east, west, or to the crow's nest. Other players must run in the indicated direction or perform the assigned task. The game combines directional awareness with physical activity, and the crow's nest direction typically demands a climbing or hiding challenge.",
        "fun_fact": "The crow's nest as a game destination reflects the importance of trees in Scottish rural children's play — climbing to the highest possible point was a mark of daring that Victorian boys particularly prized.",
        "image_prompt": "Scottish boys playing outdoors near a large tree with a crow's nest, one boy pointing in a direction while others listen and prepare to run, Scottish moorland and stone walls, 1890s ink illustration"
    },
    {
        "id": "pize-ball",
        "slug": "pize-ball",
        "title": "Pize Ball",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "ball-game",
        "tags": ["ball", "batting", "fielding", "teams", "outdoor", "rounders-variant", "folk"],
        "difficulty": "intermediate",
        "players": "8+",
        "equipment": ["ball", "bat"],
        "family_friendly": True,
        "original_description": "Two sides (e.g., six against six) play with marks and tuts. Fielders throw to the home batter who 'pizes' (strikes the ball hard) and runs to a tut. If the runner is hit by the ball while running between bases, they are 'burnt' and out.",
        "modern_description": "Two teams set up bases (tuts) and a home mark. The batter hits the ball as hard as possible and runs to the nearest tut. Fielders retrieve and throw the ball, trying to hit the runner before they reach the safety of a tut. Being struck by the ball while running means the player is out. A direct ancestor of Rounders and a cousin of early baseball.",
        "fun_fact": "Pize Ball is one of the oldest recorded forms of bat-and-ball rounders in Britain, with 'pize' being an old British dialect word meaning to strike forcefully — suggesting the game dates to before modern standardized English.",
        "image_prompt": "Victorian boys playing a rounders-style game in a field, one boy hitting a ball hard with a stick while others run or stand at marked spots, a fielder hurling the ball at a runner, green English meadow, energetic scene"
    },
    {
        "id": "plum-pudding-marbles",
        "slug": "plum-pudding-marbles",
        "title": "Plum Pudding (Marbles)",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "marble-game",
        "tags": ["marbles", "row", "striking", "folk", "outdoor", "boys", "skill"],
        "difficulty": "beginner",
        "players": "2+",
        "equipment": ["marbles"],
        "family_friendly": True,
        "original_description": "Marbles are laid in a row at a taw mark. Players toss their shooting marble to strike out as many of the row as possible, taking them. The player continues hitting until all marbles are gone. Simple, satisfying, and the most universal form of marble play.",
        "modern_description": "Arrange a row of marbles along a line. From an agreed throwing distance, players take turns rolling or throwing their shooter marble to knock marbles out of the row. Every marble knocked out of the line is kept by the shooter. Players continue until the row is cleared. The player who collected the most marbles wins.",
        "fun_fact": "The name 'Plum Pudding' refers to the row of marbles looking like plums arranged in a pudding mold — Victorian children had a talent for finding delicious names for their outdoor games.",
        "image_prompt": "Victorian boys crouching around a row of marbles on a cobbled path, one boy throwing a shooter marble at the line with careful aim, others waiting their turn, an autumn schoolyard, traditional illustration"
    },
    {
        "id": "poor-mary-sits-weeping",
        "slug": "poor-mary-sits-weeping",
        "title": "Poor Mary Sits A-Weeping",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "singing-game",
        "tags": ["singing", "ring-game", "weeping", "courtship", "choosing", "folk", "dramatic"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "One child sits weeping in the center of a ring. The ring sings and asks why Mary weeps. She names her reason — sweetheart lost, father dead. The ring comforts her, telling her to choose a lover and marry. Variants include going to church, placing a ring on, and the couple kneeling together. The song: 'Poor Mary sits a-weeping / On a bright summer's day.'",
        "modern_description": "One player sits in the center of the circle, head bowed in dramatic weeping. The ring sings to ask why Mary weeps, and she replies with her sad reason. The ring then sings encouragement — choose a love, marry, be happy! Mary rises, chooses a partner from the ring, and the couple acts out the wedding verse together. Then the game begins again with a new weeping Mary.",
        "fun_fact": "Poor Mary Sits A-Weeping was recorded by Gomme in 20 variants across Britain, making it one of the most geographically widespread British singing games. Scholars believe it preserves ancient mourning rituals transformed into play.",
        "image_prompt": "A ring of Victorian girls surrounding one girl seated on the grass with head bowed in mock weeping, the ring singing with outstretched arms of comfort, a summer garden with roses, soft and dramatic folk illustration"
    },
    {
        "id": "pi-cow",
        "slug": "pi-cow",
        "title": "Pi-Cow",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "chasing-game",
        "tags": ["castle", "assault", "hiding", "folk", "outdoor", "teams", "strategy"],
        "difficulty": "intermediate",
        "players": "8+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Half the players keep a 'castle' (a central spot) while others forage nearby. A sentry cries 'Pee-ku' as a warning. Foragers try to reach the castle; if one enters without being captured, they cry 'The hole's won!' and the guards must yield. Captured foragers switch to the guarding side.",
        "modern_description": "One team defends the Castle (a marked central area) while the other team starts scattered around foraging. The castle sentry calls 'Pee-ku!' to warn of approaching foragers. Foragers try to creep or rush into the castle without being tagged. A successful entry wins a point and forces a role swap. Captured foragers join the defending team.",
        "fun_fact": "Pi-Cow combines elements of castle-storming, hide-and-seek, and territory games in a way that suggests it developed in communities where real castle sieges were a living memory — possibly dating to the medieval period.",
        "image_prompt": "Victorian children playing a castle siege game, one team clustered around a marked central area defending it, another team trying to sneak or dash through, excitement and strategy, a country estate with hedges, 1890s illustration"
    },
    {
        "id": "odd-or-even-folk",
        "slug": "odd-or-even-folk",
        "title": "Odd or Even",
        "source_book": "The Traditional Games of England, Scotland, and Ireland, Vol. II",
        "source_author": "Alice Bertha Gomme",
        "source_year": 1898,
        "source_url": "https://www.gutenberg.org/ebooks/41728",
        "category": "folk-game",
        "subcategory": "guessing-game",
        "tags": ["guessing", "buttons", "marbles", "chance", "folk", "boys", "arithmetic"],
        "difficulty": "beginner",
        "players": "2",
        "equipment": ["buttons or marbles"],
        "family_friendly": True,
        "original_description": "A simple boys' game with buttons, marbles, or halfpence. One player hides a number of objects in their closed hand. The opponent guesses whether the number is odd or even. A correct guess wins one object; incorrect guess loses one. The player with the most objects at the end wins.",
        "modern_description": "Player one secretly grabs a handful of buttons or marbles and closes their fist. Player two guesses: 'Odd or Even?' The fist opens to reveal the count. Guess right and win one object; guess wrong and lose one. Alternate the hiding and guessing roles. The first player to reach an agreed total — or who collects all the other's objects — wins.",
        "fun_fact": "Odd or Even is one of the most ancient games known to humanity — it appears in ancient Greece under the name Artiasmos and was played with pebbles or nuts. The Romans played it as 'Par Impar,' and it spread worldwide.",
        "image_prompt": "Two Victorian boys facing each other, one with a closed fist held out, the other pointing and calling 'Even!' a scatter of buttons on the ground between them, a schoolyard wall behind, concentrated expressions, 1890s illustration"
    },
]

carroll_entry = [
    {
        "id": "the-game-of-logic",
        "slug": "the-game-of-logic",
        "title": "The Game of Logic",
        "source_book": "The Game of Logic",
        "source_author": "Lewis Carroll",
        "source_year": 1887,
        "source_url": "https://www.gutenberg.org/ebooks/4763",
        "category": "board-game",
        "subcategory": "logic-game",
        "tags": ["logic", "syllogism", "board-game", "lewis-carroll", "counters", "deduction", "victorian", "educational"],
        "difficulty": "advanced",
        "players": "1-2",
        "equipment": ["9 counters (4 red, 5 grey)", "cardboard diagram board (smaller 2x2 grid and larger diagram for 3 attributes)", "instruction book"],
        "family_friendly": True,
        "original_description": "This ingenious game consists of a cardboard Diagram and nine Counters — four red and five grey. A red counter signifies that a compartment is occupied by at least one thing ('some'), while a grey counter signifies it is empty ('none'). By placing these counters on the Diagram according to logical propositions, the player represents premises and reads off their valid conclusion — solving syllogisms without resorting to abstract symbols. 'There foam'd rebellious Logic, gagg'd and bound.'",
        "modern_description": "Set up the cardboard diagram, which acts as a visual truth table with compartments for combinations of attributes. Red counters mean 'some exist here,' grey counters mean 'none exist here.' To solve a syllogism, mark both premises on the larger diagram using counters, then transfer the information to the smaller diagram to read the conclusion. Solo play involves working through Carroll's 101 example problems; two players can quiz each other, with one giving premises and the other deriving conclusions. Carroll intended the game to make formal Aristotelian logic accessible and fun for everyone.",
        "fun_fact": "Lewis Carroll wrote The Game of Logic in 1887, four years before the symbolic logic now taught in universities was standardized. His counter-based system was an independent invention of diagrammatic logic, predating Venn diagrams by only a few years — and Carroll claimed his method was easier for beginners.",
        "image_prompt": "A Victorian study with a large open book, a cardboard logic diagram with red and grey counters placed on its grid, an inkwell and feather quill, and faint handwritten syllogisms visible on nearby paper — the room of a Victorian logician at play, warm candlelight, Lewis Carroll era"
    }
]

print(f"Gomme Vol II entries: {len(gomme2_entries)}")
print(f"Carroll entries: {len(carroll_entry)}")
