# Hoffmann Puzzles Old and New entries
hoffmann_entries = [
    {
        "id": "pick-me-up-puzzle",
        "slug": "pick-me-up-puzzle",
        "title": "The Pick-Me-Up Puzzle",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "dexterity-puzzle",
        "tags": ["dexterity", "marble", "spiral", "steady-hand", "mechanical", "Victorian", "patience"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["cylindrical box with internal spiral incline", "marble"],
        "family_friendly": True,
        "original_description": "A cylindrical box contains a spiral incline. A marble must be worked steadily up and down the spiral without the box being jerked or tilted so violently that the marble flies off the track. The secret is a perfectly smooth, rhythmic motion — no sudden movements.",
        "modern_description": "Hold the cylindrical box with the marble inside. By gently tilting and rotating the box in a smooth, continuous motion, guide the marble up the internal spiral ramp. Any sudden jerk will send the marble off the track. The challenge is to maintain the steady, rhythmic wrist movement needed to complete a full rotation of the spiral in both directions. Patience and a controlled wrist are the only tools.",
        "fun_fact": "Professor Hoffmann (the pen name of Lewis Angelo) was the Victorian era's greatest puzzle scholar, and his 1893 book catalogued more mechanical puzzles than any previous work. The dexterity puzzle category was his special interest — he owned over 200 examples.",
        "image_prompt": "A Victorian gentleman carefully tilting a small cylindrical wooden puzzle box, concentration on his face, a marble visible through a slot making its way up an internal spiral, other mechanical puzzles visible on the table nearby, 1893 illustration"
    },
    {
        "id": "planet-puzzle",
        "slug": "planet-puzzle",
        "title": "The Planet Puzzle",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "dexterity-puzzle",
        "tags": ["dexterity", "marbles", "orbits", "solar-system", "patience", "Victorian", "mechanical"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["tray with planetary orbit tracks", "marbles of different sizes"],
        "family_friendly": True,
        "original_description": "A tray features grooved tracks representing planetary orbits. The puzzle requires maneuvering marbles — representing planets — into their correct orbital positions without them rolling out of their grooves. As with the real solar system, some 'planets' must be navigated past others.",
        "modern_description": "The tray has multiple circular grooves of different radii representing planetary orbits. Place the correct marble in each orbital groove and maneuver them to their correct angular positions simultaneously. The difficulty is that navigating one marble disturbs others, requiring a careful sequence of adjustments. The astronomical theme makes the puzzle both educational and beautiful.",
        "fun_fact": "The Planet Puzzle was designed at a time when astronomy was a popular parlor science topic — the 1880s and 1890s saw an explosion of interest in the solar system following Giovanni Schiaparelli's 1877 report of Martian 'canals.'",
        "image_prompt": "A circular tray showing planetary orbits with small marbles representing planets, one being carefully guided into position by a patient Victorian hand, diagrams of the solar system visible in the background, a study filled with scientific books, 1893"
    },
    {
        "id": "coin-and-card-puzzle",
        "slug": "coin-and-card-puzzle",
        "title": "The Coin and Card Puzzle",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "dexterity-puzzle",
        "tags": ["coin", "card", "balance", "fillip", "dexterity", "trick", "physics"],
        "difficulty": "intermediate",
        "players": "1+",
        "equipment": ["playing card", "coin"],
        "family_friendly": True,
        "original_description": "Balance a playing card on the tip of one finger. Place a coin on top of the card. The puzzle: remove the card without disturbing the coin, so the coin lands on your fingertip. The solution is to fillip (flick) the card sharply from one side — the coin's inertia keeps it in place as the card flies away.",
        "modern_description": "Extend your index finger and balance a playing card horizontally on its tip. Place a coin in the center of the card, directly above your fingertip. Now remove the card without touching the coin or moving your finger. Solution: with your free hand's middle finger, flick the edge of the card sharply — it flies away instantly while the coin, by inertia, remains behind and lands on your finger.",
        "fun_fact": "This puzzle demonstrates Newton's First Law of Motion (inertia) in an elegant and immediately verifiable way. Victorian physics lecturers used it as an introductory demonstration because the result is so counterintuitive until the principle is understood.",
        "image_prompt": "A Victorian hand balancing a playing card on one fingertip with a coin on top, another hand poised to flick the card away, the surprise of the coin remaining suspended for a fraction of a second, a parlor table setting, 1893 illustration"
    },
    {
        "id": "egg-and-card-puzzle",
        "slug": "egg-and-card-puzzle",
        "title": "The Egg and Card Puzzle",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "dexterity-puzzle",
        "tags": ["egg", "card", "ring", "water-glass", "inertia", "physics", "trick"],
        "difficulty": "intermediate",
        "players": "1+",
        "equipment": ["wine glass half-filled with water", "playing card", "cardboard ring", "raw egg"],
        "family_friendly": True,
        "original_description": "Balance a playing card on a wine glass half-full of water. Place a cardboard ring on the card, directly over the glass rim. Balance a raw egg in the ring. Then remove the card with a single sharp flick — the egg drops perfectly into the glass of water, unbroken.",
        "modern_description": "Set up the stack: wine glass half-full of water, card laid flat on top, cardboard ring on the card above the glass opening, raw egg balanced in the ring. When the card is flicked away horizontally, inertia prevents the ring and egg from moving horizontally. They drop straight down — the ring falls away and the egg plops into the water. Spectacular when it works; messy when it doesn't.",
        "fun_fact": "This three-object inertia demonstration was a standard Victorian table magic trick. President John Tyler reportedly performed it for guests at the White House in the 1840s — though whether successfully is not recorded.",
        "image_prompt": "A Victorian party table setup showing a wine glass with water, a playing card on top, a ring, and an egg balanced in precarious tower, a hand about to flick the card away, the assembled guests leaning forward in anticipation, 1893 illustration"
    },
    {
        "id": "barrel-and-ball-puzzle",
        "slug": "barrel-and-ball-puzzle",
        "title": "The Barrel and Ball",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "mechanical-puzzle",
        "tags": ["barrel", "marble", "screwing", "mechanical", "secret", "wooden", "Victorian"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["boxwood barrel with enclosed marble"],
        "family_friendly": True,
        "original_description": "A boxwood barrel contains a marble that is larger than the hole in the top. The puzzle: remove the marble without breaking the barrel. Solution: the base plug screws out — by gripping the pestle-like ball and the plug together and twisting, the whole base unscrews to release the marble.",
        "modern_description": "The barrel appears to be solid wood except for a small hole in the top, through which a marble is somehow trapped. The marble is visibly larger than the hole. The solution is not in the hole at all — the entire bottom of the barrel is a threaded plug. By understanding that the barrel must open from the bottom, and using the marble itself as a grip to unscrew the plug, the puzzle yields to lateral thinking.",
        "fun_fact": "The Barrel and Ball is one of the oldest forms of puzzle box — similar designs have been found in Japanese puzzle traditions going back to the 17th century, suggesting independent invention of the threaded-plug solution in multiple cultures.",
        "image_prompt": "A Victorian hand holding a small wooden barrel puzzle with a marble visible through the top hole, a look of puzzlement, the barrel sitting on a puzzle book, other wooden mechanical puzzles nearby, 1893 illustration"
    },
    {
        "id": "dice-box-puzzle",
        "slug": "dice-box-puzzle",
        "title": "The Dice Box",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "mechanical-puzzle",
        "tags": ["dice", "box", "friction", "secret", "wooden", "mechanical", "trick"],
        "difficulty": "beginner",
        "players": "1",
        "equipment": ["barrel-shaped wooden box with three dice inside"],
        "family_friendly": True,
        "original_description": "A barrel-shaped wooden box contains three dice rattling inside. The box appears to have no opening — yet the dice must have gotten in somehow. Solution: the base is a friction-fit plug that pops free when the box is tapped sharply on a table, base downward.",
        "modern_description": "The Dice Box appears solid, with three dice audibly rattling inside but no visible seam or opening. The challenge is to figure out how to open it. The solution: tap the box firmly, base-down, on a table. The impact releases the friction-fit base plug, which pops free to reveal the dice. Understanding friction-fit joinery is the key insight.",
        "fun_fact": "The friction-fit plug joint was used by ancient Greek woodworkers and appears in puzzle boxes from Egypt dating to 1500 BC. Victorian puzzlers rediscovered it as an elegant hidden-opening mechanism.",
        "image_prompt": "A small barrel-shaped wooden box on a table, the sound of dice implied by the surprised expression of the person holding it, another person tapping the base down on the table to release the plug, puzzle books and dice scattered around, 1893"
    },
    {
        "id": "cage-and-ball-puzzle",
        "slug": "cage-and-ball-puzzle",
        "title": "The Cage and Ball",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "mechanical-puzzle",
        "tags": ["cage", "ball", "pillar", "rotating", "mechanical", "wooden", "Victorian"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["wooden cage with enclosed marble or ball"],
        "family_friendly": True,
        "original_description": "A ball is enclosed within a decorative wooden cage. The bars of the cage are too close together for the ball to pass through — yet the ball is clearly inside. Solution: one of the cage pillars rotates and withdraws, creating a gap large enough for the ball to be removed.",
        "modern_description": "Examine the wooden cage carefully. The ball inside seems impossibly enclosed. Look for any pillar or bar that seems slightly different from the others — usually one can be rotated and pulled outward. Twist it to unlock its hidden thread or groove, then slide it free. The ball can then be removed through the gap. Reinsert the pillar to reseal the cage.",
        "fun_fact": "The Cage and Ball is a classic example of the 'captive ball' puzzle genre, which was so popular in Victorian England that puzzle-turners specialized in producing them. Some elaborate examples had balls carved inside balls inside balls — an impossible feat that required carving through the outer layers.",
        "image_prompt": "An ornately turned wooden cage with a ball visible through the bars, one person twisting one of the pillars in discovery, another watching expectantly, Victorian puzzle workshop or parlor table setting, 1893 illustration"
    },
    {
        "id": "matrimonial-chair-puzzle",
        "slug": "matrimonial-chair-puzzle",
        "title": "The Matrimonial Chair",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "dexterity-puzzle",
        "tags": ["dexterity", "marble", "chair", "tilting", "mechanical", "Victorian", "fillip"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["puzzle box featuring a chair with screen", "marble"],
        "family_friendly": True,
        "original_description": "A box contains a miniature chair with a screen or barrier and marbles representing characters. The puzzle is to seat exactly one marble in the chair without touching it directly. Solution: isolate the marble, tilt the box slowly, then fillip (flick) the bottom sharply to bounce the marble over the screen and into the chair.",
        "modern_description": "The puzzle box interior shows a small chair blocked by a barrier. Several marbles are present. The goal is to get exactly one marble to land on the chair seat without touching the marble directly. Tilt the box to isolate one marble near the barrier, then sharply tap the bottom of the box — the momentum bounce sends the marble jumping over the barrier and landing in the chair.",
        "fun_fact": "The Matrimonial Chair's name is a Victorian joke — finding a spouse (getting to the chair) requires both patience and the occasional unconventional approach (the fillip). The name gave puzzlers an immediate memory hook for the unusual solution method.",
        "image_prompt": "A Victorian puzzle box with its interior visible, showing a tiny chair with a screen in front, a marble sitting behind the screen while a person's hand is about to tap the box bottom, other puzzle boxes on a Victorian study table, 1893"
    },
    {
        "id": "bouci-boula",
        "slug": "bouci-boula",
        "title": "Bouci-Boula",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "dexterity-puzzle",
        "tags": ["dexterity", "pellets", "color-sorting", "bulb", "patience", "Victorian", "glass"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["double glass bulb containing red and white pellets"],
        "family_friendly": True,
        "original_description": "A double glass bulb contains both red and white pellets mixed together. The puzzle is to separate them by color — all red in one bulb, all white in the other — without opening the glass. The solution requires carefully tilting all pellets to one side, shaking to group by color through size or density differences, then transferring small groups across the narrow neck.",
        "modern_description": "The glass object has two connected bulbs with small pellets of two colors mixed between them. Tilt the object to consolidate all pellets in one bulb. Shake gently — slight differences in pellet size or weight cause them to partially sort. Carefully tilt to transfer the lighter/smaller pellets across the narrow connecting neck first. Patience and careful incremental transfers eventually achieve full color separation.",
        "fun_fact": "Bouci-Boula was likely a French puzzle import — the name has no clear English meaning but appears in French toy catalogs of the 1880s. Its elegant glass construction made it a desirable and attractive curiosity as well as a genuine puzzle.",
        "image_prompt": "An elegant double glass bulb containing mixed red and white pellets, partially sorted with more red on one side and more white on the other, being tilted carefully by Victorian hands, a curiosity cabinet of Victorian glass objects in background, 1893"
    },
    {
        "id": "switchback-puzzle",
        "slug": "switchback-puzzle",
        "title": "The Switchback",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "dexterity-puzzle",
        "tags": ["dexterity", "shot", "tube", "depressions", "gravity", "Victorian", "balance"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["bent tube with three depressions", "three ball-bearings or shot"],
        "family_friendly": True,
        "original_description": "A bent tube has three depressions along its length, and three shots (ball-bearings) must be positioned exactly one in each depression simultaneously. The difficulty: moving the tube to position one shot disturbs the others. Solution: invert the tube, position shot in the two larger depressions, then gradually turn the tube right-way up while guiding the third.",
        "modern_description": "The tube curves in switchback fashion with three small hollow depressions at specific points. Getting all three ball-bearings into their depressions simultaneously requires a counterintuitive approach. Invert the tube to let gravity work differently, seat the easier depressions first, then slowly rotate the tube back to upright while maintaining the others. Three simultaneous targets make this fiendishly difficult.",
        "fun_fact": "The switchback design takes its name from the zigzag mountain railways popular in Victorian Switzerland — the tube's multiple bends and the counter-directional solving method deliberately mirror the railways' back-and-forth climbing technique.",
        "image_prompt": "A bent metal tube held by a Victorian hand, three ball-bearings visible, two seated in depressions and one still rolling freely, a look of intense concentration, a puzzle-filled Victorian study, 1893 illustration"
    },
    {
        "id": "the-maze-hoffmann",
        "slug": "the-maze-hoffmann",
        "title": "The Maze Puzzle",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "dexterity-puzzle",
        "tags": ["maze", "pellets", "center", "mechanical", "dexterity", "Victorian", "labyrinth"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["enclosed box with maze pattern", "5 pellets"],
        "family_friendly": True,
        "original_description": "An enclosed box contains a maze pattern on its floor with a series of walls and passages. Five pellets must all be maneuvered into the central compartment by tilting and turning the box, navigating the pellets through the maze passages without the ability to see them directly.",
        "modern_description": "Tilt and rotate the enclosed maze box to roll the five pellets through the internal passages. Unlike visible mazes, the walls and paths are inside a closed box — you must learn the maze layout through the feedback of the pellets' movement. The challenge is routing five pellets simultaneously to the center while the maze layout remains hidden. A 3D spatial reasoning challenge.",
        "fun_fact": "Enclosed maze puzzles requiring the manipulation of a hidden interior were a direct outgrowth of Victorian confidence in mechanical precision engineering — only industrial-era craftsmanship could produce the consistent internal tolerances needed for these puzzles to work reliably.",
        "image_prompt": "A flat rectangular box with opaque sides, being tilted by a Victorian hand, the sound of rolling pellets implied, a hint of a maze pattern barely visible through a smoked glass window on the top, Victorian study setting, 1893"
    },
    {
        "id": "captive-sixpence",
        "slug": "captive-sixpence",
        "title": "The Captive Sixpence",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "mechanical-puzzle",
        "tags": ["coin", "box", "mechanical", "ball", "secret", "clever", "Victorian"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["special brass box with depressible top and internal ball"],
        "family_friendly": True,
        "original_description": "A box contains a sixpence trapped under a top that can be depressed but springs back. The coin cannot be shaken out. Solution: invert the box — a hidden ball shifts to allow the top to be depressed far enough to release the coin.",
        "modern_description": "The box has a coin (the captive sixpence) under a spring-loaded depressible top. Pressing the top releases it back — not far enough to let the coin out. The secret: invert the box completely. An internal ball bearing rolls to a new position, allowing the mechanism to depress further when the top (now the bottom) is pressed. The coin then drops free.",
        "fun_fact": "This puzzle exemplifies the principle that gravity-dependent mechanisms create puzzles that solve differently when inverted — a principle used in countless Victorian puzzle boxes and which continues to inspire puzzle designers today.",
        "image_prompt": "A Victorian brass puzzle box, one hand holding it inverted while another presses the mechanism, a sixpence about to drop free into an open palm below, other coin puzzles and Victorian bric-a-brac on the table, 1893"
    },
    {
        "id": "gordian-knot-puzzle",
        "slug": "gordian-knot-puzzle",
        "title": "The Gordian Knot (Wire Puzzle)",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "wire-puzzle",
        "tags": ["wire", "disentanglement", "gordian", "loop", "rings", "mechanical", "Victorian"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["wire puzzle in Gordian Knot configuration"],
        "family_friendly": True,
        "original_description": "A complex wire configuration forms a seemingly insoluble tangle. The puzzle is to separate the interlocking wire elements without cutting or bending them. Unlike the mythological Gordian Knot, this one has an elegant solution — but it requires understanding the topology of the wire loops.",
        "modern_description": "Examine the wire structure carefully before attempting any move. Wire disentanglement puzzles have a unique correct path — the trick is moving loops through other loops in the precise sequence. Rushing will create new tangles. The key approach: trace the wire's continuous path, identify which loops can move through which gaps, and work methodically from the most mobile end inward.",
        "fun_fact": "Wire puzzle disentanglement became one of the most popular puzzle categories in the Victorian era, with thousands of designs sold. They were called 'patience puzzles' because rushing invariably made them worse — a useful life lesson packaged as entertainment.",
        "image_prompt": "A complex wire puzzle in an intricate configuration lying on a Victorian parlor table, one person's careful hands beginning to work through the disentanglement, looks of concentration, other wire puzzles hanging from a rack in the background, 1893"
    },
    {
        "id": "chinese-rings-puzzle",
        "slug": "chinese-rings-puzzle",
        "title": "The Chinese Rings",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "mechanical-puzzle",
        "tags": ["rings", "bar", "chinese", "disentanglement", "binary", "mechanical", "classic"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["Chinese rings apparatus: 7-9 rings on a bar with looped handle"],
        "family_friendly": True,
        "original_description": "A series of rings are looped onto a bar with a handle. Each ring passes through the next, and all must be removed from the bar following a precise sequence. To remove ring n, ring (n-1) must be on the bar and all preceding rings must be off. The minimum number of moves for nine rings is 341.",
        "modern_description": "The Chinese Rings apparatus has multiple rings, each linked through the next, all threaded on a bar. To remove a ring, the ring directly behind it must currently be on the bar, and all rings in front of it must be off. Remove rings one at a time following this constraint. The puzzle is mathematically equivalent to binary counting — the optimal solution for 9 rings requires exactly 341 moves.",
        "fun_fact": "The Chinese Rings puzzle appears in European mathematical literature as early as 1550, when Girolamo Cardano described it. It is mathematically isomorphic to the binary number system — each ring position corresponds to a binary digit — a connection not formally proved until the 20th century.",
        "image_prompt": "A traditional Chinese Rings puzzle with 7 metal rings on a decorative bar with looped handle, being carefully worked by a Victorian hand, the mathematical pattern of removal implied, an orientalist study with Chinese decorative objects, 1893"
    },
    {
        "id": "magic-star-puzzle",
        "slug": "magic-star-puzzle",
        "title": "The Magic Star",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "counter-puzzle",
        "tags": ["star", "counters", "magic-sum", "arrangement", "mathematical", "numbers", "Victorian"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["star pattern diagram", "12 numbered counters"],
        "family_friendly": True,
        "original_description": "Arrange numbered counters on a six-pointed star so that every straight row of four numbers adds up to the same total. The star has six points and six sides, each containing four positions. A satisfying mathematical arrangement puzzle that extends the magic square concept.",
        "modern_description": "Draw a six-pointed Star of David pattern. Each point of the star and each intersection of lines is a position — 12 positions in all. Number counters from 1 to 12 and place them on the positions so that every straight line of four numbers sums to 24 (or the same constant). Multiple solutions exist but finding any one requires systematic trial and arrangement.",
        "fun_fact": "Magic star puzzles were considered an advanced form of the classic magic square. Hoffmann devoted several pages to them in his book, noting that unlike magic squares, magic stars have been surprisingly little studied by professional mathematicians.",
        "image_prompt": "A six-pointed star diagram on paper with numbered counters placed at its vertices and intersections, a pencil noting various number arrangements tried, an open puzzle book with star diagrams, Victorian scholar's desk, 1893"
    },
    {
        "id": "fifteen-puzzle-hoffmann",
        "slug": "fifteen-puzzle-hoffmann",
        "title": "The Fifteen Puzzle",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "sliding-puzzle",
        "tags": ["fifteen-puzzle", "sliding", "tiles", "sequence", "mathematical", "Victorian-craze", "classic"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["15-tile sliding puzzle in 4x4 frame"],
        "family_friendly": True,
        "original_description": "Fifteen numbered tiles fill a 4×4 frame with one empty space. By sliding tiles into the empty space, rearrange them from any starting position into sequential order 1-15. The puzzle was an American craze in 1880 and caused productivity losses in offices across the world.",
        "modern_description": "Start with tiles scrambled in the 4×4 frame. The single empty space allows adjacent tiles to slide. Develop a method: first position tiles 1-3 in the top row, then 4-6, then complete the remaining rows without disturbing finished rows. The 15 Puzzle has exactly half its starting positions solvable — an unsolvable starting position cannot be fixed by any sequence of legal moves.",
        "fun_fact": "Sam Loyd claimed to have invented the 15 Puzzle in 1878, offering $1,000 for a solution to the 'impossible' swap of tiles 14 and 15. In fact the puzzle was invented by Noyes Chapman in 1874 — and the 14-15 swap is genuinely mathematically impossible.",
        "image_prompt": "A 4x4 sliding tile puzzle with numbered tiles 1-15 and one empty space, some tiles out of order, a Victorian person's hand about to slide a tile, concentration written on their face, other Victorian puzzle items on the desk, 1893"
    },
    {
        "id": "pigs-in-clover-puzzle",
        "slug": "pigs-in-clover-puzzle",
        "title": "Pigs in Clover",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "dexterity-puzzle",
        "tags": ["pigs", "marbles", "clover", "circular", "dexterity", "Victorian-craze", "mechanical"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["circular enclosed box with spiral partitions", "5 small marbles (the pigs)"],
        "family_friendly": True,
        "original_description": "A circular box has a series of concentric partitions with gaps between them, forming a spiral path from the outer ring to a small central pen. Five small balls (the 'pigs') must all be guided through the spiral gates into the center 'clover' pen by tilting the box.",
        "modern_description": "Tilt the circular box carefully to roll the five marbles ('pigs') toward the center through the successive ring-gates. Each gate must be aligned with the marble's path at exactly the right moment. The challenge is getting all five through simultaneously — a marble that clears one ring can roll back through the gap if the box tilts the wrong way. Remarkable patience required.",
        "fun_fact": "Pigs in Clover was an American invention of 1889 by Charles M. Crandall and became such a sensation that it was reportedly played in the U.S. Senate, causing one newspaper to wonder whether the government could function with all senators so distracted.",
        "image_prompt": "A circular dexterity puzzle box with concentric ring walls and five small marble 'pigs' being guided toward the center pen, the box tilted in careful hands, a Victorian parlor table, other novelty toys nearby, 1893 illustration"
    },
    {
        "id": "puzzle-of-dissected-cross",
        "slug": "puzzle-of-dissected-cross",
        "title": "The Dissected Cross",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "dissection-puzzle",
        "tags": ["dissection", "cross", "pieces", "rearrangement", "geometric", "cutting", "Victorian"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["5 geometric pieces that form a cross"],
        "family_friendly": True,
        "original_description": "A Greek cross is cut into five pieces. The puzzle is to rearrange these five pieces to form a perfect square. The solution requires a specific rotation and arrangement that is far from obvious — the cross-shaped whole must become a rectangular whole.",
        "modern_description": "Cut out the five provided pieces from the Greek cross shape. The challenge: rearrange them to form a perfect square without any overlapping or gaps. Some pieces may need to be rotated or flipped. The elegant mathematical fact underlying this puzzle is that a cross and a square of equal area can always be dissected into each other using just five pieces — discovered by Henry Dudeney.",
        "fun_fact": "Henry Dudeney published his elegant 4-piece cross-to-square dissection in 1902, improving on earlier 5-piece solutions. The pieces can even be hinged together to fold from one shape to the other — a 'hinged dissection' that Dudeney demonstrated in silver at the Royal Institution.",
        "image_prompt": "Five geometric puzzle pieces arranged on a table, one configuration forming a Greek cross and nearby another configuration forming a perfect square, a Victorian puzzle book open showing both shapes, hands arranging pieces thoughtfully, 1893"
    },
    {
        "id": "arithmetical-puzzle-age",
        "slug": "arithmetical-puzzle-age",
        "title": "The Age Puzzle",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "arithmetical-puzzle",
        "tags": ["arithmetic", "age", "calculation", "guessing", "number-trick", "mental-math", "Victorian"],
        "difficulty": "intermediate",
        "players": "2",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Ask someone to think of their age, double it, add a specific number, divide by two, then subtract their original age. The result is always the same predetermined number — and the performer appears to have divined the person's age, when actually only the fixed arithmetic result was predicted.",
        "modern_description": "Instruct a volunteer: 'Think of your age. Double it. Add 10. Halve the result. Now subtract your original age.' Whatever their age, the answer is always 5. The performer 'dramatically divines' the number 5 as if reading the person's mind. The algebraic explanation: if age = a, then ((2a + 10) / 2) - a = (a + 5) - a = 5. The number added (10 in this case) determines the result (always half of it).",
        "fun_fact": "Number-forcing tricks like the Age Puzzle have been performed since at least the Renaissance, when they appeared in Italian books on mathematical recreations. The Victorian era saw dozens of variations published, all based on the same algebraic identity.",
        "image_prompt": "A Victorian parlor scene, one person standing with a dramatic expression announcing 'The answer is five!' while another person sits with a surprised look checking their calculation on paper, amused onlookers, 1893 illustration"
    },
    {
        "id": "problem-horses-puzzle",
        "slug": "problem-horses-puzzle",
        "title": "The Three Horses Puzzle",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "arithmetical-puzzle",
        "tags": ["arithmetic", "horses", "price", "profit", "money", "percentage", "Victorian"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["paper", "pencil"],
        "family_friendly": True,
        "original_description": "A dealer buys three horses for £90 total. He sells the first for £30 and gains 10%, the second for £30 and neither gains nor loses, and the third for £30 and loses 10%. How much does he gain or lose overall? The apparent paradox resolves simply when each horse's original price is calculated.",
        "modern_description": "Set up the equations: If the dealer gains 10% on horse 1, he bought it for £30/1.10 = £27.27. Horse 2 cost £30. Horse 3 (10% loss) cost £30/0.90 = £33.33. Total cost: £90.61. Total received: £90. Net loss: £0.61. The dealer actually loses money, contrary to the intuition that gaining and losing the same percentage on the same price cancels out — it doesn't, because the bases are different.",
        "fun_fact": "This type of percentage paradox was a staple of Victorian puzzle books because it exposed the common misconception that gains and losses of equal percentage cancel out. The same mathematical trap catches investors today who believe 'averaging down' always restores their position.",
        "image_prompt": "A Victorian horse dealer at a market, three horses visible, an accounting ledger open with calculations, the dealer looking puzzled at his figures, a busy Victorian horse fair in the background, 1893 illustration"
    },
    {
        "id": "row-of-soldiers-puzzle",
        "slug": "row-of-soldiers-puzzle",
        "title": "The Row of Soldiers",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "counter-puzzle",
        "tags": ["counters", "rearrangement", "alternating", "soldiers", "sequence", "movement", "Victorian"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["6 counters in two colors"],
        "family_friendly": True,
        "original_description": "Six counters — three red and three black — are arranged alternating: red-black-red-black-red-black. By moving two adjacent counters at a time (without separating them), rearrange them in three moves so that all reds are together and all blacks are together.",
        "modern_description": "Place counters in alternating red-black order: R B R B R B. Each move slides two adjacent counters together (as a pair) to any new position in the row. In exactly three moves, achieve the arrangement R R R B B B or B B B R R R. The solution requires thinking about which pairs to move and where to leave gaps for the final arrangement.",
        "fun_fact": "Rearrangement puzzles involving alternating colored counters were a specialty of the Victorian puzzle tradition. Hoffmann catalogued dozens of variants, noting that the constraint of moving pairs (rather than single pieces) dramatically increases difficulty.",
        "image_prompt": "Six colored counters alternating red and black on a table, a hand preparing to slide two adjacent ones as a pair, a partially rearranged solution state visible, a Victorian puzzle book open nearby showing the starting position, 1893"
    },
    {
        "id": "magic-hexagon-puzzle",
        "slug": "magic-hexagon-puzzle",
        "title": "The Magic Hexagon",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "counter-puzzle",
        "tags": ["hexagon", "arrangement", "sum", "mathematical", "counters", "six", "Victorian"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["hexagonal grid diagram", "19 numbered counters"],
        "family_friendly": True,
        "original_description": "Place numbers in a hexagonal grid arrangement so that every straight row — whether going in any of three directions through the hexagon — sums to the same total. This extends the magic square concept into a honeycomb geometry.",
        "modern_description": "Draw a hexagonal grid with 19 positions (one center, 6 in the inner ring, 12 in the outer ring). Place numbers 1 through 19 so that every straight row sums to 38. There are essentially only seven distinct solutions (counting reflections and rotations as one). This is far rarer than the magic square — mathematicians proved there is no magic hexagon except this one for all sizes.",
        "fun_fact": "The 3-ring magic hexagon is the ONLY magic hexagon that exists for any ring count — meaning no 4-ring, 5-ring, or larger version is possible. This uniqueness was not proven until 1964, making it a genuine mathematical discovery hiding inside a Victorian puzzle.",
        "image_prompt": "A honeycomb hexagonal grid filled with numbers, lines drawn showing each row summing to the same total, a Victorian mathematician's desk with geometry books and compasses, an elegant mathematical puzzle diagram, 1893"
    },
    {
        "id": "knight-tour-puzzle",
        "slug": "knight-tour-puzzle",
        "title": "The Knight's Tour",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "mechanical-puzzle",
        "tags": ["chess", "knight", "tour", "board", "mathematical", "graph-theory", "sequence"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["chessboard or grid paper", "chess knight or marker"],
        "family_friendly": True,
        "original_description": "A chess knight must tour every square of an 8×8 board, landing on each exactly once, making only legal knight moves (one square in one direction, two in the other). The challenge is to find a complete tour — or better, a re-entrant tour where the knight can return to its starting square in one final move.",
        "modern_description": "Place a chess knight on any square of the board. Move it using only legal knight moves (L-shaped: two squares one way, one square perpendicular). Visit every square exactly once. A non-re-entrant tour ends at a square with no more unvisited squares reachable. A re-entrant (closed) tour ends a knight's move from the starting square. Use Warnsdorff's rule as a solving heuristic: always move to the square with the fewest onward moves.",
        "fun_fact": "The Knight's Tour problem was studied by Euler in 1759 and by Al-Adli in 840 AD. The total number of closed knight's tours on an 8×8 board is 26,534,728,821,064 — a number not computed until 1995 using modern computers.",
        "image_prompt": "A chessboard with numbered squares showing a completed knight's tour path, the knight piece positioned on one square, lines connecting each step in order, a Victorian chess study with books on chess problems and mathematical recreations, 1893"
    },
    {
        "id": "cryptarithmetic-puzzle",
        "slug": "cryptarithmetic-puzzle",
        "title": "The Cryptarithmetic Puzzle (Letters for Digits)",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "arithmetical-puzzle",
        "tags": ["cryptarithmetic", "letters", "digits", "arithmetic", "substitution", "mathematical", "Victorian"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["paper", "pencil"],
        "family_friendly": True,
        "original_description": "An arithmetical sum is presented with each digit replaced by a letter, different letters representing different digits. The solver must determine what digit each letter stands for to make the sum correct. A classic example: SEND + MORE = MONEY, where each letter is a unique digit.",
        "modern_description": "In a cryptarithmetic puzzle, each letter consistently represents one specific digit (0-9), with different letters representing different digits. Look for constraints: the leftmost digit of a multi-digit number can't be 0; carries between columns limit possible values. Start with the column that gives the most information and work by elimination. SEND + MORE = MONEY has a unique solution.",
        "fun_fact": "SEND + MORE = MONEY was published by Henry Dudeney in 1924 and became the most famous cryptarithmetic puzzle ever created. The technique dates to Victorian puzzle books, though Hoffmann used simpler examples. The answer: S=9, E=5, N=6, D=7, M=1, O=0, R=8, Y=2.",
        "image_prompt": "A Victorian mathematics puzzle page showing a letter-substitution addition sum, one person working through possible digit assignments with a pencil, arithmetic workings filling the margins, a candlelit study, 1893 illustration"
    },
    {
        "id": "river-crossing-puzzle",
        "slug": "river-crossing-puzzle",
        "title": "The River Crossing (Fox, Goose, and Bag of Corn)",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "logical-puzzle",
        "tags": ["river-crossing", "fox", "goose", "corn", "logic", "classic", "constraints"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": [],
        "family_friendly": True,
        "original_description": "A farmer must cross a river with a fox, a goose, and a bag of corn. The boat holds only the farmer and one item. Left alone, the fox will eat the goose; the goose will eat the corn. How does he cross without any loss?",
        "modern_description": "The boat holds you and one passenger/item. Constraints: Fox eats Goose if unsupervised; Goose eats Corn if unsupervised. Solution: Take Goose across first. Return alone. Take Fox across. Return with Goose. Take Corn across. Return alone. Take Goose across. This requires 7 trips. The key insight is that you can bring something back — which most solvers initially miss.",
        "fun_fact": "This puzzle appears in Alcuin of York's 'Propositiones ad Acuendos Juvenes' (Problems to Sharpen the Young) written around 800 AD — making it at least 1,200 years old. It is one of the oldest documented recreational mathematical puzzles in Western literature.",
        "image_prompt": "A Victorian illustration of a farmer at a riverbank with a fox, a goose, and a sack of corn, a small rowboat beside him, looking puzzled about how to transport them all safely, a river and far bank visible, 1893 pen-and-ink illustration"
    },
    {
        "id": "tower-of-hanoi-hoffmann",
        "slug": "tower-of-hanoi-hoffmann",
        "title": "Tower of Hanoi",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "mechanical-puzzle",
        "tags": ["hanoi", "discs", "pegs", "recursive", "mathematical", "mechanical", "classic"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["Tower of Hanoi apparatus: 3 pegs and 8 discs of decreasing size"],
        "family_friendly": True,
        "original_description": "Eight discs of decreasing size are stacked on one peg, largest at the bottom. Moving only one disc at a time, and never placing a larger disc on a smaller one, transfer the entire stack to another peg. The minimum number of moves for eight discs is 255.",
        "modern_description": "Stack all discs on the left peg in order (largest at bottom). Transfer all to the right peg using the middle peg as a spare. Rules: one disc per move, never place larger on smaller. The minimum number of moves for n discs is 2ⁿ - 1. For 3 discs: 7 moves. For 8 discs: 255 moves. The recursive strategy: move the top (n-1) discs to spare peg, move the largest to target, move (n-1) back on top.",
        "fun_fact": "Édouard Lucas invented Tower of Hanoi in 1883 and marketed it with a legend: Brahmin monks in Benares are transferring 64 golden discs. When they finish, the world will end. At one move per second, completing 64 discs takes about 585 billion years — longer than the current age of the universe.",
        "image_prompt": "A Victorian Tower of Hanoi puzzle with three pegs and eight graduated wooden discs, mid-transfer with discs distributed across pegs, a person carefully planning their next move, a puzzle shop or Victorian study setting, 1893"
    },
    {
        "id": "four-colours-dexterity",
        "slug": "four-colours-dexterity",
        "title": "The Four Colours Puzzle",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "dexterity-puzzle",
        "tags": ["color-matching", "pellets", "stalls", "dexterity", "mechanical", "Victorian", "matching"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["puzzle box with four colored stalls", "four colored pellets"],
        "family_friendly": True,
        "original_description": "Four differently colored stalls (red, white, blue, and mixed) are inside a box. Four colored pellets must be maneuvered by tilting the box until each pellet rests in the stall matching its color. A pure dexterity challenge of color-matching through delicate box manipulation.",
        "modern_description": "Tilt the enclosed box so the colored pellets roll freely inside. Guide each pellet to its matching-colored stall through controlled tilting motions. The difficulty: moving one pellet invariably disturbs the others, so the final approach requires isolating each pellet in sequence. Develop a system: position three correctly, then maneuver the fourth without losing the others.",
        "fun_fact": "Color-matching dexterity puzzles like The Four Colours exploited the Victorian love of classification and ordering — an era that saw the construction of elaborate taxonomic systems for biology, geology, and chemistry also produced puzzles based on sorting and matching.",
        "image_prompt": "A flat puzzle box with four colored sections visible through a glass top, four colored marbles partially sorted, hands carefully tilting the box with great precision, Victorian parlor table with other novelty puzzles, 1893"
    },
    {
        "id": "three-peg-puzzle",
        "slug": "three-peg-puzzle",
        "title": "The Three Peg Puzzle",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "counter-puzzle",
        "tags": ["pegs", "counters", "hopping", "leaping", "sequence", "logical", "movement"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["10 pegs or counters in two colors"],
        "family_friendly": True,
        "original_description": "Five black and five white pegs are placed in a row of eleven holes with one empty center hole. Black pegs on the left must reach the right side, white pegs must reach the left — by moving forward one step or jumping over one peg of the opposite color. The challenge is to do it in the minimum number of moves.",
        "modern_description": "Place 5 black pegs on the left side, one empty center hole, 5 white pegs on the right. Pegs move one space forward or jump over one adjacent peg of the opposite color. Never move backward. Both colors must reach the opposite side. The minimum solution requires 35 moves. The key insight: alternate single-steps and jumps in a specific rhythm to avoid deadlock.",
        "fun_fact": "The Leapfrog Puzzle (as it's also called) is mathematically equivalent to sorting algorithms in computer science. The optimal 35-move solution follows a pattern (1 jump, 2 jumps, 3 jumps...5 jumps...5 jumps, 4 jumps...1 jump) that Hoffmann found 'pleasing in its mathematical regularity.'",
        "image_prompt": "Eleven holes in a row on a board, five black pegs on one side and five white pegs on the other with one center space empty, mid-puzzle state with some pegs having crossed over, a Victorian puzzle board on a study table, 1893"
    },
    {
        "id": "number-guessing-trick",
        "slug": "number-guessing-trick",
        "title": "The Number Guessing Trick",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "arithmetical-puzzle",
        "tags": ["arithmetic", "mental-math", "guessing", "trick", "number", "party", "Victorian"],
        "difficulty": "beginner",
        "players": "2",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Ask someone to think of any number, triple it, halve the result (if odd, drop the fraction), triple that, then tell you the result. The performer instantly determines the original number. If the final result is even, the original was even; divide the result by 9 to get the original number.",
        "modern_description": "Ask: 'Think of a number. Multiply by 3. If odd, drop the half-point. Multiply by 3 again. Tell me the result.' Divide what they tell you by 9 (for even originals) or by 9 rounded (for odd). This is a number-forcing trick that always recovers the original. The mathematical reason: 3 × (3n)/2 × 2 = 9n/2, so dividing by 9 recovers n. Practice the division to do it instantly.",
        "fun_fact": "Mental arithmetic tricks presented as mind-reading acts were extremely popular Victorian entertainment. Performers like 'Lightning Calculators' performed at music halls and were celebrated as possessors of almost supernatural powers before the mathematical basis was understood.",
        "image_prompt": "A Victorian performer with an air of mystery announcing the thought-of number to a surprised volunteer, other guests looking impressed, a parlor or drawing room setting, gaslit atmosphere suggesting an intimate evening's entertainment, 1893"
    },
    {
        "id": "wheel-of-aristotle",
        "slug": "wheel-of-aristotle",
        "title": "The Wheel of Aristotle",
        "source_book": "Puzzles Old and New",
        "source_author": "Professor Hoffmann (Angelo Lewis)",
        "source_year": 1893,
        "source_url": "https://archive.org/details/puzzlesoldnew00hoff",
        "category": "puzzle",
        "subcategory": "catch-puzzle",
        "tags": ["paradox", "aristotle", "wheels", "circumference", "rolling", "optical", "mathematical"],
        "difficulty": "advanced",
        "players": "1+",
        "equipment": ["two concentric circles drawn on a disc"],
        "family_friendly": True,
        "original_description": "A wheel with two concentric circles of different sizes rolls along a surface. The smaller inner circle appears to cover the same distance in one rotation as the larger outer circle — even though their circumferences are different. This is Aristotle's Paradox, which puzzled philosophers for 2,000 years.",
        "modern_description": "Draw two concentric circles on a disc, one large and one small. Roll the disc along a flat surface for exactly one full rotation (mark the starting and ending positions of both circles). Observe that the point on the larger circle travels its full circumference — but the point on the smaller circle appears to travel the same distance, even though its circumference is smaller. The resolution involves understanding the difference between pure rolling and rolling with slipping.",
        "fun_fact": "Aristotle's Wheel Paradox appears in the ancient Greek text 'Mechanica' and was seriously debated by mathematicians including Galileo (who proposed it might prove the existence of infinitesimals) until the development of infinitesimal calculus finally resolved it.",
        "image_prompt": "A large wooden wheel with two concentric circles marked on it, one Victorian thinker rolling it along a table and marking where each circle's point lands, a philosophical discussion implied, books on Aristotle and mathematics open nearby, 1893"
    },
]

print(f"Hoffmann entries: {len(hoffmann_entries)}")
