# Magician's Own Book entries
magician_entries = [
    {
        "id": "the-flying-dime",
        "slug": "the-flying-dime",
        "title": "The Flying Dime",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "coin-trick",
        "tags": ["coin", "handkerchief", "vanish", "appear", "sleight", "performance", "Victorian"],
        "difficulty": "advanced",
        "players": "Performer + audience",
        "equipment": ["two handkerchiefs", "three dimes (one hidden)", "hat", "needle and thread"],
        "family_friendly": True,
        "original_description": "Borrow two handkerchiefs and show two dimes (concealing a third). Place two dimes into one handkerchief in a hat; secretly sew the third dime into the second handkerchief using a needle hidden in the cuff. The spectator drops the sewn-in dime (held by stitches), it vanishes from the second handkerchief and the three dimes are found in the hat.",
        "modern_description": "This classic coin routine requires secret preparation: conceal a third dime and a needle-and-thread in your sleeve cuff. Display two dimes openly and wrap them in the first handkerchief in a borrowed hat. While handling the second handkerchief, secretly stitch the hidden dime inside its fold. Hand the second handkerchief to a spectator — when they try to drop the dime, it stays sewn in (vanish!). Reveal all three dimes mysteriously gathered in the hat.",
        "fun_fact": "The Flying Dime routine is part of a long tradition of 'coin travel' effects dating back to ancient Roman conjurers. The use of needle-and-thread as a secret tool reflects the Victorian conjurer's ingenuity in turning everyday objects into magical apparatus.",
        "image_prompt": "A Victorian stage magician in formal attire showing two coins to an audience while secretly holding a third behind his finger, a borrowed hat on the table, gaslit theatre setting, dramatic and mysterious atmosphere, 1862 illustration"
    },
    {
        "id": "the-three-cups",
        "slug": "the-three-cups",
        "title": "The Three Cups",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "cup-and-ball",
        "tags": ["cups", "balls", "classic", "vanish", "appear", "sleight", "Victorian", "stage"],
        "difficulty": "advanced",
        "players": "Performer + audience",
        "equipment": ["3 cups", "4 balls (3 visible + 1 hidden)", "table"],
        "family_friendly": True,
        "original_description": "Balls vanish from under cups, reappear under wrong cups, and finally all appear under one cup. The secret is a fourth hidden cork ball — palmed and slipped secretly while lifting and replacing cups. Each apparently impossible transport is achieved through sleight of hand.",
        "modern_description": "The Cups and Balls is the world's oldest documented magic trick. Begin by showing three cups and three balls. Balls seem to pass through solid cups, travel from cup to cup, and multiply or vanish at command. The master move: the fourth ball is always palmed; when a cup is lifted to show it empty, the hidden ball is loaded under the next cup. Practice the palm-and-load until it is completely natural.",
        "fun_fact": "The Cups and Balls trick appears in Roman records from 200 BC and is depicted on Egyptian tomb paintings from 2000 BC. Seneca mentioned conjurers performing it at the forum. It is widely considered the oldest magic trick in recorded history.",
        "image_prompt": "A Victorian street conjurer with three cups and three cork balls on a folding table, mid-trick with one ball visibly under a cup and the audience watching intently, gaslit street scene, Victorian gentleman magician, 1862"
    },
    {
        "id": "the-beads-and-strings",
        "slug": "the-beads-and-strings",
        "title": "The Beads and Strings",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "string-trick",
        "tags": ["beads", "strings", "release", "impossible", "knot", "sleight", "Victorian"],
        "difficulty": "intermediate",
        "players": "Performer + audience",
        "equipment": ["two strings", "large beads"],
        "family_friendly": True,
        "original_description": "Thread beads onto two strings twisted together and tied at their ends. Spectators pull both ends and the beads seem inextricably locked — yet the magician removes them easily. The secret: strings are secretly crossed at the center, and the center bead is passed over the juncture; pulling loops free releases all beads under cover of hand.",
        "modern_description": "Set up: Cross two strings at their midpoint before threading beads on. The beads appear to be threaded straight through but are actually on a crossed section. When spectators hold the four ends and pull, the beads seem trapped. Under the cover of your hand 'working the magic,' uncross the center crossing and the beads slip free instantly as the strings separate.",
        "fun_fact": "String-and-bead tricks formed one of the largest categories of Victorian parlor magic because they required no special equipment — any household had strings and beads. The mathematical secret (crossing strings) was considered elegant by the era's many amateur mathematicians.",
        "image_prompt": "A Victorian magician threading large wooden beads onto two strings before an audience, the strings visibly crossed in the center under the beads, one spectator pulling string ends looking puzzled, a cosy parlor setting, 1862"
    },
    {
        "id": "magic-bond",
        "slug": "magic-bond",
        "title": "The Magic Bond",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "string-trick",
        "tags": ["string", "hand", "loop", "escape", "impossible", "sleight", "Victorian"],
        "difficulty": "intermediate",
        "players": "Performer + audience",
        "equipment": ["length of string"],
        "family_friendly": True,
        "original_description": "A string is tied in a loop around the magician's hand and wrist, seemingly inescapable. With a quick movement, the loop slips off entirely despite the spectator holding both ends. The secret lies in arranging the string over the fingers in a specific looped configuration that creates hidden slack.",
        "modern_description": "Hold your hand out flat. Have a spectator tie a loop of string around it. The loop seems tight and inescapable. But you have secretly arranged the string to cross over a hidden fold of skin at your thumb joint — this creates a 'ghost' slack. With a smooth pulling motion, work this hidden slack through and the loop slips off cleanly. The spectator sees both ends throughout and never understands what happened.",
        "fun_fact": "Escape from bonds was one of the most requested feats of Victorian conjurers. Long before Houdini's famous escapes, lesser-known performers were building entire acts around rope and string escapes using clever mechanical advantages rather than brute force.",
        "image_prompt": "A Victorian magician's hand with a string loop around it, the other hand making a dramatic gesture as if casting a spell, the string beginning to slip free impossibly, an amazed spectator watching, an intimate parlor setting, 1862"
    },
    {
        "id": "ring-from-handkerchief",
        "slug": "ring-from-handkerchief",
        "title": "Ring Out of a Handkerchief",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "ring-trick",
        "tags": ["ring", "handkerchief", "vanish", "rod", "borrowed", "sleight", "Victorian"],
        "difficulty": "advanced",
        "players": "Performer + audience",
        "equipment": ["handkerchief", "borrowed ring", "fake wire ring", "rod held by spectators"],
        "family_friendly": True,
        "original_description": "A borrowed ring vanishes from a tied handkerchief and appears on a rod held by the audience. The method uses a fake ring made of sharpened wire that unbends and passes through the handkerchief fabric; the real ring is slipped onto the rod secretly during the wrapping process.",
        "modern_description": "Borrow a ring and place it in a handkerchief in full view. As you wrap the handkerchief around it, switch the ring for a wire fake under the fabric. The spectator can feel the fake ring through the cloth and ties the handkerchief. You now hold the real ring palmed. Have two spectators hold a rod between them — secretly load the ring onto the rod under your sleeve. Shake the handkerchief: the 'ring' has vanished. Reveal it on the rod.",
        "fun_fact": "The borrowed ring trick is considered an ideal effect because it uses the spectator's own property — making any accusation of a pre-prepared fake ring completely illogical. Victorian magicians called this principle 'borrowing your proof.'",
        "image_prompt": "A Victorian conjurer wrapping a borrowed ring in a handkerchief with exaggerated ceremony, two spectators holding a rod behind him, the ring about to secretly travel to the rod, gaslit Victorian drawing room performance, 1862"
    },
    {
        "id": "cut-string-restored",
        "slug": "cut-string-restored",
        "title": "The Cut String Restored",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "string-trick",
        "tags": ["string", "cut", "restore", "mouth", "knot", "sleight", "Victorian"],
        "difficulty": "intermediate",
        "players": "Performer + audience",
        "equipment": ["piece of string", "scissors"],
        "family_friendly": True,
        "original_description": "A string is cut in the middle in full view and placed in the magician's mouth. A moment later, it is removed whole and restored. The secret: a hidden crossed loop was in the string — the scissors cut only this loop, leaving the main string intact; the loop is removed by the tongue and swallowed or concealed in the cheek.",
        "modern_description": "Before showing the string, fold a section near the middle into a small crossed loop. Present the string showing its length. Fold it in half and bring the middle up — but position the loop so that the scissors cut it, not the main string. Take the 'cut ends' into your mouth. Work the loop off with your tongue, concealing it. Draw the string out whole and restored. The cut loop is tiny and easily hidden.",
        "fun_fact": "The Cut and Restored Rope (or String) is one of magic's most enduring effects. Modern magicians still perform it, and it has been used in practically every language of the world's magic traditions — Japanese, Indian, Chinese, and European versions all exist independently.",
        "image_prompt": "A Victorian magician holding a string with scissors about to cut it before an astonished audience, moments later with the restored string held up triumphantly, gaslit Victorian performance setting, theatrical and dramatic, 1862"
    },
    {
        "id": "gordian-knot-handkerchief",
        "slug": "gordian-knot-handkerchief",
        "title": "The Gordian Knot",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "handkerchief-trick",
        "tags": ["handkerchief", "knot", "behind-back", "restoration", "sleight", "Victorian"],
        "difficulty": "intermediate",
        "players": "Performer + audience",
        "equipment": ["handkerchief"],
        "family_friendly": True,
        "original_description": "A handkerchief is tied into what appears to be an impossibly tight, complex ball. The magician places it behind their back and — a moment later — reveals it completely untied. The secret: the corners are layered in a specific way that reverses the process when pulled correctly.",
        "modern_description": "Fold the handkerchief into thirds lengthwise. Tie it into an overhand knot but layer the corners in a specific mirrored sequence as you do so. The resulting ball appears hopelessly knotted. Behind your back (where spectators cannot see), you simply reverse the layering sequence — the 'knot' falls apart instantly. Bring it out smoothly spread flat.",
        "fun_fact": "The mythological Gordian Knot (cut by Alexander the Great in 333 BC) was so culturally prominent that Victorian magicians regularly borrowed its name for complicated-looking but secretly simple knot effects, adding classical gravitas to their performances.",
        "image_prompt": "A Victorian magician dramatically hiding a knotted handkerchief behind his back while facing the audience, then revealing it fully spread and smooth, theatrical gestures with a look of triumph, an evening performance setting, 1862"
    },
    {
        "id": "magic-handcuffs-trick",
        "slug": "magic-handcuffs-trick",
        "title": "The Magic Handcuffs",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "string-trick",
        "tags": ["handcuffs", "rope", "escape", "two-person", "loop", "sleight", "Victorian"],
        "difficulty": "intermediate",
        "players": "2 performers or performer + volunteer",
        "equipment": ["two lengths of string"],
        "family_friendly": True,
        "original_description": "Two persons' hands are tied together with separate string loops around each wrist, the strings linking them together. They appear inescapably bound. The solution: pass one person's wrist loop under the binding string, over their partner's hand, and pull free — no untying needed.",
        "modern_description": "Tie a string loop around each person's wrists. Thread the second person's string through the first person's wrist loop before securing. The pair is now linked like handcuffs. To escape: one person takes the center of their own string, passes it through the other's wrist loop (going between their skin and the string), then passes it over the other's entire hand. Pull it through and the two are free — while the strings remain intact.",
        "fun_fact": "The Magic Handcuffs escape became the parlor basis for Houdini's theatrical handcuff escapes decades later. Houdini always credited American parlor books like The Magician's Own Book as his earliest education in escape principles.",
        "image_prompt": "Two Victorian gentlemen linked by strings around their wrists looking hopelessly bound, one beginning to work the escape by threading a loop over the other's hand, onlookers watching with fascination, a parlor setting, 1862"
    },
    {
        "id": "four-kings-together",
        "slug": "four-kings-together",
        "title": "The Four Kings",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "card-game",
        "subcategory": "card-trick",
        "tags": ["cards", "kings", "cut", "together", "sleight", "Victorian", "magic"],
        "difficulty": "intermediate",
        "players": "Performer + audience",
        "equipment": ["standard deck of playing cards"],
        "family_friendly": True,
        "original_description": "The four kings are shown and placed separately throughout the deck. After a single cut, all four kings are found together. The secret: the other three kings have three indifferent court cards hidden between them; the fourth is placed last. After the cut, the hidden cards fill the apparent gap between the kings.",
        "modern_description": "Show four kings openly. Unknown to the audience, three other court cards are hidden face-down behind three of the kings. Place the visible kings at four separate positions in the deck, actually placing the hidden cards too. The fourth king goes on top. When the deck is cut, the cut brings the top king to join the other three (plus their hidden companions). Fan the deck to reveal the four kings together.",
        "fun_fact": "The Four Kings is one of the oldest and most widely taught card tricks in the world, appearing in magic books from the 17th century. It teaches the most fundamental principle in card magic: that appearance and reality can be completely separated through misdirection.",
        "image_prompt": "A Victorian card sharp spreading a deck face-up showing four kings together, audience members leaning forward amazed, cards fanned dramatically on a green-felt table, candlelit Victorian gentleman's club atmosphere, 1862"
    },
    {
        "id": "triple-deal-card-trick",
        "slug": "triple-deal-card-trick",
        "title": "The Triple Deal",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "card-game",
        "subcategory": "card-trick",
        "tags": ["cards", "mathematical", "dealing", "chosen-card", "self-working", "Victorian", "magic"],
        "difficulty": "beginner",
        "players": "Performer + audience",
        "equipment": ["21 playing cards"],
        "family_friendly": True,
        "original_description": "Twenty-one cards are dealt into three piles. The spectator notes which pile contains their chosen card. After three rounds of this procedure, always placing the named pile between the other two before re-dealing, the chosen card is found at position eleven — the exact middle of the packet.",
        "modern_description": "Deal 21 cards face-up into 3 piles of 7. Ask the spectator to note which pile their thought-of card is in. Collect the piles with the named pile in the middle. Repeat the deal twice more, each time placing the named pile in the middle of the three. After three rounds, the chosen card is guaranteed to be at position 11 (the middle card) of the 21-card packet.",
        "fun_fact": "The Triple Deal is a self-working mathematical trick — no sleight of hand is required. The mathematics involves base-3 positioning: placing the named pile in the middle each time effectively zero-places the chosen card in three-digit ternary arithmetic, always resulting in position 11.",
        "image_prompt": "A Victorian amateur magician dealing cards into three face-up piles on a parlor table, a spectator pointing to one pile to identify their chosen card, the performer collecting the piles with practiced confidence, 1862 illustration"
    },
    {
        "id": "card-discovered-touch-smell",
        "slug": "card-discovered-touch-smell",
        "title": "The Card Discovered by Touch",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "card-game",
        "subcategory": "card-trick",
        "tags": ["cards", "marked", "long-card", "touch", "feel", "preparation", "Victorian"],
        "difficulty": "intermediate",
        "players": "Performer + audience",
        "equipment": ["deck with one card slightly wider (long card) than others"],
        "family_friendly": True,
        "original_description": "A spectator names their card after the performer feels and 'smells' the cards one by one. The secret is a prepared card: one card is slightly wider than the others, so it can be located by touch even with eyes closed or in the dark. The performer uses this marked card to locate any selected card by controlling it near the prepared one.",
        "modern_description": "Prepare a deck by trimming one card (the 'locator') slightly longer or wider than the rest. When a card is selected and returned, control it to sit next to the locator. Fan the deck behind your back or hold it overhead and feel for the wider locator card — the chosen card will be adjacent. Dramatically 'smell' or 'feel' each card as you approach the selection for maximum theatrical effect.",
        "fun_fact": "Marked cards were not considered cheating in Victorian parlor magic — they were accepted performance tools. Professional gamblers, however, used much more subtle markings (pin pricks, ink shading) to cheat at Faro and Poker, and Victorian books on magic frequently warned readers about these criminal applications of the same principles.",
        "image_prompt": "A Victorian magician holding cards behind his back with a theatrical expression of intense concentration, sniffing one card as if detecting its identity by smell, an amused and baffled audience, intimate evening performance, 1862"
    },
    {
        "id": "knaves-and-constable",
        "slug": "knaves-and-constable",
        "title": "The Knaves and the Constable",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "card-game",
        "subcategory": "card-trick",
        "tags": ["cards", "knaves", "king", "story", "narrative", "placement", "Victorian"],
        "difficulty": "beginner",
        "players": "Performer + audience",
        "equipment": ["standard deck of playing cards"],
        "family_friendly": True,
        "original_description": "A story is told: three knaves (thieves) go to different parts of a house while a constable searches. The King (constable) eventually finds all three together. The trick: the three knaves are placed at specific positions in a single pile, and a cut brings the King to join them.",
        "modern_description": "Hold the four knaves (jacks) and the king of spades. Tell the story as you 'hide' the knaves: place them at the top, middle, and bottom of the deck while secretly stacking them with hidden indifferent cards in between. Place the king (constable) on top. One dramatic cut of the deck brings the king face-to-face with all three knaves at the same position. The story makes the trick completely self-explaining.",
        "fun_fact": "Narrative card tricks — in which a story explains the sequence of moves while disguising the method — are considered among the most elegant because the performer needs no formal explanation of what's happening. The story IS the explanation.",
        "image_prompt": "A Victorian storytelling magician holding face cards as characters in a story, arranging them in a deck while narrating, an audience of children and adults listening to the tale, a firelit parlor, 1862 illustration"
    },
    {
        "id": "pairs-repaired",
        "slug": "pairs-repaired",
        "title": "The Pairs Repaired",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "card-game",
        "subcategory": "card-trick",
        "tags": ["cards", "memory", "pairs", "rows", "mnemonic", "Latin", "Victorian"],
        "difficulty": "advanced",
        "players": "Performer + audience",
        "equipment": ["standard deck of playing cards"],
        "family_friendly": True,
        "original_description": "Sixteen cards are laid in four rows of four. Spectators memorize pairs; the performer leaves the room. On return, the performer names which cards are paired. The secret is the mnemonic 'MUTUS DEDIT NOMEN COCIS' — each letter codes the row of paired cards according to a mathematical table.",
        "modern_description": "Lay 16 cards (8 pre-selected pairs) in 4 rows of 4, according to a position table coded by 'MUTUS DEDIT NOMEN COCIS' (Latin: 'The dumb man gave his name to the cook'). Each repeated letter in this phrase corresponds to a pair of positions. Leave the room; spectators memorize two matching cards. Return and ask which row each card is in — the two row-answers decode through the mnemonic to give both positions.",
        "fun_fact": "MUTUS DEDIT NOMEN COCIS is one of the earliest mnemonic memory systems used in magic — predating the Major System of Gregor von Feinaigle (1808). The Latin phrase is complete nonsense, chosen purely because its repeated letters create the necessary code pattern.",
        "image_prompt": "A Victorian magician returning to a table of 16 cards laid in rows, spectators watching as he confidently names paired cards, an air of impossible memory, Victorian gentleman's club or parlor, 1862"
    },
    {
        "id": "cards-in-vase",
        "slug": "cards-in-vase",
        "title": "The Cards in the Vase",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "card-trick",
        "tags": ["cards", "vase", "rising", "chosen", "mechanical", "thread", "Victorian-stage"],
        "difficulty": "advanced",
        "players": "Performer + audience",
        "equipment": ["special vase with internal thread mechanism", "deck of cards"],
        "family_friendly": True,
        "original_description": "Three chosen cards are returned to the deck which is placed in a vase. On command, each chosen card rises mysteriously from the vase. The mechanism uses threads and small pulleys inside the vase — the performer triggers each rise by a concealed hair or thread attachment to their body.",
        "modern_description": "The special vase has three hidden slots with fine threads attached to each card position. When a chosen card is controlled to a specific position and placed in the vase, a barely visible thread runs from the card over a tiny concealed pulley to the performer's ring or shoe. A small movement rises that card dramatically from the pack. Three chosen cards can rise in sequence — apparently by mental command.",
        "fun_fact": "The Rising Cards is considered one of magic's great classics. The first documented mechanical rising cards apparatus appeared in a French magic book in 1584. Modern performers use sophisticated magnetic and electronic versions — but the basic thread method still works beautifully.",
        "image_prompt": "A Victorian stage magician gesturing dramatically at an ornate vase on a table, a playing card slowly rising from the packed deck inside it, an audience of Victorian theater-goers watching in astonishment, gaslit stage, 1862"
    },
    {
        "id": "metamorphosis-card-trick",
        "slug": "metamorphosis-card-trick",
        "title": "The Metamorphosis (Cards)",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "card-game",
        "subcategory": "card-trick",
        "tags": ["cards", "change", "metamorphosis", "half-cards", "eights", "aces", "Victorian"],
        "difficulty": "advanced",
        "players": "Performer + audience",
        "equipment": ["specially prepared half-and-half cards"],
        "family_friendly": True,
        "original_description": "Four eights are shown, change to blank cards, then to four twos, and finally the colors change from black to red — all through skillful handling of specially prepared half-painted cards stacked in a specific order. Each shuffle reveals a new face.",
        "modern_description": "The secret: pairs of cards are trimmed so one half shows one design and the other half shows another. By fanning and re-closing the cards in specific ways, different faces appear to replace the previous ones. The audience sees a complete transformation — eights to blanks to twos to color-changes — while the hand holds the same 'deck' throughout.",
        "fun_fact": "The Metamorphosis card effect pioneered the use of mechanically prepared cards — an innovation that led directly to the modern industry of specially manufactured magic cards. Today, dozens of commercial card effects use gimmicked card pairs based on this same half-card principle.",
        "image_prompt": "A Victorian magician's hands showing four playing card eights to an audience, then fanning them again to show four aces, the impossibility clear from the expressions of the watchers, an intimate evening gathering, 1862"
    },
    {
        "id": "trick-of-thirty-one",
        "slug": "trick-of-thirty-one",
        "title": "The Trick of Thirty-One",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "card-game",
        "subcategory": "card-game",
        "tags": ["cards", "mathematical", "thirty-one", "adding", "winning", "strategy", "Victorian"],
        "difficulty": "advanced",
        "players": "2",
        "equipment": ["playing cards (ace through 6, each suit)"],
        "family_friendly": True,
        "original_description": "Two players alternately turn up cards and add their values, the one who reaches exactly 31 winning. The cards are ace to six. The performer can always win by controlling the running totals to land on 3, 10, 17, and 24 — leaving the opponent unable to reach 31 first.",
        "modern_description": "Use only cards ace through 6. Take turns flipping a card and announcing the running total. Whoever makes the total reach exactly 31 wins — but going over 31 loses. The winning strategy: ensure you hit the totals 3, 10, 17, and 24 on your turns. Each of these is spaced 7 apart, and since the maximum card is 6, your opponent can never jump over your control points.",
        "fun_fact": "The Thirty-One trick is a mathematical game theory problem. The winning strategy (controlling positions modulo 7) is an instance of Nim theory — a branch of combinatorial game theory not formally developed until 1901, but implicitly understood by Victorian puzzle-masters.",
        "image_prompt": "Two Victorian gentlemen playing the Thirty-One card game, one clearly winning by pointing confidently at the running total written on paper, playing cards face-up on a gentleman's club table, gaslit evening atmosphere, 1862"
    },
    {
        "id": "sympathetic-inks",
        "slug": "sympathetic-inks",
        "title": "Sympathetic or Invisible Inks",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "scientific-recreation",
        "subcategory": "chemistry-demonstration",
        "tags": ["invisible-ink", "chemistry", "heat", "acid", "secret-writing", "Victorian", "science"],
        "difficulty": "intermediate",
        "players": "1+",
        "equipment": ["lemon juice or milk (for heat-revealed)", "paper", "candle or heat source"],
        "family_friendly": True,
        "original_description": "Various recipes produce invisible writing that can only be revealed by specific treatments: lemon juice or milk revealed by heat, lead acetate made visible by hydrogen sulfide gas, and sulphate of iron revealed by oak galls solution. The book provides multiple formulas for different secret writing scenarios.",
        "modern_description": "Write a secret message using lemon juice as ink on white paper — it dries invisible. To reveal it, hold the paper near a candle or iron — the organic acids in the lemon juice char at a lower temperature than the paper, revealing the message in brown. Milk works the same way. For more sophisticated invisible inks, various chemical developer pairs can be chosen to require a specific reagent — making the message readable only to someone who knows the right developer.",
        "fun_fact": "Invisible ink has a serious historical pedigree: George Washington's Continental Army used a silver nitrate invisible ink system during the Revolutionary War, with Hercules Mulligan as a key operative. James Jay (brother of Founding Father John Jay) invented the formula.",
        "image_prompt": "A Victorian child holding a blank paper near a candle flame, a secret message slowly appearing in brown on the page, an expression of delight, a Victorian study with a chemistry set visible, 1862 illustration"
    },
    {
        "id": "silver-tree",
        "slug": "silver-tree",
        "title": "The Silver Tree",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "scientific-recreation",
        "subcategory": "chemistry-demonstration",
        "tags": ["chemistry", "silver", "crystallization", "tree", "metal", "acid", "Victorian-science"],
        "difficulty": "intermediate",
        "players": "1+",
        "equipment": ["silver nitrate solution", "zinc strip", "glass beaker"],
        "family_friendly": False,
        "original_description": "A zinc strip placed in a silver nitrate solution causes silver to deposit on the zinc, forming beautiful tree-like crystal formations that grow visibly before the eye. The displaced metal prefers the zinc over the acid, creating a miniature metallic tree.",
        "modern_description": "Prepare a dilute silver nitrate solution in a beaker. Drop a clean zinc strip into the solution. Within minutes, silver metal begins to deposit on the zinc in beautiful feathery, tree-like crystalline formations that slowly grow taller and more elaborate. The zinc slowly dissolves while silver appears from solution. The result is a genuine silver tree grown from chemistry alone. (Silver nitrate stains skin black — handle carefully.)",
        "fun_fact": "The Silver Tree (and its cousin the Lead Tree, grown the same way) were among Victorian chemists' most beloved demonstrations precisely because the 'tree' growing from apparently nothing seemed genuinely miraculous. Michael Faraday performed it at the Royal Institution.",
        "image_prompt": "A glass beaker with a beautiful silver metallic tree formation growing from a zinc strip immersed in clear solution, light catching the crystalline silver branches, a Victorian chemistry laboratory with elegant glassware, a sense of alchemical wonder, 1862"
    },
    {
        "id": "cleopatras-pearls",
        "slug": "cleopatras-pearls",
        "title": "Cleopatra's Pearls",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "scientific-recreation",
        "subcategory": "chemistry-demonstration",
        "tags": ["chemistry", "pearl", "vinegar", "acid", "dissolution", "history", "Victorian"],
        "difficulty": "beginner",
        "players": "1+",
        "equipment": ["small chalk or calcium carbonate pellet", "glass of vinegar"],
        "family_friendly": True,
        "original_description": "A pearl (or chalk) dropped into vinegar dissolves — demonstrating the chemical principle by which Cleopatra supposedly dissolved her famous pearl earring in wine vinegar and drank it to win a wager with Mark Antony over who could throw the most lavish feast.",
        "modern_description": "Drop a small piece of chalk (calcium carbonate, the same material as a pearl) into a glass of white vinegar. Bubbles immediately form and the chalk dissolves over several minutes: CaCO3 + 2CH3COOH → Ca(CH3COO)2 + H2O + CO2. The bubbles are carbon dioxide. With a real pearl, dissolution would take much longer, but the principle is identical. A beautiful demonstration of acid-base chemistry.",
        "fun_fact": "Whether Cleopatra actually dissolved a pearl in wine vinegar is historically debated — the story comes from Pliny the Elder. Modern chemists have calculated that while a pearl would eventually dissolve in acetic acid, Cleopatra would have needed to wait days, not moments, at wine's acid concentration.",
        "image_prompt": "A Victorian chemistry demonstration, a chalk pellet fizzing and dissolving in a glass of clear vinegar with visible bubbles, a portrait of Cleopatra on the wall in the background, a scientific lecture setting with an engaged audience, 1862"
    },
    {
        "id": "infallible-prophet",
        "slug": "infallible-prophet",
        "title": "The Infallible Prophet",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "mind-reading-trick",
        "tags": ["mind-reading", "coins", "Latin", "mnemonic", "counters", "confederate", "Victorian"],
        "difficulty": "advanced",
        "players": "Performer + 3 spectators + optional assistant",
        "equipment": ["ring", "dime", "key", "small counters or pebbles"],
        "family_friendly": True,
        "original_description": "Three spectators each secretly choose one of three articles — a ring, a dime, and a key. While the performer's back is turned, three counters are distributed. Returning, the performer divines who took what — using the vowel positions in the Latin phrase 'Nunc Iterum Vide' as a memory key for counter distributions.",
        "modern_description": "Give three spectators three differently colored counters (1, 2, 3). Turn your back. Spectator A takes the ring, B takes the dime, C takes the key (in whatever combination they choose). They arrange themselves in the initial counter order. Turn around. The counter in each person's hand tells you the article via the Latin mnemonic: vowel positions in 'Nunc Iterum Vide' code A=ring, E=dime, I=key. Practice until the decoding is instantaneous.",
        "fun_fact": "The Infallible Prophet uses one of the oldest mnemonic systems in conjuring — Latin vowels as position codes. This system appears in Italian conjuring manuscripts of the 1580s and may be much older. The use of Latin gave the trick an aura of ancient wisdom.",
        "image_prompt": "A Victorian magician dramatically pointing to each of three spectators announcing what they hold hidden in their hands, the spectators looking amazed and checking their palms, a small Latin phrase written on a card secretly held by the performer, 1862"
    },
    {
        "id": "hat-and-die-trick",
        "slug": "hat-and-die-trick",
        "title": "The Hat and Die Trick",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "production",
        "tags": ["hat", "die", "vanish", "appear", "stage", "hollow", "Victorian-magic"],
        "difficulty": "advanced",
        "players": "Performer + audience",
        "equipment": ["two identical top hats", "hollow die (larger)", "solid die (smaller)", "cover"],
        "family_friendly": True,
        "original_description": "A die is shown and placed under a cover on a top hat; the cover is removed — the die has vanished. It is found in a lower hat. The method: the visible die is hollow with the real solid die inside; when the cover is removed, the hollow shell stays hidden in the hat while the cover conceals the transfer.",
        "modern_description": "The hollow die fits over the solid die. Show the hollow die (it looks solid). Place it on the hat brim under a cover. As the cover descends over the die, it catches the rim of the hollow shell and lifts it away invisibly when 'removed' — the hollow shell slides up inside the cover. The solid real die is left in the hat, to be 'revealed' by a spectator removing the hat. The die has traveled without being seen to move.",
        "fun_fact": "Top hat magic was so associated with the Victorian era that the top hat became the universal symbol of stage magic worldwide. The tradition of pulling things from top hats began in the 1830s and peaked in the 1860s-80s, coinciding with the peak popularity of The Magician's Own Book.",
        "image_prompt": "A Victorian stage magician in white tie and top hat performing with a die and hat on a table, the die apparently vanishing under a cone cover, dramatic gesture toward the second hat where it mysteriously appears, gaslit stage, 1862"
    },
    {
        "id": "magic-funnel",
        "slug": "magic-funnel",
        "title": "The Magic Funnel",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "liquid-trick",
        "tags": ["funnel", "water", "stop", "flow", "finger-hole", "stage", "Victorian"],
        "difficulty": "intermediate",
        "players": "Performer + audience",
        "equipment": ["special double-walled funnel with finger-controlled holes"],
        "family_friendly": True,
        "original_description": "Water pours freely from a funnel, then stops entirely at the performer's command — then pours again. A double-walled funnel has small holes in its inner tube; when the performer secretly covers one hole with a finger, air is excluded and water cannot flow. Uncovering the hole allows flow to resume.",
        "modern_description": "The magic funnel has an air tube running through its interior. Covering the hidden hole at the top with a finger creates a vacuum that holds water suspended in the funnel — the same principle as pressing your finger on a straw to hold liquid. Remove the finger and water flows freely. This looks completely miraculous: water apparently obeying commands without any visible mechanism.",
        "fun_fact": "The Magic Funnel demonstrates atmospheric pressure — the same principle prevents liquid from flowing from a covered test tube. Torricelli discovered the principle in 1644 as he invented the barometer, but Victorian conjurers exploited it for entertainment long before physics teachers used it for education.",
        "image_prompt": "A Victorian magician holding a funnel from which water flows freely, then dramatically commanding it to stop — the water halts mid-air — an amazed audience, water pitcher and basin on the demonstration table, 1862 stage illustration"
    },
    {
        "id": "magic-bottle",
        "slug": "magic-bottle",
        "title": "The Magic Bottle",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "liquid-trick",
        "tags": ["bottle", "wine", "milk", "water", "compartments", "stage", "Victorian"],
        "difficulty": "advanced",
        "players": "Performer + audience",
        "equipment": ["special compartmented bottle with finger-controlled pour holes"],
        "family_friendly": True,
        "original_description": "One ordinary-looking bottle pours wine, then water, then milk in succession at the performer's command — apparently containing all three liquids. The bottle has a compartmented interior with separate chambers, each with its own pouring hole controlled by the position of the performer's fingers.",
        "modern_description": "The bottle's interior is divided into three compartments — one with red wine, one with water, one with milk. Three tiny pour holes exit through the bottom of what appears to be a single spout. By covering different combinations of holes with the fingers of the hand holding the bottle, the performer controls which liquid flows. Shift finger positions smoothly between pours for a seamless display.",
        "fun_fact": "The Magic Bottle was considered the ultimate stage prop in Victorian parlor magic books, and detailed instructions were given for constructing one at home using a tin body with soldered interior partitions. Professional versions were sold by magician-suppliers in London and New York.",
        "image_prompt": "A Victorian stage magician pouring wine, then water, then milk from the same ornate bottle into different glasses, the audience registering increasing bewilderment at each new liquid, a theatrical stage setting with gaslight and red curtains, 1862"
    },
    {
        "id": "erratic-egg",
        "slug": "erratic-egg",
        "title": "The Erratic Egg",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "science-trick",
        "tags": ["egg", "glasses", "hopping", "blow", "aerodynamics", "Victorian", "physics"],
        "difficulty": "beginner",
        "players": "Performer + audience",
        "equipment": ["egg", "two wine glasses"],
        "family_friendly": True,
        "original_description": "An egg is placed between two wine glasses. By blowing sharply on one side, the egg hops from one glass to the other without being touched. The aerodynamic pressure difference causes the transfer.",
        "modern_description": "Balance an egg across the rims of two wine glasses placed close together. Blow a sharp, focused puff of air against the side of the egg nearest to one glass. The Bernoulli effect (lowered pressure on the blown side) combined with the force of the puff rolls the egg over the gap and into the far glass. This genuinely works with practice — the key is a sharp horizontal puff rather than a gentle continuous blow.",
        "fun_fact": "The Erratic Egg trick demonstrates Bernoulli's principle, described by Daniel Bernoulli in 1738. The same principle explains how airplane wings generate lift. Victorian science writers delighted in finding domestic demonstrations of this principle long before anyone dreamed of flight.",
        "image_prompt": "A Victorian drawing room, an egg balanced between two wine glasses, a person's face leaning close blowing a sharp puff of air, the egg beginning to roll impossibly from one glass to the other, curious onlookers, 1862 illustration"
    },
    {
        "id": "obedient-dime",
        "slug": "obedient-dime",
        "title": "The Obedient Dime",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "coin-trick",
        "tags": ["coin", "glass", "movement", "table", "nail", "scratch", "Victorian"],
        "difficulty": "intermediate",
        "players": "Performer + audience",
        "equipment": ["glass", "two coins", "hidden long thumbnail"],
        "family_friendly": True,
        "original_description": "A dime placed between two half-dollars under a glass moves from between them at the performer's scratch command. The secret: the performer's thumbnail scratches the tablecloth just outside the glass, propelling the dime through a slight vibration transmitted through the cloth.",
        "modern_description": "Place a dime between two larger coins under a glass. Tell the audience the dime will escape on command. Under the table or beside the glass, scratch your thumbnail briskly on the tablecloth in a specific motion. The friction-vibration travels through the cloth and nudges the dime out from between the half-dollars. It slides a definite distance, seeming to obey the 'command.'",
        "fun_fact": "The Obedient Dime is a beautiful example of how Victorian magic exploited scientific principles (acoustic/mechanical vibration through a surface) that audiences of the era would have no context for understanding, making a mundane physical fact appear miraculous.",
        "image_prompt": "A Victorian coin trick, a glass covering three coins (a dime between two larger coins), the performer's hand making a mystical gesture above while secretly scratching the cloth below, the dime visibly sliding free, audience watching, 1862"
    },
    {
        "id": "egg-bag-trick",
        "slug": "egg-bag-trick",
        "title": "The Egg Bag",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "production",
        "tags": ["egg", "bag", "appear", "vanish", "double-bag", "stage", "Victorian"],
        "difficulty": "advanced",
        "players": "Performer + audience",
        "equipment": ["special double-pocket cloth bag", "wooden eggs"],
        "family_friendly": True,
        "original_description": "Eggs appear and disappear repeatedly from a small cloth bag that can be turned inside out to show empty. The bag has a double lining with a secret pocket — eggs vanish into and appear from the hidden pocket while the visible inner bag seems completely empty.",
        "modern_description": "The Egg Bag has two layers: an outer bag and an inner false bottom with a side pocket between the layers. Place an egg in the visible bag — it seems to vanish when the bag is inverted (egg moves to the hidden pocket). Show the bag empty inside and out. Reach in and 'find' the egg in the hidden pocket, pulling it out. The egg can vanish and appear repeatedly. A borrowed spectator's egg can be made to vanish and reappear elsewhere.",
        "fun_fact": "The Egg Bag is a classic of close-up magic that has been performed continuously since at least the 16th century. It appeared in the 1584 book 'Discoverie of Witchcraft' by Reginald Scot — the first published exposure of conjuring secrets in English.",
        "image_prompt": "A Victorian street magician showing a small cloth bag inside-out (proving it empty) while an egg seems to have vanished, about to reach in and produce it again to gasps from the crowd, Victorian market setting, 1862"
    },
    {
        "id": "magnetized-cane",
        "slug": "magnetized-cane",
        "title": "The Magnetized Cane",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "levitation-trick",
        "tags": ["cane", "dance", "levitation", "thread", "horsehair", "Victorian", "stage"],
        "difficulty": "intermediate",
        "players": "Performer + audience",
        "equipment": ["walking cane", "horsehair or fine thread attached to clothing"],
        "family_friendly": True,
        "original_description": "A walking cane appears to dance and balance unsupported, following the performer's hand without touching it. A barely visible horsehair or fine thread runs from the cane to a hook on the performer's trouser leg — movements of the legs control the cane's dance.",
        "modern_description": "Attach a long fine horsehair between a hook on your trouser leg (near the knee) and the balance point of the cane. When standing, the thread is invisible. Move the cane to an apparently unsupported position — it stays upright, seemingly magnetized to your hand. By shifting your leg, the cane dances, bows, or falls gently. The discovery and concealment of the thread is the entire secret.",
        "fun_fact": "Fine horsehair was the standard invisible support thread in Victorian magic because it matched the refractive index of air better than any available manufactured thread. Magicians kept horse tails as prized materials — selecting individual hairs for specific tricks based on their fineness.",
        "image_prompt": "A Victorian magician making dramatic passes with his hand near a floating upright cane that dances without visible support, an astonished Victorian audience, a barely visible suggestion of a thread connecting the cane to the performer's leg, 1862"
    },
    {
        "id": "dancing-egg",
        "slug": "dancing-egg",
        "title": "The Dancing Egg",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "animation-trick",
        "tags": ["egg", "dancing", "thread", "animation", "music", "hat", "Victorian"],
        "difficulty": "intermediate",
        "players": "Performer + audience",
        "equipment": ["egg", "top hat", "fine hair or thread attached from egg to coat"],
        "family_friendly": True,
        "original_description": "An egg placed on top of a hat appears to dance and bob in time to music. A nearly invisible hair runs from the egg to the performer's coat — small movements of the body cause the egg to animate convincingly, responding to music as if alive.",
        "modern_description": "Rest the egg on the hat brim with a fine hair running secretly from the egg up to your coat lapel or a pin. When music plays, sway slightly in time — the movement translates through the hair to make the egg bob and turn convincingly on the hat. Stop moving and the egg stops. The synchronization with music makes the effect seem genuinely animated.",
        "fun_fact": "Animated-object magic was one of the most beloved categories of Victorian performance, reflecting the era's fascination with clockwork automata. When synchronizing with a live musician, the Dancing Egg could be performed with apparent spontaneity.",
        "image_prompt": "A Victorian magician at a party, a raw egg on a top hat appearing to dance and bob in time to piano music being played in the background, the audience laughing with delight, a fine thread almost visible if you know where to look, 1862"
    },
    {
        "id": "fire-eater",
        "slug": "fire-eater",
        "title": "The Fire Eater",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "fire-trick",
        "tags": ["fire", "eating", "tow", "niter", "dangerous", "stage", "Victorian-performance"],
        "difficulty": "advanced",
        "players": "Performer",
        "equipment": ["flax tow", "potassium nitrate (niter) solution", "candle"],
        "family_friendly": False,
        "original_description": "The performer appears to eat burning tow (flax fiber), placing glowing material in their mouth and quenching it. The method: tow soaked in niter (potassium nitrate) ignites easily in the presence of the mouth's warmth but can be extinguished safely by closing the mouth and excluding oxygen.",
        "modern_description": "Niter-soaked tow smolders with a glow that looks dramatic but produces minimal flame. Prepared tow can be touched to a candle, begin glowing, and then placed briefly in a closed mouth. The niter keeps the tow glowing at a temperature that is startling but manageable for a trained and experienced performer. This is a genuine fire act requiring proper training — never attempted without expert instruction.",
        "fun_fact": "Fire eating is one of the oldest performance arts in recorded history, practiced at ancient Roman circus events and throughout the medieval period by itinerant showmen. The fire eating scene in the 1862 book specifically notes it was 'not recommended for amateurs,' making it one of the earliest printed safety warnings in a magic book.",
        "image_prompt": "A Victorian fire-eating performer at a fairground with glowing tow in their mouth, dramatic gaslight illumination, a crowd gathered in amazement, the performer's face lit by the glow, a Victorian fairground setting, 1862"
    },
    {
        "id": "double-meaning-trick",
        "slug": "double-meaning-trick",
        "title": "The Double Meaning",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "catch-trick",
        "tags": ["wager", "hat", "drinking", "catch", "joke", "Victorian", "wordplay"],
        "difficulty": "beginner",
        "players": "2",
        "equipment": ["hat", "glass of any liquid"],
        "family_friendly": True,
        "original_description": "The performer bets they can drink a glass of liquid under a hat without touching the hat. The spectator accepts the wager. The performer gets on hands and knees, acts as if drinking from under the hat, then stands up and drinks the glass openly — having fulfilled the literal wager of drinking 'under' the hat (they were below it) without touching it.",
        "modern_description": "Bet a friend: 'I can drink this glass of water under my hat without touching the hat.' Place the hat on your head. Get down on all fours on the floor (you are now 'under' the hat in the literal sense). Mime drinking. Stand up, pick up the glass, and drink it openly. When the friend objects, point out: you drank the water while you were under the hat — exactly as promised. A word-trick disguised as a feat.",
        "fun_fact": "The Double Meaning and similar verbal trick wagers were a staple of Victorian gentlemen's club entertainment, where the ability to win a bet through wit rather than fact was considered a mark of intelligence and good humor.",
        "image_prompt": "A Victorian gentleman on all fours on a drawing room floor with a hat on his head, his friend watching in confusion, then the gentleman standing up triumphantly to drink the glass of water, amused onlookers, gaslit club setting, 1862"
    },
    {
        "id": "wizards-wit",
        "slug": "wizards-wit",
        "title": "The Wizard's Wit (Remove Middle Coin)",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "coin-trick",
        "tags": ["coin", "middle", "lateral-thinking", "impossible", "bet", "Victorian", "clever"],
        "difficulty": "beginner",
        "players": "2+",
        "equipment": ["3 coins"],
        "family_friendly": True,
        "original_description": "Three coins are laid in a row. The wager: remove the middle coin without touching it. The apparent impossibility dissolves with the solution — slide either side coin over the middle one. The middle coin is now on the side and can be picked up. The lateral-thinking solution makes this both a puzzle and a bet-winner.",
        "modern_description": "Place three coins in a row: A B C. The challenge: remove coin B (the middle one) without touching it. Solution: slide coin A over coin B so that A is now resting on B's position and C's position is empty. Now coin B is no longer the middle coin — pick it up. The 'middle' coin was the one you weren't supposed to touch, but the definition of middle changes with the coins' positions.",
        "fun_fact": "This puzzle/trick exploits the ambiguity between a fixed positional definition of 'middle' and a relational one. It was a popular gentleman's wager in Victorian clubs precisely because it can be won only by questioning the terms of the wager itself — a logical rather than physical solution.",
        "image_prompt": "Three coins in a row on a Victorian club table, one gentleman sliding the left coin over the middle one with a knowing smile, another looking puzzled having just lost the bet, a gaslit gentlemen's club atmosphere, 1862"
    },
    {
        "id": "old-man-and-his-chair",
        "slug": "old-man-and-his-chair",
        "title": "The Old Man and His Chair",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "string-trick",
        "tags": ["string", "figures", "cat-cradle", "story", "candles", "chairs", "Victorian"],
        "difficulty": "intermediate",
        "players": "1-2",
        "equipment": ["loop of string"],
        "family_friendly": True,
        "original_description": "Using only a loop of string and both hands, the performer creates a sequence of string figures while telling a story: candles, a chair, scissors, a policeman's staff. Each figure is formed through specific finger loops and pulls while the narrative gives the shapes meaning and context.",
        "modern_description": "Hold a string loop across both hands. As you tell the story of an old man, form the figure of two candles (a cat's cradle configuration). Then transform the string into a chair shape through a series of specific finger movements. Continue through scissors and a staff. Each figure is held up at the named point in the story — the narrative framework helps the audience follow the transformations.",
        "fun_fact": "String figure storytelling is one of the oldest art forms in human culture, practiced by indigenous peoples on every continent. Victorian anthropologists who encountered it in Polynesia, the Arctic, and Africa brought it back to Europe as a 'primitive' curiosity — not realizing it was equally present in their own folk traditions.",
        "image_prompt": "A Victorian performer's hands creating an elaborate string figure — clearly recognizable as a chair — while telling a story, family audience watching the transformation with interest, a parlor setting, 1862 illustration"
    },
    {
        "id": "new-perpetual-motion",
        "slug": "new-perpetual-motion",
        "title": "New Perpetual Rotary Motion",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "scientific-recreation",
        "subcategory": "physics-demonstration",
        "tags": ["spinning", "crystal", "quartz", "perpetual", "inclined-plane", "physics", "Victorian"],
        "difficulty": "intermediate",
        "players": "1+",
        "equipment": ["convex-cut quartz crystal disk", "smooth wetted surface", "inclined plane"],
        "family_friendly": True,
        "original_description": "A crystal disk cut with a convex bottom, placed on a wetted smooth inclined surface, spins continuously as it slides slowly down the plane. The rotation appears perpetual — the convex shape and thin water film create a gyroscopic spinning effect as the crystal descends.",
        "modern_description": "Cut or obtain a small round disk with a slightly convex underside. Lightly wet a smooth glass or marble inclined surface. Place the disk at the top and release — it spins as it slides, and the spinning continues for a remarkably long time due to the near-frictionless interface created by the water film. Called 'perpetual motion' in 1862, it actually demonstrates extremely low friction physics.",
        "fun_fact": "No true perpetual motion machine is possible — the Second Law of Thermodynamics forbids it. But Victorian audiences' fascination with 'perpetual motion' demonstrations reflected an era when the conservation of energy was only recently established (1850) and many still believed in mechanical perpetual motion.",
        "image_prompt": "A polished glass inclined plane slightly wetted, a small crystal disk spinning as it glides slowly down the surface, appearing to rotate indefinitely, a Victorian scientific demonstration table with instruments and curiosities, 1862"
    },
    {
        "id": "miraculous-apple",
        "slug": "miraculous-apple",
        "title": "The Miraculous Apple",
        "source_book": "The Magician's Own Book",
        "source_author": "Various",
        "source_year": 1862,
        "source_url": "https://archive.org/details/magiciansownbook00arno",
        "category": "magic-trick",
        "subcategory": "food-trick",
        "tags": ["apple", "division", "rind", "needle", "thread", "preparation", "Victorian"],
        "difficulty": "intermediate",
        "players": "Performer + audience",
        "equipment": ["apple", "fine needle", "thread"],
        "family_friendly": True,
        "original_description": "An apparently whole apple is divided into segments without breaking its skin. The method: a needle and thread are threaded through the apple under the skin in multiple directions before the performance. When the audience asks for the apple to be 'divided,' simply pulling the thread segments the flesh inside while the skin remains intact.",
        "modern_description": "Before the performance, insert a needle and thread into the apple at the stem, loop the thread around inside the apple through multiple insertion points, and withdraw the needle. The thread loops divide the apple into sections internally without visible external damage. Present the apple. When you pull a thread end (or have a spectator pull the stem), the apple falls apart into segments — the skin briefly intact until opened.",
        "fun_fact": "The Miraculous Apple is a pre-show preparation trick — the work is done long before the performance. This concept of 'advance preparation' is one of the most important principles in conjuring, allowing for seemingly impossible feats that require no skill in the moment.",
        "image_prompt": "A Victorian magician pulling gently on the stem of a whole apple before an astonished audience, the apple beginning to separate into perfectly divided segments without the skin having been cut, an intimate drawing room performance, 1862"
    },
]

print(f"Magician entries: {len(magician_entries)}")
