# The Sociable entries
sociable_entries = [
    # Acting proverbs / charades
    {
        "id": "when-the-cats-away",
        "slug": "when-the-cats-away",
        "title": "When the Cat's Away (Acting Proverb)",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "acting-game",
        "tags": ["acting", "proverb", "performance", "charade", "servants", "victorian", "drama"],
        "difficulty": "intermediate",
        "players": "5+",
        "equipment": ["simple costumes optional"],
        "family_friendly": True,
        "original_description": "Servants throw a party while their masters are away — Patrick, Bridget, Bob, and Mehitable invite guests, cause chaos, smash a hat, eat the refreshments, catch a thief, and are all dismissed when the masters unexpectedly return. The audience guesses the proverb being illustrated.",
        "modern_description": "Assign roles: servants and masters. The servants secretly plan and execute a wild party while the masters are 'out of town.' Assign each servant a comic personality and improvise the escalating chaos — spilled drinks, crashed furniture, unexpected guests, a thief, and the climactic early return of the masters who discover everything. The audience guesses the illustrated proverb: 'When the cat's away, the mice will play.'",
        "fun_fact": "Acting proverbs were among the most popular parlor entertainments in mid-Victorian America, combining amateur dramatics with the educational value of proverbs, making them respectable fun for mixed-age family evenings.",
        "image_prompt": "Victorian servants having a wild party in a grand drawing room, one dancing on the furniture, another eating from the master's plate, a shocked master in the doorway, chaotic and comedic scene, 1858 illustration style"
    },
    {
        "id": "honor-among-thieves-proverb",
        "slug": "honor-among-thieves-proverb",
        "title": "Honor Among Thieves (Acting Proverb)",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "acting-game",
        "tags": ["acting", "proverb", "brigand", "honor", "drama", "performance", "guessing"],
        "difficulty": "intermediate",
        "players": "4+",
        "equipment": ["costume scraps optional"],
        "family_friendly": True,
        "original_description": "Brigand Cordobello robs the virtuous Alice Vane, taking all her valuables — but when he discovers a miniature of her lost love, he returns it to her as promised, demonstrating that even thieves keep their word. The audience must guess the proverb illustrated.",
        "modern_description": "Cast players as the brigand Cordobello, the unfortunate Alice Vane, and assorted robbers and bystanders. Improvise the scene of the robbery with theatrical flair, building to the unexpected moment of honor when the villain returns the precious miniature. Ham it up with capes and dramatic poses. The audience guesses: 'There is honor among thieves.'",
        "fun_fact": "The phrase 'honor among thieves' appears in English literature as early as 1633 and was a Victorian favorite for acting proverbs because the dramatic contradiction — villains with principles — made for such entertaining theatre.",
        "image_prompt": "A Victorian amateur theatrical scene, a man in brigand costume dramatically returning a locket to a frightened woman, other 'robbers' watching solemnly, a forest backdrop painted on a sheet, parlor theater, 1858"
    },
    {
        "id": "phantom-charade",
        "slug": "phantom-charade",
        "title": "Phantom (Dramatic Charade)",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "charade",
        "tags": ["charade", "wordplay", "drama", "syllables", "acting", "guessing", "fan"],
        "difficulty": "intermediate",
        "players": "4+",
        "equipment": ["fan", "minimal props"],
        "family_friendly": True,
        "original_description": "A two-act dramatic charade for the word PHANTOM (PHAN-TOM). In the first scene, a clerk named Tom returns a lost fan to Mrs. Reeves in an office setting. In the second scene, a romantic subplot unfolds between Ellen and Tom. The audience must identify both syllables and the complete word.",
        "modern_description": "Prepare two short scenes, each illustrating one syllable of the mystery word: first scene suggests 'fan' (PHAN), second scene involves a character named Tom (TOM). Perform both acts with full Victorian melodrama, then let the audience guess. The challenge is that syllables may be homophones, alternate spellings, or only suggested by the action rather than spoken aloud.",
        "fun_fact": "Dramatic charades were distinct from simpler acting charades in that they required genuine scene-writing and rehearsal, making them the most theatrical parlor entertainment of the Victorian era and a training ground for amateur actors.",
        "image_prompt": "A Victorian parlor arranged as a stage, one person playing a clerk in a scene with a lady and a fan, another group of guests watching and whispering guesses to each other, gaslit Victorian drawing room, 1858 illustration"
    },
    {
        "id": "contest-charade",
        "slug": "contest-charade",
        "title": "Contest (Dramatic Charade)",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "charade",
        "tags": ["charade", "wordplay", "suitors", "competition", "riddle", "guessing", "drama"],
        "difficulty": "intermediate",
        "players": "5+",
        "equipment": ["bandbox prop"],
        "family_friendly": True,
        "original_description": "Two suitors, Beauchamp and Sparks, compete for the hand of Ada Lockitt by staging a CON (confidence trick or quiz) and a TEST (bandbox test). The audience must identify both syllable-scenes and deduce the complete word: CONTEST.",
        "modern_description": "Plan two scenes: the first depicting a 'con' or trick (CON), the second a formal test or trial (TEST). Cast two rival suitors and a desirable young woman. Improvise their competition using whatever props serve each syllable — a confidence trick for the first act, a formal challenge for the second. The audience debates and guesses the word CONTEST.",
        "fun_fact": "Victorian dramatic charades often satirized the institution of courtship, with suitors competing in elaborate theatrical challenges — a genteel way for families to poke fun at the anxious rituals surrounding marriage.",
        "image_prompt": "Two Victorian gentlemen suitors competing in a drawing room, one performing a trick while another stands with a bandbox, a young woman watching with amusement, seated audience of family members guessing, candlelit 1858 scene"
    },
    {
        "id": "consequences-sociable",
        "slug": "consequences-sociable",
        "title": "Consequences",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "writing-game",
        "tags": ["writing", "folding", "narrative", "absurd", "social", "story", "group"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": ["paper", "pencils"],
        "family_friendly": True,
        "original_description": "Each player writes a word or phrase on a paper, folds it to hide their contribution, and passes it to the next player. Each segment follows a fixed narrative structure: a man's name, met a woman's name, where they met, what he said to her, what she said to him, and what the consequence was. When unfolded, the absurd story is read aloud.",
        "modern_description": "Each player gets a piece of paper and writes the first element of the story (a man's name), then folds the paper to hide it and passes it left. Each player adds the next element — a woman's name, the meeting place, his words, her reply, and the consequence — always hiding their contribution before passing on. When all papers are complete, unfold and read each story aloud. The more incongruous the combinations, the better.",
        "fun_fact": "Consequences remained so popular that the Surrealist art movement adopted it in the 1920s as 'Exquisite Corpse,' using the same blind-contribution mechanic to create collaborative poetry and drawings.",
        "image_prompt": "Victorian ladies and gentlemen around a parlor table, each writing on a folded piece of paper and passing it along, looks of suppressed amusement, one person reading aloud from an unfolded paper to peals of laughter, gaslit room, 1858"
    },
    {
        "id": "crambo-sociable",
        "slug": "crambo-sociable",
        "title": "Crambo",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "word-game",
        "subcategory": "rhyming-game",
        "tags": ["rhyming", "poetry", "guessing", "wit", "verse", "group", "word"],
        "difficulty": "intermediate",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "One player thinks of a secret word and tells the others only a word that rhymes with it. The others must guess the word — but they may not say any rhyming word aloud; instead they must describe it by a definition or circumlocution. The thinker must deny each description until the correct word is guessed.",
        "modern_description": "Player one secretly chooses a word (say, 'king') and announces a rhyme clue ('I'm thinking of a word that rhymes with ring'). Other players deduce possible answers but must describe rather than say their guesses: 'Is it what a bell does?' or 'Is it the leader of a nation?' The thinker says yes or no until someone gets it right. That player becomes the next thinker.",
        "fun_fact": "Crambo is mentioned by name in Samuel Pepys's diary in 1660 and again in Robert Burns's poetry, making it one of the best-documented parlor word games of the 17th and 18th centuries.",
        "image_prompt": "A spirited Victorian parlor game, one person standing mysteriously while others gesture and describe words in roundabout ways, everyone competing to be first to guess correctly, a cosy firelit drawing room, 1858 illustration"
    },
    {
        "id": "proverbs-guessing",
        "slug": "proverbs-guessing",
        "title": "Proverbs (Guessing Game)",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "word-game",
        "subcategory": "word-guessing",
        "tags": ["proverbs", "guessing", "questions", "embedded", "word", "clever", "social"],
        "difficulty": "intermediate",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "One player goes out of the room. The remaining players choose a proverb and assign one word of it to each person. The guesser returns and asks each person a question; each must work their assigned word naturally into their answer. The guesser must identify the proverb from the scattered words.",
        "modern_description": "While one player waits outside, the group chooses a proverb — for example, 'A rolling stone gathers no moss' — and assigns one word to each player in order. The guesser returns and asks each person any question; each must incorporate their word naturally into their reply. By listening carefully to all the answers, the guesser should be able to reconstruct and name the hidden proverb.",
        "fun_fact": "This version of Proverbs was played at Victorian parties for its elegant simplicity — it required no equipment, suited any number of players, and gave shy guests a structured way to participate without needing to act or perform.",
        "image_prompt": "A Victorian parlor scene, one person standing in the center interrogating seated guests one by one, each guest carefully working a secret word into their answer, expressions of concentration and suppressed amusement, 1858 drawing room"
    },
    {
        "id": "what-is-my-thought-like",
        "slug": "what-is-my-thought-like",
        "title": "What Is My Thought Like?",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "word-game",
        "subcategory": "comparison-game",
        "tags": ["comparison", "wit", "guessing", "thought", "wordplay", "social", "Victorian"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "One player thinks of a person, place, or object without revealing it. Each other player in turn must say 'My thought is like a ——' with some object, and later must justify the comparison. After all comparisons are given, the hidden thought is revealed and each player defends their comparison with wit.",
        "modern_description": "Player one secretly thinks of something (a person, an object, a feeling). Going round the circle, each player says what their thought is like — naming any object they choose. Once all have spoken, the thinker reveals their secret thought. Now each player must cleverly justify how their chosen object really does resemble the revealed thought. The most creative justification wins applause.",
        "fun_fact": "What Is My Thought Like? was praised by Victorian games books for developing the faculty of analogy and metaphorical thinking — skills considered essential for poets, orators, and educated conversationalists.",
        "image_prompt": "Victorian ladies and gentlemen in a drawing room, one person dramatically revealing their secret thought while others prepare to defend wild comparisons, wit and laughter in the air, a richly furnished parlor, 1858 illustration"
    },
    {
        "id": "cross-purposes-sociable",
        "slug": "cross-purposes-sociable",
        "title": "Cross Purposes",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "word-game",
        "subcategory": "nonsense-game",
        "tags": ["nonsense", "questions", "answers", "mismatch", "absurd", "social", "word"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Each player whispers a question to their right-hand neighbor, who whispers an answer to their left-hand neighbor. When all are done, each player speaks their question aloud, followed by the answer they received — which belongs to a completely different question, producing absurd results.",
        "modern_description": "Sit in a circle. Each player whispers a question to the person on their right, then whispers an answer (to an imaginary different question) to the person on their left. The two whispered conversations happen simultaneously and independently. When all whispering is done, go around the circle: each player says their question, then reads the unrelated answer they received. The non-sequiturs are the entertainment.",
        "fun_fact": "Cross Purposes is the direct ancestor of the modern party game 'Telephone Pictionary,' and the 'crossed purposes' of mismatched questions and answers gave the English language the idiom 'talking at cross purposes.'",
        "image_prompt": "Victorian guests in a circle whispering to neighbors on both sides simultaneously, expressions of concentration and suppressed laughter, one person reading an absurd answer to a completely unrelated question, parlor setting 1858"
    },
    {
        "id": "dutch-concert",
        "slug": "dutch-concert",
        "title": "Dutch Concert",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "music-game",
        "tags": ["music", "instruments", "imitation", "noise", "group", "leader", "chaos"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Each player is assigned a musical instrument to imitate with their voice and body. A leader begins conducting the 'concert'; whenever the leader changes their own instrument imitation, all players must switch to imitating whatever instrument they are now doing. Anyone who fails to follow correctly pays a forfeit.",
        "modern_description": "Assign everyone an instrument to mime and vocalize — violin, trumpet, drum, etc. The leader begins performing theirs; everyone joins in. When the leader switches their instrument, all players must instantly switch to copying the leader's new instrument, abandoning their own. The beauty is pure chaos: the first to stop performing, switch too slowly, or make the wrong sound pays a forfeit.",
        "fun_fact": "The name 'Dutch Concert' was a Victorian expression for a discordant, chaotic noise — 'Dutch' being used loosely to mean foreign and incomprehensible. The game was deliberately designed to produce gloriously awful cacophony.",
        "image_prompt": "A chaotic Victorian parlor scene, guests mime-playing various instruments — violin, tuba, drums, flute — all looking at the leader to see when to switch, hilarious noise implied by the expressions, gaslit drawing room, 1858"
    },
    {
        "id": "elements-game",
        "slug": "elements-game",
        "title": "The Elements",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "word-game",
        "tags": ["elements", "earth", "air", "water", "fire", "quick-response", "animals", "category"],
        "difficulty": "intermediate",
        "players": "4+",
        "equipment": ["soft ball or handkerchief"],
        "family_friendly": True,
        "original_description": "A ball is thrown to any player while a leader calls 'Earth,' 'Air,' or 'Water.' The catcher must name an appropriate creature — an earth animal, a bird for air, a fish for water — before a count of ten. If the leader calls 'Fire,' the catcher must say nothing at all. Error or delay pays a forfeit.",
        "modern_description": "One player acts as the leader and holds a soft ball. The leader throws it to any player and immediately shouts one of the four elements: Earth, Air, Water, or Fire. The catcher must instantly name a creature belonging to that element before the group counts to ten aloud. Fire is the trap — shout 'Fire!' and the catcher must say absolutely nothing. Hesitate or speak wrongly, pay a forfeit.",
        "fun_fact": "The four classical elements game was popular from the Renaissance onward as a way of testing natural history knowledge — in the 1858 Victorian version, a wrong answer was worth a forfeit rather than a spot on the wrong element.",
        "image_prompt": "A Victorian parlor, one person throwing a small ball to another who looks startled, the thrower shouting 'Water!', the catcher about to name a fish while the group counts with raised fingers, energetic and amusing scene, 1858"
    },
    {
        "id": "simon-says-sociable",
        "slug": "simon-says-sociable",
        "title": "Simon Says",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "action-game",
        "tags": ["simon-says", "attention", "commands", "listening", "children", "group", "action"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "One player acts as 'Simon' and issues a series of commands. Players must obey only those commands preceded by 'Simon says.' Any player who obeys a command not prefaced with 'Simon says,' or who fails to obey one that was, pays a forfeit or is eliminated.",
        "modern_description": "The Simon player issues rapid commands: 'Simon says touch your nose! Simon says raise your right hand! Touch your left ear!' Players must follow commands prefaced by 'Simon says' but must freeze on bare commands. The pace is deliberately increased to catch players off guard. The last remaining player in a round becomes the next Simon.",
        "fun_fact": "Simon Says has been played under various names — 'Jacques dit' in France, 'O'Grady says' in Ireland, 'Simon says' in America — for at least 300 years, making it one of the most geographically universal children's games ever devised.",
        "image_prompt": "Victorian children and adults playing Simon Says, one person as leader giving commands, the group in various ridiculous positions — arms raised, noses touched, standing on one foot — one person caught doing the wrong thing, laughing parlor scene, 1858"
    },
    {
        "id": "Copenhagen-game",
        "slug": "Copenhagen-game",
        "title": "Copenhagen",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "action-game",
        "tags": ["string", "slapping", "action", "quick", "reflexes", "danish", "group"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": ["long loop of string"],
        "family_friendly": True,
        "original_description": "All players but one hold onto a long loop of string, forming a circle. The odd player outside tries to slap the hands of those holding the string. Anyone who fails to pull their hand away in time is out and takes the pursuer's place outside the circle.",
        "modern_description": "All players but one hold a single long loop of string, standing in a circle with the string at waist height. The player outside the circle tries to slap any hand on the string. Circle players must quickly pull their hands off the string before being slapped, but must always return to holding it. Anyone slapped swaps with the person outside.",
        "fun_fact": "Copenhagen was particularly popular in Scandinavia and was imported into British parlor games books as an exotic novelty. The string mechanic made it adaptable for large groups where a simple chase game would be impractical indoors.",
        "image_prompt": "Victorian party guests standing in a circle holding a loop of string at waist height, one person outside darting at hands, others snatching hands away at the last second, a parlor with furniture pushed back, lively action scene, 1858"
    },
    {
        "id": "cat-and-mouse-sociable",
        "slug": "cat-and-mouse-sociable",
        "title": "Cat and Mouse",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "chasing-game",
        "tags": ["cat", "mouse", "chasing", "circle", "children", "action", "fun"],
        "difficulty": "beginner",
        "players": "8+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Players form a circle holding hands. One player is the Cat, one is the Mouse. The circle raises or lowers arms to let the Mouse in or out while blocking the Cat. The Mouse must be caught; the circle sympathizes with the Mouse and works against the Cat.",
        "modern_description": "Two players are Cat and Mouse outside the circle. The circle raises their linked arms to let the Mouse dart through but drops them to block the Cat. The Mouse weaves frantically in and out of the circle while the Cat tries to follow — but the circle actively conspires to protect the Mouse. When the Cat finally catches the Mouse, a new pair takes their places.",
        "fun_fact": "Cat and Mouse is a perfect example of a game with collective sympathy built into its rules — the circle is instructed to favor the Mouse, creating natural drama and a sense of underdog triumph when the Cat eventually succeeds despite all obstacles.",
        "image_prompt": "Victorian children and adults in a large circle, arms raised to help one player (the Mouse) dart through while blocking another player (the Cat), the Cat looking frustrated trying to follow, a cheerful parlor or garden scene, 1858"
    },
    {
        "id": "hunt-the-hare",
        "slug": "hunt-the-hare",
        "title": "Hunt the Hare",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "chasing-game",
        "tags": ["hare", "chasing", "tapping", "chase", "group", "action", "replacement"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Players sit in a circle with one player (the Hare) running around the outside. The Hare taps any seated player, who must immediately jump up and chase the Hare around the circle. If the Hare reaches the empty seat before being caught, the chaser becomes the new Hare.",
        "modern_description": "All players sit in a circle. The Hare jogs around the outside, builds suspense, then quickly taps a seated player and runs. The tapped player leaps up and chases the Hare around the full circle. If the Hare makes it back to the vacant seat before being caught, the chaser becomes the new Hare. A game of speed, cunning, and tactical seat selection.",
        "fun_fact": "Hunt the Hare is essentially the same game known today as 'Duck Duck Goose' — it has been played in broadly similar forms across Europe for centuries, with local names referencing whatever animal the region considered the prime quarry for hunting.",
        "image_prompt": "Victorian party guests seated in a circle on chairs, one person (the Hare) tapping a seated player and sprinting away, the tapped player jumping up to give chase, a parlor with furniture rearranged, excited expressions, 1858"
    },
    {
        "id": "twirl-the-trencher-sociable",
        "slug": "twirl-the-trencher-sociable",
        "title": "Twirl the Trencher",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "action-game",
        "tags": ["plate", "spinning", "name-calling", "quick", "action", "forfeit", "group"],
        "difficulty": "beginner",
        "players": "6+",
        "equipment": ["wooden plate or round board"],
        "family_friendly": True,
        "original_description": "Players sit in a circle, each assigned a trade or name. One player spins a wooden trencher (plate) in the center and calls out a name. The named player must reach the trencher before it falls. Failure pays a forfeit — or the named player must guess a trade associated with the spinner's gesture.",
        "modern_description": "Each player is assigned a name or occupation. One player spins a wooden plate in the center of the circle and immediately calls out another player's name. That player must dash to catch the spinning plate before it falls flat. Fail and pay a forfeit. As a variation, the spinner mimes a trade or occupation and the named player must identify it before the plate stops spinning.",
        "fun_fact": "Twirl the Trencher was already an old game in 1858 — wooden trenchers (flat serving boards) had been the standard dish for centuries before ceramic plates replaced them, keeping the old name alive long after the original object became obsolete.",
        "image_prompt": "Victorian guests in a circle, a wooden plate spinning in the center, one person leaping from their chair to catch it before it falls while others watch with anticipation, a parlor drawing room, excited energy, 1858"
    },
    {
        "id": "jacks-alive-sociable",
        "slug": "jacks-alive-sociable",
        "title": "Jack's Alive",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "action-game",
        "tags": ["fire", "stick", "passing", "forfeit", "group", "twilight", "risk"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": ["thin stick or match that glows when blown"],
        "family_friendly": True,
        "original_description": "Players pass a glowing stick around a circle in the dark, each blowing it to maintain its glow. When a player receives it, they say 'Jack's alive!' while it glows. Whoever holds the stick when the glow dies out must pay a forfeit — often having their face marked with soot.",
        "modern_description": "In dim lighting, light a thin stick or long match to a slow smolder. Pass it quickly around the circle; each player blows on it to keep the glow alive and calls out 'Jack's alive!' as long as it glows. Whoever is holding the stick when it finally goes out must pay a forfeit (traditionally a mark of soot on the nose). Speed and urgency make this game genuinely exciting.",
        "fun_fact": "Jack's Alive is one of the oldest named parlor games in English, mentioned in records going back to the 17th century. The 'Jack' is thought to be a spark or ember — 'alive' meaning still burning — and the game was a fireside winter staple.",
        "image_prompt": "A dim Victorian parlor at night, guests passing a glowing stick around a circle in the firelight, one person blowing frantically to keep the glow alive, others watching anxiously, a sense of excitement and shadows, 1858 illustration"
    },
    {
        "id": "grand-mufti",
        "slug": "grand-mufti",
        "title": "Thus Says the Grand Mufti",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "action-game",
        "tags": ["imitation", "gesture", "mufti", "attention", "forfeit", "group", "action"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "One player is the Grand Mufti and makes various gestures. Players must imitate only those gestures introduced with 'Thus says the Grand Mufti.' If the Mufti makes a gesture without the sacred formula, players must remain still. Those who imitate wrongly pay a forfeit — the oriental-exotic theme being a popular Victorian fancy.",
        "modern_description": "The Grand Mufti makes increasingly complex and silly gestures. When they say 'Thus says the Grand Mufti—' before the gesture, players must copy it exactly. But gestures made without the formula must be ignored. The Mufti tries to trick players by blending formula and no-formula gestures at speed. This is essentially Simon Says with exotic Victorian branding.",
        "fun_fact": "Victorian parlor games frequently borrowed exotic names from the Ottoman Empire, Persia, and Egypt, reflecting the era's fascination with the 'Orient.' The Grand Mufti was a real Ottoman religious office whose authority seemed comically absolute to Victorian imaginations.",
        "image_prompt": "A Victorian parlor, one person acting as the Grand Mufti making an elaborate gesture while others try to decide whether to copy it or stay still, expressions of concentration and uncertainty, ornate drawing room with Turkish decorative touches, 1858"
    },
    {
        "id": "three-kingdoms",
        "slug": "three-kingdoms",
        "title": "Three Kingdoms",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "word-game",
        "subcategory": "category-guessing",
        "tags": ["kingdoms", "animal", "vegetable", "mineral", "guessing", "questions", "natural-history"],
        "difficulty": "beginner",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "One player thinks of an object from the animal, vegetable, or mineral kingdom. Others ask questions that can be answered yes or no, trying to narrow down what the object is. The questioners must determine the kingdom first, then zero in on the specific object.",
        "modern_description": "One player thinks of any object and announces which of the three kingdoms it belongs to: animal, vegetable, or mineral. Other players take turns asking yes/no questions to narrow down the possibilities. Classic questions include 'Is it alive?', 'Is it used by humans?', 'Is it larger than a breadbox?'. The player who correctly identifies the object wins the next turn.",
        "fun_fact": "Three Kingdoms is the earliest recorded version of what became the famous game 'Twenty Questions' — the animal/vegetable/mineral format was so well-established by the Victorian era that it was used as a pedagogical tool in natural history education.",
        "image_prompt": "Victorian ladies and gentlemen playing Twenty Questions, one player mysteriously holding a secret thought, others raising hands to ask yes/no questions, a natural history book lying open on the table, drawing room setting, 1858"
    },
    {
        "id": "tableaux-vivants-sociable",
        "slug": "tableaux-vivants-sociable",
        "title": "Tableaux Vivants",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "performance-game",
        "tags": ["tableau", "living-picture", "costume", "dramatic", "still", "art", "performance"],
        "difficulty": "intermediate",
        "players": "3+",
        "equipment": ["costumes", "simple backdrop or curtain", "props"],
        "family_friendly": True,
        "original_description": "Groups of participants arrange themselves to form a living picture of a historical scene, painting, or dramatic moment and hold it perfectly still while the audience observes. Popular scenes include 'The Army and Navy' (soldiers flanking the Goddess of Liberty) and 'The Drunkard's Home' (a miserable family scene).",
        "modern_description": "Participants secretly plan and costume a famous scene — from history, art, or mythology — then assemble behind a curtain. At a signal, the curtain opens to reveal them frozen in a perfect living picture. They hold the pose silently for thirty seconds to a minute. The audience applauds and identifies the scene. Illumination from behind a gauze screen created ghost effects particularly popular at Victorian gatherings.",
        "fun_fact": "Tableaux Vivants were enormously fashionable in Victorian America and Europe from the 1820s to 1900s. The most ambitious included professional lighting, gauze screens for supernatural effects, and original costume design — essentially amateur theatre without dialogue.",
        "image_prompt": "A Victorian parlor stage with a curtain pulled open, three elegantly costumed people frozen in a dramatic living picture — one as a soldier, one as a sailor, one as the Goddess of Liberty with flags — audience seated below applauding, 1858"
    },
    {
        "id": "scissors-crossed-not-crossed",
        "slug": "scissors-crossed-not-crossed",
        "title": "Scissors Crossed or Not Crossed",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "catch-game",
        "tags": ["trick", "catch", "scissors", "observation", "mystery", "legs", "secret"],
        "difficulty": "intermediate",
        "players": "4+",
        "equipment": ["scissors"],
        "family_friendly": True,
        "original_description": "A pair of scissors is passed around the group. Each time, the passer announces whether they pass them 'crossed' or 'not crossed.' New players cannot understand the pattern — the real secret is not the scissors' position but whether the passer's legs (ankles) are crossed or uncrossed when they pass.",
        "modern_description": "One player holds scissors and passes them to the next person, announcing 'I pass these crossed' or 'I pass these not crossed.' The uninitiated players try to figure out the pattern while those in the know play along perfectly. The trick: 'crossed' or 'not crossed' refers to whether the passer's own legs are crossed, not the scissors. The slowly dawning realization on players' faces is the real entertainment.",
        "fun_fact": "Scissors Crossed or Not Crossed is a classic catch-game that exploits the principle of misdirection — everyone looks at the scissors when the key information is actually elsewhere. Victorian parlor books called these 'mystification games.'",
        "image_prompt": "Victorian party guests passing scissors around a circle, some players baffled, one person knowingly crossing their legs as they pass, one newcomer staring at the scissors trying to figure out the pattern, a cosy parlor, 1858 illustration"
    },
    {
        "id": "shouting-proverbs-sociable",
        "slug": "shouting-proverbs-sociable",
        "title": "Shouting Proverbs",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "word-game",
        "subcategory": "word-guessing",
        "tags": ["proverbs", "shouting", "simultaneous", "noise", "chaos", "guessing", "group"],
        "difficulty": "intermediate",
        "players": "6+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "One player leaves the room. A proverb is selected and one word distributed to each remaining player. When the guesser returns, all players shout their word simultaneously, at the same moment, at the top of their voices. From this cacophony the guesser must identify the proverb.",
        "modern_description": "One player waits outside. Inside, a long proverb is chosen and each word assigned to one player. When the guesser returns and calls 'Ready!', all players bellow their word simultaneously at the top of their lungs. From the resulting delicious chaos, the guesser must somehow extract enough to identify the proverb. Give three chances, then reveal.",
        "fun_fact": "Shouting Proverbs was celebrated for being the loudest proper parlor game in the Victorian repertoire, and families were warned that it was not suitable for thin walls or nervous neighbors — which only increased its appeal.",
        "image_prompt": "Victorian ladies and gentlemen all shouting one word at the same time at the top of their lungs while one confused person covers their ears trying to make sense of the chaos, a chaotic and hilarious parlor scene, 1858"
    },
    {
        "id": "alphabet-i-love-my-love",
        "slug": "alphabet-i-love-my-love",
        "title": "I Love My Love with an A",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "word-game",
        "subcategory": "alphabet-game",
        "tags": ["alphabet", "vocabulary", "love", "sequential", "word", "memory", "social"],
        "difficulty": "intermediate",
        "players": "4+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "Each player in turn must complete the sentence 'I love my love with an [A] because she is [Adorable]; I took her to the sign of [the Anchor] and treated her to [Almonds]; her name is [Alice] and she comes from [Aberdeen]' — using a new letter of the alphabet for each round, supplying all words with the same letter.",
        "modern_description": "Players sit in a circle. Player one completes the formula using words beginning with A: 'I love my love with an A because she is Amusing; I took her to the sign of the Anchor and treated her to Apricots; her name is Agnes and she comes from Aberdeen.' Player two uses B, and so on through the alphabet. Anyone who hesitates or gives a wrong initial letter is out or pays a forfeit.",
        "fun_fact": "I Love My Love is mentioned in Lewis Carroll's Alice Through the Looking-Glass, where the White Queen plays it using the letter 'M' — its inclusion in one of the most beloved Victorian novels made it a must-know parlor game for the era.",
        "image_prompt": "Victorian family gathered around a parlor table, one person standing to recite their alphabet phrase while others listen critically ready to call out any mistake, bookshelves in background, warm evening light, 1858"
    },
    {
        "id": "bouquet-game",
        "slug": "bouquet-game",
        "title": "Bouquet",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "compliment-game",
        "tags": ["flowers", "language-of-flowers", "compliment", "social", "romantic", "Victorian", "bouquet"],
        "difficulty": "intermediate",
        "players": "4+",
        "equipment": ["real or paper flowers", "cards with flower names"],
        "family_friendly": True,
        "original_description": "Players each receive a flower or flower name. Using the Victorian language of flowers, each player must compose a little speech describing what kind of person their flower represents — or offer the flower as a symbolic compliment to another player. The audience judges whose bouquet speech is most elegant.",
        "modern_description": "Draw cards naming different flowers. Each player must compose a poetic description of a person using their flower's symbolism from the Victorian language of flowers (rose = love, violet = modesty, daisy = innocence, etc.) and present it as a compliment to a chosen player in the group. Judges vote for the most graceful or creative bouquet speech.",
        "fun_fact": "The Victorian language of flowers (floriography) was a genuine social code with published dictionaries — sending a specific bouquet could convey a complex romantic message without a single word being spoken, making it both practical and poetic.",
        "image_prompt": "Victorian ladies holding flowers in a parlor, one composing a poetic compliment while presenting a rose to another, a flower dictionary book lying open on the table, soft afternoon light through lace curtains, elegant 1858 scene"
    },
    {
        "id": "twenty-questions-sociable",
        "slug": "twenty-questions-sociable",
        "title": "Twenty Questions",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "word-game",
        "subcategory": "category-guessing",
        "tags": ["twenty-questions", "guessing", "yes-no", "deduction", "animal-vegetable-mineral", "classic", "social"],
        "difficulty": "intermediate",
        "players": "3+",
        "equipment": [],
        "family_friendly": True,
        "original_description": "One player thinks of any person, place, or thing. The other players ask up to twenty yes-or-no questions to deduce what it is. The thinker may answer only 'Yes,' 'No,' or 'Sometimes.' If the questioners fail in twenty questions, the thinker wins. The game is listed under 'Characters' in the original.",
        "modern_description": "One player silently chooses any subject — a person, a historical figure, an object — and announces only 'animal, vegetable, or mineral.' The group collaborates, asking up to twenty yes-or-no questions ('Is it alive?', 'Is it larger than a chair?', 'Is it in this room?'). If they identify it within twenty questions they win; if not, the thinker wins and goes again.",
        "fun_fact": "Twenty Questions became one of the first popular radio game shows in America in 1946 and later became a classic road-trip game. Its logical deduction structure has been studied by computer scientists as a model for decision tree algorithms.",
        "image_prompt": "A Victorian parlor with one person sitting smugly holding a secret thought, others leaning forward asking questions with fingers raised to count, looks of concentration and deduction, a cosy firelit room, 1858 illustration"
    },
    # Puzzles from The Sociable
    {
        "id": "magic-square-sociable",
        "slug": "magic-square-sociable",
        "title": "The Magic Square (Match Puzzle)",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "puzzle",
        "subcategory": "match-puzzle",
        "tags": ["matches", "squares", "removal", "puzzle", "matches", "geometric", "visual"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["matches or toothpicks"],
        "family_friendly": True,
        "original_description": "Arrange matches to form a pattern of squares. Remove exactly five matches so that exactly three squares remain. The challenge is to find which five matches to remove without breaking or overlapping.",
        "modern_description": "Arrange matches to form a grid of squares. The puzzle asks you to remove exactly five matches so that only three perfect squares remain. The solution requires careful observation of which matches are shared between squares — removing a shared match destroys multiple squares at once. Diagram the arrangement on paper first to think it through.",
        "fun_fact": "Match puzzles — also called Toothpick Puzzles — became enormously popular in the Victorian era when safety matches became household staples after 1855. They were ideal for after-dinner entertainment because the materials were always at hand.",
        "image_prompt": "A Victorian drawing room after dinner, matches arranged in square patterns on a polished table, one person removing matches thoughtfully while others watch to see if three squares remain, gaslit atmosphere, 1858 illustration"
    },
    {
        "id": "practicable-orchard",
        "slug": "practicable-orchard",
        "title": "The Practicable Orchard",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "puzzle",
        "subcategory": "geometrical-puzzle",
        "tags": ["trees", "geometry", "rows", "orchard", "puzzle", "arrangement", "mathematical"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["paper", "pencil"],
        "family_friendly": True,
        "original_description": "Plant sixteen trees in an orchard so that they form ten rows of four trees each. At first this seems impossible — sixteen trees making ten rows of four would require forty positions. The solution uses the diagonal and overlapping intersections of a clever geometric arrangement.",
        "modern_description": "Draw 16 dots (the trees) on paper so that exactly 10 straight rows of 4 trees each can be found. This requires placing trees at the intersections of multiple lines simultaneously — a tree counts in every row that passes through it. The solution involves a specific star or diamond pattern. Puzzle out the arrangement by starting with the rows and working backwards to placement.",
        "fun_fact": "The orchard planting puzzle type dates back to at least the 17th century and was a staple of Victorian puzzle books. The 'ten rows of four from sixteen trees' problem was considered a particularly elegant version because the solution is so unexpected.",
        "image_prompt": "An old puzzle diagram showing dots representing trees arranged in an orchard pattern with lines drawn through them showing the rows, a Victorian puzzle book lying open, pen-and-ink illustration style, 1858"
    },
    {
        "id": "blind-abbot-monks",
        "slug": "blind-abbot-monks",
        "title": "The Blind Abbot and His Monks",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "puzzle",
        "subcategory": "arithmetical-puzzle",
        "tags": ["arithmetic", "monks", "counting", "rows", "puzzle", "abbot", "historical"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["counters or coins"],
        "family_friendly": True,
        "original_description": "A blind abbot must count his nine monks arranged in rows of three on each side of a square without detecting that some have slipped away or extras have joined. The monks can vary their total from 18 to 36 while always showing exactly three in each row to their blind master.",
        "modern_description": "Place 9 counters in a 3x3 square with 3 in each row and each column (a standard grid). The puzzle: rearrange the same counters into configurations that make each side still appear to have 3, while the actual total secretly varies. Some configurations accommodate as few as 3 or as many as 36. Explore how corner positions are counted in multiple rows to create the deception.",
        "fun_fact": "The Blind Abbot puzzle appears in puzzles books from as early as the 14th century and is related to magic square mathematics. Its monastic setting reflects how educated medieval monks were the primary keepers of mathematical knowledge.",
        "image_prompt": "A medieval cloister setting with monks arranged at corners and sides of a square courtyard, a blindfolded abbot counting on his fingers, some monks sneaking away or extra monks slipping in, an illuminated manuscript illustration style"
    },
    {
        "id": "christians-and-turks",
        "slug": "christians-and-turks",
        "title": "Christians and Turks",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "puzzle",
        "subcategory": "counting-puzzle",
        "tags": ["counting", "josephus", "survivors", "circle", "elimination", "arithmetic", "puzzle"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["15 counters of two colors"],
        "family_friendly": True,
        "original_description": "Fifteen Christians and fifteen Turks are in a boat that must be lightened. They stand in a circle and every ninth person is thrown overboard. Arrange them so that all fifteen Christians survive and all fifteen Turks are sacrificed. The puzzle requires finding the correct starting arrangement.",
        "modern_description": "Place 30 counters (15 of two colors) in a circle. Count off every ninth counter and remove it. The challenge is to arrange the circle beforehand so that all 15 of one color are removed before any of the other color. The solution requires memorizing a specific pattern of arrangement. The counting-out process follows an elegant mathematical sequence.",
        "fun_fact": "This puzzle is a variant of the ancient 'Josephus Problem,' named after the historian Flavius Josephus who supposedly used similar counting logic to be the last survivor of a suicide circle in 67 AD. It has been studied by mathematicians for centuries.",
        "image_prompt": "A Victorian puzzle illustration showing a circle of alternating colored counters on a table, one person counting around the circle while another tracks on paper, a maritime map in the background, scholarly study atmosphere, 1858"
    },
    {
        "id": "nine-digits-magic",
        "slug": "nine-digits-magic",
        "title": "Nine Digits",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "puzzle",
        "subcategory": "arithmetical-puzzle",
        "tags": ["magic-square", "arithmetic", "digits", "numbers", "rows", "sums", "puzzle"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["paper", "pencil"],
        "family_friendly": True,
        "original_description": "Arrange the nine digits 1 through 9 in a three-by-three square so that every row, every column, and both diagonals add up to the same number — fifteen. This is the oldest known magic square.",
        "modern_description": "Draw a 3×3 grid. Place each digit from 1 to 9 exactly once in the nine cells so that all rows, all columns, and both diagonals sum to 15. There are essentially only one solution (rotations and reflections aside): 2 is in the top-left, 7 in the top-middle, 6 in the top-right, 9, 5, 1 in the middle, and 4, 3, 8 along the bottom — or any rotation thereof. A beautiful mathematical challenge.",
        "fun_fact": "The 3×3 magic square summing to 15 is called the Lo Shu square and appears in Chinese legend as a pattern carried on the back of a tortoise. It is the earliest known magic square, appearing in Chinese mathematical texts from around 650 BC.",
        "image_prompt": "A 3x3 grid with the digits 1-9 arranged in a magic square on aged parchment paper, quill and ink visible, a Victorian mathematical study with books on algebra, puzzle books, and an oil lamp, scholarly atmosphere"
    },
    {
        "id": "agon-queens-guards",
        "slug": "agon-queens-guards",
        "title": "Agon (Queen's Guards)",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "board-game",
        "subcategory": "strategy-game",
        "tags": ["board-game", "strategy", "queen", "guards", "hexagonal", "Victorian", "two-player"],
        "difficulty": "intermediate",
        "players": "2",
        "equipment": ["Agon board (hexagonal grid)", "pieces: 1 queen + 6 guards per player"],
        "family_friendly": True,
        "original_description": "Two players each command a Queen and six Guards arranged on a hexagonal board. The goal is to maneuver your Queen to the central hexagon, surrounded by all six of your Guards, before your opponent does the same. Pieces may be captured and sent back to the starting rim.",
        "modern_description": "Set up on a hexagonal board with both queens and their guards around the rim. Each turn, move one piece to an adjacent hexagon. Move your queen toward the center while surrounding her with guards. Capture opponents by flanking them — a piece between two of yours is sent back to the rim. Win by placing your queen in the exact center hex with all six guards around her.",
        "fun_fact": "Agon is believed to be the oldest board game using a hexagonal grid and one of the first games specifically designed for and by women — it was patented in France in 1842 and quickly spread to Britain as an elegant drawing room game.",
        "image_prompt": "Two Victorian ladies playing Agon at a parlor table, the hexagonal board between them with colored queen and guard pieces, one player deep in strategic thought, gaslit Victorian drawing room, 1858 illustration"
    },
    {
        "id": "merelles-nine-mens-morris-sociable",
        "slug": "merelles-nine-mens-morris-sociable",
        "title": "Merelles (Nine Men's Morris)",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "board-game",
        "subcategory": "strategy-game",
        "tags": ["morris", "strategy", "board-game", "mill", "Victorian", "two-player", "historical"],
        "difficulty": "intermediate",
        "players": "2",
        "equipment": ["Nine Men's Morris board", "9 pieces per player in two colors"],
        "family_friendly": True,
        "original_description": "Two players take turns placing their nine pieces on a board of three concentric squares connected by lines. Completing a row of three (a 'mill') allows removing an opponent's piece. When a player is reduced to two pieces, they lose. An ancient game of strategic placement and capture.",
        "modern_description": "The board has three concentric squares connected by lines at midpoints, creating 24 intersections. In the placement phase, take turns placing pieces one at a time, trying to form rows of three (mills). Each mill formed lets you remove an opponent's piece. In the movement phase, slide pieces along lines to form new mills. Reduce the opponent to 2 pieces or trap them so they cannot move to win.",
        "fun_fact": "Nine Men's Morris boards have been carved into medieval cathedral stonework across Europe and were played in ancient Egypt, Rome, and Viking Scandinavia. Shakespeare references 'the nine men's morris' as a game he knew well.",
        "image_prompt": "A medieval-style wooden Nine Men's Morris board on a Victorian parlor table, black and white pieces positioned mid-game, two players in Victorian dress studying the position, an antique atmosphere, 1858 illustration"
    },
    {
        "id": "solitaire-sociable",
        "slug": "solitaire-sociable",
        "title": "Solitaire (Peg Solitaire)",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "puzzle",
        "subcategory": "counter-puzzle",
        "tags": ["solitaire", "pegs", "board", "solo", "logic", "jumping", "classic"],
        "difficulty": "advanced",
        "players": "1",
        "equipment": ["peg solitaire board with 33 holes", "32 pegs"],
        "family_friendly": True,
        "original_description": "Thirty-three holes are arranged in a cross pattern. Thirty-two pegs fill all holes but the center. Players jump one peg over an adjacent peg into an empty hole, removing the jumped peg. The goal is to reduce all 32 pegs to exactly one peg remaining in the center hole.",
        "modern_description": "Fill all holes except the center with pegs. A legal move jumps one peg over an adjacent peg (horizontally or vertically) into a vacant hole; the jumped peg is removed. Continue making jumps until no more moves exist. The perfect solution leaves exactly one peg, sitting in the very center of the board. An elegant solo logic puzzle with many dead-end paths and one celebrated solution.",
        "fun_fact": "Peg Solitaire was invented in France around 1687 and became fashionable across Europe. Leibniz mentioned analyzing it mathematically in 1710, and the perfect single-center solution was not published until 1912 — over 200 years of puzzlers trying.",
        "image_prompt": "A Victorian circular peg solitaire board on a table, most pegs remaining with several holes empty, one player's hand reaching to make the next jump, a late evening study setting with books on games and puzzles, 1858"
    },
    {
        "id": "puzzle-purse",
        "slug": "puzzle-purse",
        "title": "The Puzzle Purse",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "puzzle",
        "subcategory": "mechanical-puzzle",
        "tags": ["purse", "rings", "disentanglement", "mechanical", "Victorian", "trick", "manipulation"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["fabric purse threaded with rings on a cord"],
        "family_friendly": True,
        "original_description": "A fabric purse is closed and secured with a cord threaded through rings. The puzzle is to open the purse and remove the rings without untying the cord — a feat that seems impossible but has an elegant mechanical solution.",
        "modern_description": "The puzzle purse has a cord threaded through several rings in a specific interlocked pattern. The challenge is to open the purse and separate the rings from the cord entirely without cutting anything or untying the knot. The solution involves carefully routing the cord through specific ring combinations in the correct order — a three-dimensional disentanglement problem.",
        "fun_fact": "The Puzzle Purse was a popular Victorian novelty gift, often given as a Valentine's Day present with a love note hidden inside. The recipient had to solve the puzzle to access the message — making the gift both sentimental and intellectually challenging.",
        "image_prompt": "A Victorian velvet purse with a cord threaded through metal rings sitting on a table, one person examining it perplexedly, trying various manipulations, a parlor setting with sewing items and accessories nearby, 1858 illustration"
    },
    {
        "id": "problem-of-money",
        "slug": "problem-of-money",
        "title": "The Problem of Money",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "puzzle",
        "subcategory": "counter-puzzle",
        "tags": ["coins", "leaping", "counter", "movement", "puzzle", "arithmetic", "sequence"],
        "difficulty": "intermediate",
        "players": "1",
        "equipment": ["10 coins or counters"],
        "family_friendly": True,
        "original_description": "Ten half-dimes are arranged in a row. Each coin must leap over exactly two others to land on a new position, and must do this in a specific sequence so that all coins end up properly rearranged. The puzzle requires finding the correct order of moves.",
        "modern_description": "Lay 10 coins in a row. Assign each a number from 1 to 10. Each move consists of picking up one coin and placing it on another coin two positions away (jumping over two). The goal is to rearrange all coins into five stacks of two in the fewest moves possible, each move being a legal leap of exactly two. Work out the sequence on paper before moving coins.",
        "fun_fact": "Coin-jumping puzzles like this one were popular throughout the Victorian era as a way of demonstrating that what looks impossible often has an elegant solution — Victorian puzzle books delighted in using simple everyday objects to create surprising mental challenges.",
        "image_prompt": "Ten coins arranged in a row on a polished table, one coin being held by a Victorian hand about to be placed two positions away, a puzzle book open showing the problem, afternoon light through a window, 1858 illustration"
    },
    {
        "id": "balanced-coin-sociable",
        "slug": "balanced-coin-sociable",
        "title": "The Balanced Coin",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "parlor-game",
        "subcategory": "science-trick",
        "tags": ["balance", "cork", "coin", "needle", "science", "demonstration", "trick"],
        "difficulty": "intermediate",
        "players": "Performer + audience",
        "equipment": ["cork", "two forks", "coin", "needle"],
        "family_friendly": True,
        "original_description": "A coin is made to spin and balance on the point of a needle stuck in a cork. Two forks are inserted into the cork on opposite sides to lower the center of gravity, allowing the coin-and-cork-and-forks assembly to balance perfectly on the needle point and spin freely.",
        "modern_description": "Stick a needle upright in a cork. Press two forks symmetrically into opposite sides of the cork, angled downward. Place a coin on top of the needle point and give it a spin — the whole assembly balances and rotates indefinitely. The physics: the forks lower the system's center of gravity below the balance point, creating stable equilibrium. A perfect dinner-table demonstration.",
        "fun_fact": "This trick demonstrates the principle of center of gravity that fascinated Victorian natural philosophers. The Sociable's 'Science in Sport' section featured dozens of such experiments as a way of making physics both visible and entertaining.",
        "image_prompt": "A Victorian table with a needle stuck in a cork, two forks inserted on opposite sides balancing on the needle point with a spinning coin on top, a gentleman demonstrating this physics marvel to amazed guests, 1858 drawing room"
    },
    {
        "id": "thaumatrope-sociable",
        "slug": "thaumatrope-sociable",
        "title": "The Thaumatrope",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "scientific-recreation",
        "subcategory": "optical-illusion",
        "tags": ["optical", "spinning", "illusion", "persistence-of-vision", "thaumatrope", "science", "Victorian"],
        "difficulty": "beginner",
        "players": "1+",
        "equipment": ["card disc", "two strings", "drawings on both sides"],
        "family_friendly": True,
        "original_description": "A card disc with a bird drawn on one side and a cage drawn on the other is attached to two strings. Twisting and releasing the strings makes the disc spin rapidly — and the two images appear to merge into one picture of a bird inside the cage, demonstrating persistence of vision.",
        "modern_description": "Draw a bird on one side of a small round card and an empty birdcage on the other. Thread strings through holes on opposite sides. Hold both ends, wind the strings by swinging the disc in a circle, then pull both strings taut to make it spin. As the disc spins fast, your eyes merge the two images and you see a bird inside the cage. The disc spins forward and back by alternating tension.",
        "fun_fact": "The thaumatrope was invented in 1826 and became a beloved scientific toy throughout the Victorian era. Its principle of persistence of vision directly led to the invention of cinema — the thaumatrope is a direct ancestor of the motion picture.",
        "image_prompt": "A Victorian child holding strings attached to a spinning round card, one side showing a bird and the other a cage, the illusion creating a bird-in-cage image as it spins, a colorful and delightful scientific toy, 1858 illustration"
    },
    {
        "id": "magic-tumbler",
        "slug": "magic-tumbler",
        "title": "The Magic Tumbler",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "scientific-recreation",
        "subcategory": "science-demonstration",
        "tags": ["water", "glass", "inverted", "air-pressure", "science", "demonstration", "atmospheric"],
        "difficulty": "beginner",
        "players": "Performer + audience",
        "equipment": ["glass", "water", "playing card or stiff paper"],
        "family_friendly": True,
        "original_description": "Fill a glass to the brim with water. Cover it with a playing card or stiff paper. Holding the card in place, invert the glass completely. Release the hand — and the water stays inside the inverted glass, held up by atmospheric pressure against the card.",
        "modern_description": "Fill a glass completely to the rim with water. Place a playing card flat on top. Press one hand firmly on the card, then flip the glass upside down. Carefully move your hand away from the card — the water remains suspended in the inverted glass, held by atmospheric pressure pushing up on the card. The trick works because air pressure (14.7 PSI) easily supports the small column of water.",
        "fun_fact": "This classic experiment demonstrates atmospheric pressure so dramatically that it was used in Victorian science lectures to audiences of thousands. Evangelist showmen used it as a metaphor for divine sustenance — God holding up those who depend on Him.",
        "image_prompt": "A Victorian gentleman holding an inverted glass of water upside down over a table, a playing card between glass and water, triumphant expression as the water stays suspended, audience watching in amazement, 1858 drawing room science demonstration"
    },
    {
        "id": "boomerang-card",
        "slug": "boomerang-card",
        "title": "The Boomerang (Card Trick)",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "scientific-recreation",
        "subcategory": "aerodynamic-demonstration",
        "tags": ["boomerang", "card", "spinning", "returning", "aerodynamics", "science", "trick"],
        "difficulty": "intermediate",
        "players": "1+",
        "equipment": ["visiting card or playing card"],
        "family_friendly": True,
        "original_description": "A stiff card is bent slightly and thrown with a particular wrist action so that it spins and curves through the air, returning like a boomerang to the thrower. The card creates its own gyroscopic flight path when given proper backspin.",
        "modern_description": "Fold a playing card slightly along its length. Hold it vertically at one end between thumb and forefinger. Flick your wrist sharply to release it with backspin — like throwing a frisbee but vertically. When released correctly, the card curves away and returns to approximately where you threw it from. It takes practice but the aerodynamics are genuine and reproducible.",
        "fun_fact": "Australian boomerangs were a sensation at Victorian exhibitions, and 'boomerang tricks' with cards, hoops, and sticks became fashionable parlor diversions in the 1850s-60s as the unusual returning trajectory fascinated European observers.",
        "image_prompt": "A Victorian gentleman throwing a bent playing card with a sharp wrist motion, the card curving in a visible arc back toward him, an amused audience watching the aerial trick, a parlor or garden setting, 1858 illustration"
    },
    {
        "id": "fire-from-cane",
        "slug": "fire-from-cane",
        "title": "Fire from a Cane",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "scientific-recreation",
        "subcategory": "friction-demonstration",
        "tags": ["fire", "friction", "cane", "rattan", "primitive", "science", "demonstration"],
        "difficulty": "intermediate",
        "players": "1+",
        "equipment": ["two rattan canes"],
        "family_friendly": False,
        "original_description": "Two rattan canes are struck against each other rapidly. If struck at the right angle and speed, friction ignites the rattan fibers and a genuine spark or small flame can be produced — demonstrating the primitive method of fire-starting used for thousands of years before matches.",
        "modern_description": "This demonstration shows how friction can produce fire using only plant fibers. Hold one rattan cane firmly and strike the other against it repeatedly at a sharp angle, maintaining rapid strokes. Friction heats the contact point until the fibers ignite. This was the original human fire-making method and still works on dry rattan today. For safety, hold over a non-flammable surface.",
        "fun_fact": "This experiment was included in Victorian parlor books as a link to primitive human history — Victorian readers were fascinated by how their scientifically advanced society had emerged from ancestors who made fire by rubbing sticks.",
        "image_prompt": "A Victorian scientific demonstration, a gentleman rubbing two rattan canes together rapidly over a saucer, a small wisp of smoke beginning to appear, an audience of interested spectators, scientific apparatus and books visible, 1858"
    },
    {
        "id": "smoke-bottles",
        "slug": "smoke-bottles",
        "title": "The Smoke Bottles",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "scientific-recreation",
        "subcategory": "chemistry-demonstration",
        "tags": ["chemistry", "smoke", "ammonia", "acid", "clouds", "demonstration", "Victorian-science"],
        "difficulty": "advanced",
        "players": "Performer + audience",
        "equipment": ["two glass bottles", "hartshorn (ammonia) solution", "salt solution", "corks"],
        "family_friendly": False,
        "original_description": "Two bottles are prepared — one containing hartshorn (ammonia) vapors and one containing muriatic acid (hydrochloric acid) fumes. When their corks are removed simultaneously and the bottle mouths brought close together, a dense white cloud of smoke instantly fills the air between them.",
        "modern_description": "Prepare one bottle with ammonia solution and another with hydrochloric acid solution. Open both simultaneously near each other (at arm's length, away from face). The gases react instantly: NH3 + HCl → NH4Cl, creating a dramatic dense white cloud of ammonium chloride 'smoke.' An impressive demonstration of acid-base chemistry. Adult supervision required; perform in ventilated area only.",
        "fun_fact": "This reaction between ammonia and hydrochloric acid is so visually dramatic that Victorian chemistry demonstrators called it 'bottled lightning' — the white smoke appears instantly and fills a large volume. The same reaction is used today in theatrical fog effects.",
        "image_prompt": "A Victorian chemistry demonstration, two bottles releasing white smoke that billows into a dramatic cloud in the air between them, an audience leaning back in amazement, a laboratory or parlor setting with chemical apparatus, 1858"
    },
    {
        "id": "iron-filings-magnetism",
        "slug": "iron-filings-magnetism",
        "title": "Magnet Experiments",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "scientific-recreation",
        "subcategory": "physics-demonstration",
        "tags": ["magnetism", "iron", "filings", "field", "science", "physics", "demonstration"],
        "difficulty": "beginner",
        "players": "1+",
        "equipment": ["bar magnet", "iron filings", "paper"],
        "family_friendly": True,
        "original_description": "Place a bar magnet under a piece of paper and sprinkle iron filings on the paper above it. Tap the paper gently and the iron filings arrange themselves into the lines of the magnetic field — a beautiful, instantly visible map of an invisible force.",
        "modern_description": "Place a bar magnet on a table and lay a sheet of paper over it. Sprinkle iron filings evenly over the paper from a small height. The filings will align along the magnetic field lines — forming elegant arcs from pole to pole. Tap the paper gently to let the filings settle into their final positions. The result is a perfect physical map of the magnetic field, invisible to the naked eye but made visible by the iron.",
        "fun_fact": "Magnetic field visualization using iron filings was one of the most performed demonstrations of the Victorian era, popularized by Michael Faraday in the 1840s. Faraday's concept of field lines — literally visible here — became the foundation of modern electromagnetism.",
        "image_prompt": "Iron filings arranged in graceful arcs around a bar magnet on paper, clearly showing the magnetic field lines, a Victorian scientific instrument table with books on physics and a magnifying glass, academic and elegant, 1858"
    },
    {
        "id": "fire-under-water",
        "slug": "fire-under-water",
        "title": "Fire Under Water",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "scientific-recreation",
        "subcategory": "chemistry-demonstration",
        "tags": ["chemistry", "potassium", "water", "fire", "dangerous", "Victorian-science", "demonstration"],
        "difficulty": "advanced",
        "players": "Performer + audience",
        "equipment": ["potassium metal", "large bowl of water"],
        "family_friendly": False,
        "original_description": "A small piece of potassium metal is placed on the surface of a bowl of water. The metal immediately reacts, skittering across the surface with a violet flame while producing hydrogen gas. The metal literally burns on top of the water — seemingly impossible and utterly spectacular.",
        "modern_description": "Use a very tiny piece of potassium metal (dangerous — handle with forceps only, never touch with bare hands). Drop it onto the surface of a large bowl of water. Potassium reacts violently with water: 2K + 2H2O → 2KOH + H2. The hydrogen gas ignites from the heat of reaction, producing a distinctive violet flame. The metal spins across the water surface burning. Never use pieces larger than a pea — this is a professional demonstration only.",
        "fun_fact": "Humphry Davy discovered potassium metal in 1807 and performed exactly this water demonstration before astonished audiences at the Royal Institution — he reportedly laughed with delight at the violet flame, one of the most dramatic reactions in chemistry.",
        "image_prompt": "A dramatic Victorian chemistry demonstration, a piece of potassium dancing across a bowl of water with a violet flame, an audience of Victorian gentlemen and ladies staring in amazement and concern, a scientific lecture hall, 1858"
    },
    {
        "id": "mineral-chameleon",
        "slug": "mineral-chameleon",
        "title": "The Mineral Chameleon",
        "source_book": "The Sociable, or One Thousand and One Home Amusements",
        "source_author": "Various",
        "source_year": 1858,
        "source_url": "https://archive.org/details/cu31924080786779",
        "category": "scientific-recreation",
        "subcategory": "chemistry-demonstration",
        "tags": ["chemistry", "color-change", "manganese", "solution", "Victorian-science", "demonstration", "visual"],
        "difficulty": "advanced",
        "players": "Performer + audience",
        "equipment": ["permanganate of potash", "water", "various reducing agents", "glasses"],
        "family_friendly": False,
        "original_description": "A solution of permanganate of potash dissolved in water produces a deep purple liquid that changes through green, blue, and ultimately colorless as various chemicals are added. The 'mineral chameleon' was prized for the sheer beauty of its color transformations.",
        "modern_description": "Dissolve a small amount of potassium permanganate in water to produce a vivid purple solution. Add reducing agents in sequence — ferrous sulfate, sodium sulfite, etc. — and the solution transforms through a remarkable sequence: purple → brown → green → clear. Each color change represents a different manganese oxidation state. A visually spectacular multi-step chemistry demonstration.",
        "fun_fact": "The name 'mineral chameleon' was given by Victorian chemists because, like the reptile, the manganese compound seemed to change its appearance at will. Potassium permanganate remains one of the most colorful compounds in chemistry, used today as a water purification agent.",
        "image_prompt": "Three Victorian glass beakers showing progressively different colors of a chemical solution — deep purple, green, and clear — demonstrating the mineral chameleon color changes, a chemistry demonstration table with elegant scientific apparatus, 1858"
    },
]

print(f"Sociable entries: {len(sociable_entries)}")
